{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "bitcoincore",
    "version": "v0.1.0-pcash.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash",
          "module": "hd-wallet-kit-android",
          "version": {
            "requires": "46a441d"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bitcoincore-v0.1.0-pcash.25.aar",
          "url": "bitcoincore-v0.1.0-pcash.25.aar",
          "size": 1240801,
          "sha512": "a2901c15c581fffa5736cb9998715c15896b0ca3ff9f08215d69805c9a87de577b6080f3040f46b8e8e97dc9a9a5adbb6c1f2a3e71eca086f9c843786efdebac",
          "sha256": "437f654cc48bf6232ff31b621c00172518a9c6d6fb401c73fd418b57c5749bd5",
          "sha1": "2f1260811dfe53d5231198ee9d6fb8823742dc04",
          "md5": "87e5a1a84b773fa9c85f5e075db63898"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.5.0"
          }
        },
        {
          "group": "com.github.piratecash",
          "module": "hd-wallet-kit-android",
          "version": {
            "requires": "46a441d"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bitcoincore-v0.1.0-pcash.25.aar",
          "url": "bitcoincore-v0.1.0-pcash.25.aar",
          "size": 1240801,
          "sha512": "a2901c15c581fffa5736cb9998715c15896b0ca3ff9f08215d69805c9a87de577b6080f3040f46b8e8e97dc9a9a5adbb6c1f2a3e71eca086f9c843786efdebac",
          "sha256": "437f654cc48bf6232ff31b621c00172518a9c6d6fb401c73fd418b57c5749bd5",
          "sha1": "2f1260811dfe53d5231198ee9d6fb8823742dc04",
          "md5": "87e5a1a84b773fa9c85f5e075db63898"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "bitcoincore-v0.1.0-pcash.25-sources.jar",
          "url": "bitcoincore-v0.1.0-pcash.25-sources.jar",
          "size": 1446922,
          "sha512": "26fa8ced6c0f4ed43f97a79a1a8d0ef3e82a8dffa853f6fbc0ae7c2f6a495d3e86c985b43f3d89874f602c1f3b5400d97714768d1c19eff939150d13fd054800",
          "sha256": "e80210f56fa3f05d0cb8c5a6127ff5e8d20de219a61a9b6aab1917860b439294",
          "sha1": "8e78b17f0c7ffc958d6766c91787e980e45fc5bb",
          "md5": "ede6734c63ec327e0dfb942e3cca25e7"
        }
      ]
    }
  ]
}
