{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "piratecashkit",
    "version": "v0.1.0-pcash.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "v0.1.0-pcash.21"
          }
        }
      ],
      "files": [
        {
          "name": "piratecashkit-v0.1.0-pcash.21.aar",
          "url": "piratecashkit-v0.1.0-pcash.21.aar",
          "size": 290870,
          "sha512": "623d2dfb32ebc400b2618fea7b886ca564947a7744b68cb876ff27a959ebf024ba59d2c3eb4d7dde6b3b3970dbc28dc62ca85d0d048d9a2974166abb28235a71",
          "sha256": "0d429eef43af0683b01c463b47ff666a53b3e29624b81a87589ce540b89e2300",
          "sha1": "2ed6ef368bc93bcee5124c703dceca109ee69b32",
          "md5": "1cb9a9e9144e97cc85a3ab362b20a0d3"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "dashlib",
          "version": {
            "requires": "v0.1.0-pcash.21"
          }
        },
        {
          "group": "de.sfuhrm",
          "module": "saphir-hash-jca",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "com.github.all3fox",
          "module": "lyra2",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "v0.1.0-pcash.21"
          }
        }
      ],
      "files": [
        {
          "name": "piratecashkit-v0.1.0-pcash.21.aar",
          "url": "piratecashkit-v0.1.0-pcash.21.aar",
          "size": 290870,
          "sha512": "623d2dfb32ebc400b2618fea7b886ca564947a7744b68cb876ff27a959ebf024ba59d2c3eb4d7dde6b3b3970dbc28dc62ca85d0d048d9a2974166abb28235a71",
          "sha256": "0d429eef43af0683b01c463b47ff666a53b3e29624b81a87589ce540b89e2300",
          "sha1": "2ed6ef368bc93bcee5124c703dceca109ee69b32",
          "md5": "1cb9a9e9144e97cc85a3ab362b20a0d3"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "piratecashkit-v0.1.0-pcash.21-sources.jar",
          "url": "piratecashkit-v0.1.0-pcash.21-sources.jar",
          "size": 291844,
          "sha512": "39892e78da47565d779d502d81524b0397b61ac8e28ebf9dab2c3df1eb9902fcdda5d0ab2a53403225ea78626568b33b86718b04eceea4473158d73ef7972106",
          "sha256": "e94a3609b30bf69991933aa321db07b371ea6eb8d2e3bc42ad7237297972033d",
          "sha1": "8ac4f0860796fc4a94f13bc9beb3724da4f3a3cf",
          "md5": "a25f989ce7e551696e4517e5b9068965"
        }
      ]
    }
  ]
}
