{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "dashkit",
    "version": "3f0c17e",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "3f0c17e"
          }
        }
      ],
      "files": [
        {
          "name": "dashkit-3f0c17e.aar",
          "url": "dashkit-3f0c17e.aar",
          "size": 234044,
          "sha512": "99df3101bc6856c90191a37ae022fd3ec5b4e936058955e98fa53dc8aa8dc2ddd8f40d36f3efce983a9d8165d6ba656772fba7a9726927ebdf833dec59647c08",
          "sha256": "93b5535637aa8b975403a70afdb0b1f3a3c235e982c486447f23812563215f74",
          "sha1": "7c2ae9471777c036e80e0f12b69d6e635ad79b75",
          "md5": "6794bbcad449cb40a65dc8f6d98ccac2"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "dashlib",
          "version": {
            "requires": "3f0c17e"
          }
        },
        {
          "group": "de.sfuhrm",
          "module": "saphir-hash-jca",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "3f0c17e"
          }
        }
      ],
      "files": [
        {
          "name": "dashkit-3f0c17e.aar",
          "url": "dashkit-3f0c17e.aar",
          "size": 234044,
          "sha512": "99df3101bc6856c90191a37ae022fd3ec5b4e936058955e98fa53dc8aa8dc2ddd8f40d36f3efce983a9d8165d6ba656772fba7a9726927ebdf833dec59647c08",
          "sha256": "93b5535637aa8b975403a70afdb0b1f3a3c235e982c486447f23812563215f74",
          "sha1": "7c2ae9471777c036e80e0f12b69d6e635ad79b75",
          "md5": "6794bbcad449cb40a65dc8f6d98ccac2"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "dashkit-3f0c17e-sources.jar",
          "url": "dashkit-3f0c17e-sources.jar",
          "size": 277466,
          "sha512": "72dad0ef85300bdf31a2b927e8f855094f64eb39ae7d9acc41ff4e22f2203f9cf735a1d5d404256a196527d0e11edadb2aadf6928597bf2fd52df421d9a7c0df",
          "sha256": "dd13a59f991f352f4de49e4ccd7228ab20e130c8de957735ed2eaa8bbd40a344",
          "sha1": "ac1c87cd364695fc3b37672bb23fb37810645a8b",
          "md5": "ae62f4ea9e24466a60a73ab282906ad2"
        }
      ]
    }
  ]
}
