{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "bitcoincore",
    "version": "6f6afa5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash",
          "module": "hd-wallet-kit-android",
          "version": {
            "requires": "46a441d"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bitcoincore-6f6afa5.aar",
          "url": "bitcoincore-6f6afa5.aar",
          "size": 1124009,
          "sha512": "bb846c59e5f2dc567a92db898a47ecf5bbc437087b623acd697f1b2574aade683ad3d387fc1e82aa11927536c90664641614c1c7c33befd47be1905e20b73461",
          "sha256": "024c6dc44c06686b3cea518966b2de2a9dbc6fc44941944dc6ea28184d8e878a",
          "sha1": "3fe8db1206acd18681125f4352600959bb310d7d",
          "md5": "76c3dfe482789f7be9f95387cccbaf87"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.5.0"
          }
        },
        {
          "group": "com.github.piratecash",
          "module": "hd-wallet-kit-android",
          "version": {
            "requires": "46a441d"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bitcoincore-6f6afa5.aar",
          "url": "bitcoincore-6f6afa5.aar",
          "size": 1124009,
          "sha512": "bb846c59e5f2dc567a92db898a47ecf5bbc437087b623acd697f1b2574aade683ad3d387fc1e82aa11927536c90664641614c1c7c33befd47be1905e20b73461",
          "sha256": "024c6dc44c06686b3cea518966b2de2a9dbc6fc44941944dc6ea28184d8e878a",
          "sha1": "3fe8db1206acd18681125f4352600959bb310d7d",
          "md5": "76c3dfe482789f7be9f95387cccbaf87"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "bitcoincore-6f6afa5-sources.jar",
          "url": "bitcoincore-6f6afa5-sources.jar",
          "size": 1199493,
          "sha512": "0120efb4341f1b51de166548ce1fdf14db5a1bcaa8bda70f7146a4cb123c590de86647985aafdc923c3575e756bf4f8b925f7521aaf0765ee7e553121a560d9f",
          "sha256": "d68cd7f493b19844cb812a3f680b7a8be5a4b685fdb50e2afe7d7550e58e5d8a",
          "sha1": "fcd08c444af3cd7c5824d3644d87e6fe8f589b06",
          "md5": "d70785443b901052be145c1132d5c554"
        }
      ]
    }
  ]
}
