{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "cosantakit",
    "version": "a49d6b8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "a49d6b8"
          }
        }
      ],
      "files": [
        {
          "name": "cosantakit-a49d6b8.aar",
          "url": "cosantakit-a49d6b8.aar",
          "size": 283269,
          "sha512": "4f000c5e6941fe0b1c082e09e7ab00e55d0d9a4d856beabe26ae0ac1ca9a385ebde2912fdaad80f4e5aab63ca5aafbb93e34a80b73adbf99ea292403476a6b98",
          "sha256": "eb5eb16f06f46c0564a9657949d2f0ee4232ec152ffc9658c38af94ba7580d73",
          "sha1": "142708530994bb377c32c90d551b1265255d3daa",
          "md5": "20df81f5d2fb00c46d3b16d646ec057b"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "dashlib",
          "version": {
            "requires": "a49d6b8"
          }
        },
        {
          "group": "de.sfuhrm",
          "module": "saphir-hash-jca",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "com.github.all3fox",
          "module": "lyra2",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "a49d6b8"
          }
        }
      ],
      "files": [
        {
          "name": "cosantakit-a49d6b8.aar",
          "url": "cosantakit-a49d6b8.aar",
          "size": 283269,
          "sha512": "4f000c5e6941fe0b1c082e09e7ab00e55d0d9a4d856beabe26ae0ac1ca9a385ebde2912fdaad80f4e5aab63ca5aafbb93e34a80b73adbf99ea292403476a6b98",
          "sha256": "eb5eb16f06f46c0564a9657949d2f0ee4232ec152ffc9658c38af94ba7580d73",
          "sha1": "142708530994bb377c32c90d551b1265255d3daa",
          "md5": "20df81f5d2fb00c46d3b16d646ec057b"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "cosantakit-a49d6b8-sources.jar",
          "url": "cosantakit-a49d6b8-sources.jar",
          "size": 288657,
          "sha512": "f1a5f6b767989a2bc0106c11bfe48b1ea07d792599084e59830ff6fd27fe49575c210b8ae590b2806193a88e45fac8f8051468e84bd37ca311c3c51317f55db2",
          "sha256": "92aeee34e6950d7eef470050c36e325b884ec2ceb23237fe6a53a72c83fc30cf",
          "sha1": "6bfadfa0d62bfcbef2bd8a4c520ec9747d6525f2",
          "md5": "9b6569615fcc79dd9fea6f8ac9fcf611"
        }
      ]
    }
  ]
}
