{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "dashkit",
    "version": "8e318e2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "8e318e2"
          }
        }
      ],
      "files": [
        {
          "name": "dashkit-8e318e2.aar",
          "url": "dashkit-8e318e2.aar",
          "size": 234837,
          "sha512": "e94ea8453e76673b827d5a9672b7b8d85c46773f8afc97ccaa805ccea85e12b3c5959d2cc6bb7bbc021739541cbdb68aefe18185ce906d2c74f4599886537ec0",
          "sha256": "010171257ef95e69878461ddd4297960bd5495989eccc43321efb5832b2125a6",
          "sha1": "b4dd684351cc66b762a33da53335c4fd911895f6",
          "md5": "8a4aed5a8c745c2ab84adc1c7064cdb1"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "dashlib",
          "version": {
            "requires": "8e318e2"
          }
        },
        {
          "group": "de.sfuhrm",
          "module": "saphir-hash-jca",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "8e318e2"
          }
        }
      ],
      "files": [
        {
          "name": "dashkit-8e318e2.aar",
          "url": "dashkit-8e318e2.aar",
          "size": 234837,
          "sha512": "e94ea8453e76673b827d5a9672b7b8d85c46773f8afc97ccaa805ccea85e12b3c5959d2cc6bb7bbc021739541cbdb68aefe18185ce906d2c74f4599886537ec0",
          "sha256": "010171257ef95e69878461ddd4297960bd5495989eccc43321efb5832b2125a6",
          "sha1": "b4dd684351cc66b762a33da53335c4fd911895f6",
          "md5": "8a4aed5a8c745c2ab84adc1c7064cdb1"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "dashkit-8e318e2-sources.jar",
          "url": "dashkit-8e318e2-sources.jar",
          "size": 279921,
          "sha512": "b0627a65a98ba7c3041c5543345aecd93ec504aa4cf2f30eb2ec994b8045beddc23983563c0d8f08af9c9c318310db6a0e92e0097ce5c4eff3716933796f69c9",
          "sha256": "d27831e2141534cd313d9ec096c37a059b8aef6fbde2b7d70da0a3a2e5e12c1e",
          "sha1": "063358e5cee0eb567710d4ddff0f10ffa88203ca",
          "md5": "eaa94e2f3bf8033dfa086134a75bb205"
        }
      ]
    }
  ]
}
