{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "bitcoincore",
    "version": "v0.1.0-pcash.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash",
          "module": "hd-wallet-kit-android",
          "version": {
            "requires": "46a441d"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bitcoincore-v0.1.0-pcash.9.aar",
          "url": "bitcoincore-v0.1.0-pcash.9.aar",
          "size": 1130102,
          "sha512": "ff4428d8c887972fb13eab4c5127858ff981b4a7688bdccd7496ba85b2ad98b87b41ff897bc82212a3d775c44aef9093924a4b6480cc54a648a042c09f7226dc",
          "sha256": "e3d02ba63ea8cd518ab719f303af49c6dbab9fa2f2c9fd16c6d857b9491b6173",
          "sha1": "581d77aca7b9e9ae44b08135e3e9733f222b9f0f",
          "md5": "619aa726dbe51b8023f38545cac6434e"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.5.0"
          }
        },
        {
          "group": "com.github.piratecash",
          "module": "hd-wallet-kit-android",
          "version": {
            "requires": "46a441d"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bitcoincore-v0.1.0-pcash.9.aar",
          "url": "bitcoincore-v0.1.0-pcash.9.aar",
          "size": 1130102,
          "sha512": "ff4428d8c887972fb13eab4c5127858ff981b4a7688bdccd7496ba85b2ad98b87b41ff897bc82212a3d775c44aef9093924a4b6480cc54a648a042c09f7226dc",
          "sha256": "e3d02ba63ea8cd518ab719f303af49c6dbab9fa2f2c9fd16c6d857b9491b6173",
          "sha1": "581d77aca7b9e9ae44b08135e3e9733f222b9f0f",
          "md5": "619aa726dbe51b8023f38545cac6434e"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "bitcoincore-v0.1.0-pcash.9-sources.jar",
          "url": "bitcoincore-v0.1.0-pcash.9-sources.jar",
          "size": 1213828,
          "sha512": "91e33cf8ba2233c3306d6dffbd63f82242eb5ec94acffa0d49e11512dae9447eaba3076ad34f16dd040f7ed9b35dd6865a1da68baec917f3bfd873367b097ac7",
          "sha256": "687d52ed13eeac601f8c7b4d0e8fd1d19c27df717c523f4e48ef05a9d02884cc",
          "sha1": "394421a3f10a6ace463dca661714d202fd62806a",
          "md5": "19383e64414ca27e47368a20326f8bc5"
        }
      ]
    }
  ]
}
