{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "litecoinkit",
    "version": "0339c10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "0339c10"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "hodler",
          "version": {
            "requires": "0339c10"
          }
        }
      ],
      "files": [
        {
          "name": "litecoinkit-0339c10.aar",
          "url": "litecoinkit-0339c10.aar",
          "size": 593750,
          "sha512": "347512af7ec8e3784667db874841eff88c1bfc8e0fb313a6b6d46af250b315d843130ba2df94916a966cc026059ff2bfa709393a3da266fdfd43c5c3ff0064ef",
          "sha256": "6e61f48543f3b2b44052ecac42dcddc442406260f3b19e58ce0af2f5428e6f98",
          "sha1": "6271eeca210ccd05a969a5047ac63bf580f568f6",
          "md5": "42e1254f87df0ecf40884f94573acd5b"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.github.piratecash",
          "module": "mwebd-android",
          "version": {
            "requires": "v0.1.19-pcash.9"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "0339c10"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "hodler",
          "version": {
            "requires": "0339c10"
          }
        }
      ],
      "files": [
        {
          "name": "litecoinkit-0339c10.aar",
          "url": "litecoinkit-0339c10.aar",
          "size": 593750,
          "sha512": "347512af7ec8e3784667db874841eff88c1bfc8e0fb313a6b6d46af250b315d843130ba2df94916a966cc026059ff2bfa709393a3da266fdfd43c5c3ff0064ef",
          "sha256": "6e61f48543f3b2b44052ecac42dcddc442406260f3b19e58ce0af2f5428e6f98",
          "sha1": "6271eeca210ccd05a969a5047ac63bf580f568f6",
          "md5": "42e1254f87df0ecf40884f94573acd5b"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "litecoinkit-0339c10-sources.jar",
          "url": "litecoinkit-0339c10-sources.jar",
          "size": 297710,
          "sha512": "3736fcca9a548e5e554db7ee112e04d9a34fddb1a5d973c0adcbdefd668235a8e97eb2a0e17ad953e82b51dfc342d2bd9c476c2241597f71ccbb8be0b8956abd",
          "sha256": "320295b7f0f0f7b42f3f1b6f41a28037b72877677484695634b45fb2f52810d6",
          "sha1": "b28204b60914d40c6309d7ffce08a7f415daafb2",
          "md5": "1d60a5482d86fc8288d5502a22e87227"
        }
      ]
    }
  ]
}
