{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "bitcoincore",
    "version": "1c68398",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash",
          "module": "hd-wallet-kit-android",
          "version": {
            "requires": "8f873a1"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bitcoincore-1c68398.aar",
          "url": "bitcoincore-1c68398.aar",
          "size": 1080571,
          "sha512": "18d3484dc99a0f779aa3b667850c73bff2c0703c215799ddb88715fdc20fb37a42ce81f11d736af77583b8c59753dd87acd4717e04e212c3a7a5105ebcde07bf",
          "sha256": "ed642fffd04a178110861921d508e484c2d4e73a2054a0d121154f94e40d7bf4",
          "sha1": "b86441741ad47d91fbee0bb5b026a68a04215834",
          "md5": "071927968778d64d60e466c08b8a211f"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.5.0"
          }
        },
        {
          "group": "com.github.piratecash",
          "module": "hd-wallet-kit-android",
          "version": {
            "requires": "8f873a1"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bitcoincore-1c68398.aar",
          "url": "bitcoincore-1c68398.aar",
          "size": 1080571,
          "sha512": "18d3484dc99a0f779aa3b667850c73bff2c0703c215799ddb88715fdc20fb37a42ce81f11d736af77583b8c59753dd87acd4717e04e212c3a7a5105ebcde07bf",
          "sha256": "ed642fffd04a178110861921d508e484c2d4e73a2054a0d121154f94e40d7bf4",
          "sha1": "b86441741ad47d91fbee0bb5b026a68a04215834",
          "md5": "071927968778d64d60e466c08b8a211f"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "bitcoincore-1c68398-sources.jar",
          "url": "bitcoincore-1c68398-sources.jar",
          "size": 1169730,
          "sha512": "fa7e4ed9bf973b6379740b27665f18e0f1cf221d4b874f4e32078a21c76da185f2f8c5e4fd7f5169ea8b68a89da78f721f8f355dffdd9e563045c4f471d6b498",
          "sha256": "111f9d6855fc8d19d57bf57acee3ce4836c875a9793d2f6caa1af74351a497c4",
          "sha1": "3ac11431c0dbe78d6e68bd8858bb1a6395826128",
          "md5": "cda47bc97cc18cd7eb83849e2a4a0f85"
        }
      ]
    }
  ]
}
