{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "cosantakit",
    "version": "v0.1.0-pcash.24",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "v0.1.0-pcash.24"
          }
        }
      ],
      "files": [
        {
          "name": "cosantakit-v0.1.0-pcash.24.aar",
          "url": "cosantakit-v0.1.0-pcash.24.aar",
          "size": 286747,
          "sha512": "f9adaae022056bb5bb61358df92c82aa23bacc2480d9412c319921fe146ad6f0c73aeaae2251f7ace7dee000fc256f955080a12fc8b3288e966ed3d2142501b2",
          "sha256": "79ad4ab2b4f281cb66fee1d578edd4f750950ed6479ea0d2fcfd6ccb561cf48e",
          "sha1": "62388a082dc9b0f00437120931fc6a4742b72a0d",
          "md5": "150435246320cc9d072d9e35e8e83746"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "dashlib",
          "version": {
            "requires": "v0.1.0-pcash.24"
          }
        },
        {
          "group": "de.sfuhrm",
          "module": "saphir-hash-jca",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "com.github.all3fox",
          "module": "lyra2",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "v0.1.0-pcash.24"
          }
        }
      ],
      "files": [
        {
          "name": "cosantakit-v0.1.0-pcash.24.aar",
          "url": "cosantakit-v0.1.0-pcash.24.aar",
          "size": 286747,
          "sha512": "f9adaae022056bb5bb61358df92c82aa23bacc2480d9412c319921fe146ad6f0c73aeaae2251f7ace7dee000fc256f955080a12fc8b3288e966ed3d2142501b2",
          "sha256": "79ad4ab2b4f281cb66fee1d578edd4f750950ed6479ea0d2fcfd6ccb561cf48e",
          "sha1": "62388a082dc9b0f00437120931fc6a4742b72a0d",
          "md5": "150435246320cc9d072d9e35e8e83746"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "cosantakit-v0.1.0-pcash.24-sources.jar",
          "url": "cosantakit-v0.1.0-pcash.24-sources.jar",
          "size": 289532,
          "sha512": "71f661dd9ba55b579937a17f0c5e9f7d2c83f702db1acc37cc139e61c4e5f82535024b6d33114865afa6e012610f4eaffc902294faac95d0606893ce7ab6a022",
          "sha256": "8a9f91cd553320ccfb71420a744179dabc14beb7ce967d3b29ab995c100bb825",
          "sha1": "6e9df94f8183a50c2b85eca72c62af9f14c975f6",
          "md5": "3d37e9db77a9b56c2b9bf395ff6ba8e3"
        }
      ]
    }
  ]
}
