{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "bitcoincore",
    "version": "3a320fa",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash",
          "module": "hd-wallet-kit-android",
          "version": {
            "requires": "46a441d"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bitcoincore-3a320fa.aar",
          "url": "bitcoincore-3a320fa.aar",
          "size": 1124009,
          "sha512": "bb846c59e5f2dc567a92db898a47ecf5bbc437087b623acd697f1b2574aade683ad3d387fc1e82aa11927536c90664641614c1c7c33befd47be1905e20b73461",
          "sha256": "024c6dc44c06686b3cea518966b2de2a9dbc6fc44941944dc6ea28184d8e878a",
          "sha1": "3fe8db1206acd18681125f4352600959bb310d7d",
          "md5": "76c3dfe482789f7be9f95387cccbaf87"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.5.0"
          }
        },
        {
          "group": "com.github.piratecash",
          "module": "hd-wallet-kit-android",
          "version": {
            "requires": "46a441d"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bitcoincore-3a320fa.aar",
          "url": "bitcoincore-3a320fa.aar",
          "size": 1124009,
          "sha512": "bb846c59e5f2dc567a92db898a47ecf5bbc437087b623acd697f1b2574aade683ad3d387fc1e82aa11927536c90664641614c1c7c33befd47be1905e20b73461",
          "sha256": "024c6dc44c06686b3cea518966b2de2a9dbc6fc44941944dc6ea28184d8e878a",
          "sha1": "3fe8db1206acd18681125f4352600959bb310d7d",
          "md5": "76c3dfe482789f7be9f95387cccbaf87"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "bitcoincore-3a320fa-sources.jar",
          "url": "bitcoincore-3a320fa-sources.jar",
          "size": 1199493,
          "sha512": "e7de8e4faaaf98265216bdf9382ee8e6297c64c6e5a28bca7861927020c1f66a5b0539c12128ee501ca700c12d444930dbdc1489dda68073dffa95335d0fc435",
          "sha256": "52a5d1d734e6712048c97fe248849c0dc45663e9efaef9daa89fa73d79467944",
          "sha1": "09d26db1cf756998ea733862c036e5946507e0ee",
          "md5": "9d4e6a5e65835e910d6c1396ea1f34ad"
        }
      ]
    }
  ]
}
