{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "litecoinkit",
    "version": "086b341",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "086b341"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "hodler",
          "version": {
            "requires": "086b341"
          }
        }
      ],
      "files": [
        {
          "name": "litecoinkit-086b341.aar",
          "url": "litecoinkit-086b341.aar",
          "size": 386192,
          "sha512": "70a27196af3d928e2458b89e456dca4c02d1f5ac771006e2224f95f982e8eab08b901020ab959878a5fba0691b921c837d1f78c29a409d33012e18de79fee3b5",
          "sha256": "bb959bfd59bc9f8b191f66f95fb406e8403725c278f6379591cd6534d42886ef",
          "sha1": "ae8acc2791d9c5504ccf757d2820e8d570c9119e",
          "md5": "6db96c0f253b6716788ba4d20ed502ff"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.github.piratecash",
          "module": "mwebd-android",
          "version": {
            "requires": "v0.1.19-pcash.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "086b341"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "hodler",
          "version": {
            "requires": "086b341"
          }
        }
      ],
      "files": [
        {
          "name": "litecoinkit-086b341.aar",
          "url": "litecoinkit-086b341.aar",
          "size": 386192,
          "sha512": "70a27196af3d928e2458b89e456dca4c02d1f5ac771006e2224f95f982e8eab08b901020ab959878a5fba0691b921c837d1f78c29a409d33012e18de79fee3b5",
          "sha256": "bb959bfd59bc9f8b191f66f95fb406e8403725c278f6379591cd6534d42886ef",
          "sha1": "ae8acc2791d9c5504ccf757d2820e8d570c9119e",
          "md5": "6db96c0f253b6716788ba4d20ed502ff"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "litecoinkit-086b341-sources.jar",
          "url": "litecoinkit-086b341-sources.jar",
          "size": 249485,
          "sha512": "70b27f23c6c3f849b329cab55149ea5dd8dffd49b73d7a4725cba3d7f319c415bedff7abac4e93a0ad497b4f23e9d2020ec0f14c7b876ece58a2d36aa52d7509",
          "sha256": "abb8ef315fec7706603a5687f6803008b31c0b32a75b2cb188dcca2e7287a190",
          "sha1": "ebfc4e193fa6193b8c9855073aae9fd2254a1366",
          "md5": "7aa8e9b2868cd4d78f5058ddae3d14ed"
        }
      ]
    }
  ]
}
