{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "bitcoincore",
    "version": "5316246",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash",
          "module": "hd-wallet-kit-android",
          "version": {
            "requires": "46a441d"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bitcoincore-5316246.aar",
          "url": "bitcoincore-5316246.aar",
          "size": 1122027,
          "sha512": "292f0a2a31075944827666047167b133c62bd1821a1e477a1aaa21e40278138753c8d45119b399d8f8e6c65a44a449d93416a93b8a78f2559925042dd143bf50",
          "sha256": "0c908001c861a1908792a9dc58fad40c41eaad85950d8a0edc8a00b11c1ca8a7",
          "sha1": "f3a670775c8f64126a4e07b228a70f0b98450341",
          "md5": "d5330815ab6ef32503705b6304a72b56"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.5.0"
          }
        },
        {
          "group": "com.github.piratecash",
          "module": "hd-wallet-kit-android",
          "version": {
            "requires": "46a441d"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bitcoincore-5316246.aar",
          "url": "bitcoincore-5316246.aar",
          "size": 1122027,
          "sha512": "292f0a2a31075944827666047167b133c62bd1821a1e477a1aaa21e40278138753c8d45119b399d8f8e6c65a44a449d93416a93b8a78f2559925042dd143bf50",
          "sha256": "0c908001c861a1908792a9dc58fad40c41eaad85950d8a0edc8a00b11c1ca8a7",
          "sha1": "f3a670775c8f64126a4e07b228a70f0b98450341",
          "md5": "d5330815ab6ef32503705b6304a72b56"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "bitcoincore-5316246-sources.jar",
          "url": "bitcoincore-5316246-sources.jar",
          "size": 1194518,
          "sha512": "bf5626535098f573f8629b2c37fdeb31cd083edab961c5928ca9badba889437e17da8b78859f23f8db75af2faf2e35e698d5a5434b55cfb672ed5809fc1521ec",
          "sha256": "6767273f488a35d688e458026b55982a11fd2014d8dc768220e7d01c08b4fc23",
          "sha1": "a4f4feb2f9aba636b5423302761a26827556b2ce",
          "md5": "3d4bf5ccd8ead72221bbfcd658f2141c"
        }
      ]
    }
  ]
}
