{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "piratecashkit",
    "version": "v0.1.0-pcash.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "v0.1.0-pcash.18"
          }
        }
      ],
      "files": [
        {
          "name": "piratecashkit-v0.1.0-pcash.18.aar",
          "url": "piratecashkit-v0.1.0-pcash.18.aar",
          "size": 290870,
          "sha512": "406d7fd489595b34712fef98270c080032016b7006cad601907898a85090d06c2dc4cd41ab9b4eefacbf8b909ee6e60b25e1655e5b9e360e3a457b2e853812da",
          "sha256": "ebebb9900f966177b3dbcbb89f3ab69d4720a0b4eb236d0791ac1bc265947b50",
          "sha1": "c124b6647f7ebc48041e62febbe90efe4322c6cc",
          "md5": "2c62e376d5c7cdd37eb018d7e715d7eb"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "dashlib",
          "version": {
            "requires": "v0.1.0-pcash.18"
          }
        },
        {
          "group": "de.sfuhrm",
          "module": "saphir-hash-jca",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "com.github.all3fox",
          "module": "lyra2",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "v0.1.0-pcash.18"
          }
        }
      ],
      "files": [
        {
          "name": "piratecashkit-v0.1.0-pcash.18.aar",
          "url": "piratecashkit-v0.1.0-pcash.18.aar",
          "size": 290870,
          "sha512": "406d7fd489595b34712fef98270c080032016b7006cad601907898a85090d06c2dc4cd41ab9b4eefacbf8b909ee6e60b25e1655e5b9e360e3a457b2e853812da",
          "sha256": "ebebb9900f966177b3dbcbb89f3ab69d4720a0b4eb236d0791ac1bc265947b50",
          "sha1": "c124b6647f7ebc48041e62febbe90efe4322c6cc",
          "md5": "2c62e376d5c7cdd37eb018d7e715d7eb"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "piratecashkit-v0.1.0-pcash.18-sources.jar",
          "url": "piratecashkit-v0.1.0-pcash.18-sources.jar",
          "size": 291839,
          "sha512": "cee8c4111113ceee0f590797ccde5e2c98f56e35d84412c863f36d27653c9ba9d3165b054ea6785ab78617b0069a62491c44a8ba0d87fe6f361c827f4ebb8a8e",
          "sha256": "90f6291ea13567e39d7921a980be447983c02ee067156c27161b971163492715",
          "sha1": "fe1c1e9daf4b24aeef50e8047d2e21f1dde8ec67",
          "md5": "d1a75ceea49fcfdc8292228cf20a42b5"
        }
      ]
    }
  ]
}
