{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "litecoinkit",
    "version": "v0.1.0-pcash.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "v0.1.0-pcash.4"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "hodler",
          "version": {
            "requires": "v0.1.0-pcash.4"
          }
        }
      ],
      "files": [
        {
          "name": "litecoinkit-v0.1.0-pcash.4.aar",
          "url": "litecoinkit-v0.1.0-pcash.4.aar",
          "size": 551796,
          "sha512": "fcf28057082ed9527d211825b5a21ea8087d6e84a2f1d22ab603403b6d2a0dfa04e32bd598d01afac6b4adab3eee52f1ef55114d0be728fd2bbc7c8dd30daeb4",
          "sha256": "b04447cc2ecd2fa69eac88e03f6d36692e123c3ab8712079715ae3b50ed60c2b",
          "sha1": "43138a9391e33903b11acf8ce3813558f3354b5d",
          "md5": "5b3682958bf7d79aed1fcaab3238949e"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.github.piratecash",
          "module": "mwebd-android",
          "version": {
            "requires": "v0.1.19-pcash.8"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "v0.1.0-pcash.4"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "hodler",
          "version": {
            "requires": "v0.1.0-pcash.4"
          }
        }
      ],
      "files": [
        {
          "name": "litecoinkit-v0.1.0-pcash.4.aar",
          "url": "litecoinkit-v0.1.0-pcash.4.aar",
          "size": 551796,
          "sha512": "fcf28057082ed9527d211825b5a21ea8087d6e84a2f1d22ab603403b6d2a0dfa04e32bd598d01afac6b4adab3eee52f1ef55114d0be728fd2bbc7c8dd30daeb4",
          "sha256": "b04447cc2ecd2fa69eac88e03f6d36692e123c3ab8712079715ae3b50ed60c2b",
          "sha1": "43138a9391e33903b11acf8ce3813558f3354b5d",
          "md5": "5b3682958bf7d79aed1fcaab3238949e"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "litecoinkit-v0.1.0-pcash.4-sources.jar",
          "url": "litecoinkit-v0.1.0-pcash.4-sources.jar",
          "size": 282340,
          "sha512": "76745a38e4a67eb81a891570c564d03bb037862f51a10e87ef48bdf853fd1b4596ae41c16d558c9ad4218b53330d78d29f1864e1aa9f148a261f1f23be2451b1",
          "sha256": "3247ff0690fe76d7186539ccf57ffcdfb5ef754b619d04bf95aed01b5dc6a31f",
          "sha1": "4e962f174704bb241bfed4bb7cf345f8ce7e309b",
          "md5": "b9fd2b0c1d663dc3f17fed09fdad9edb"
        }
      ]
    }
  ]
}
