{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "piratecashkit",
    "version": "200ae7d",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "200ae7d"
          }
        }
      ],
      "files": [
        {
          "name": "piratecashkit-200ae7d.aar",
          "url": "piratecashkit-200ae7d.aar",
          "size": 290870,
          "sha512": "623d2dfb32ebc400b2618fea7b886ca564947a7744b68cb876ff27a959ebf024ba59d2c3eb4d7dde6b3b3970dbc28dc62ca85d0d048d9a2974166abb28235a71",
          "sha256": "0d429eef43af0683b01c463b47ff666a53b3e29624b81a87589ce540b89e2300",
          "sha1": "2ed6ef368bc93bcee5124c703dceca109ee69b32",
          "md5": "1cb9a9e9144e97cc85a3ab362b20a0d3"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "dashlib",
          "version": {
            "requires": "200ae7d"
          }
        },
        {
          "group": "de.sfuhrm",
          "module": "saphir-hash-jca",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "com.github.all3fox",
          "module": "lyra2",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "200ae7d"
          }
        }
      ],
      "files": [
        {
          "name": "piratecashkit-200ae7d.aar",
          "url": "piratecashkit-200ae7d.aar",
          "size": 290870,
          "sha512": "623d2dfb32ebc400b2618fea7b886ca564947a7744b68cb876ff27a959ebf024ba59d2c3eb4d7dde6b3b3970dbc28dc62ca85d0d048d9a2974166abb28235a71",
          "sha256": "0d429eef43af0683b01c463b47ff666a53b3e29624b81a87589ce540b89e2300",
          "sha1": "2ed6ef368bc93bcee5124c703dceca109ee69b32",
          "md5": "1cb9a9e9144e97cc85a3ab362b20a0d3"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "piratecashkit-200ae7d-sources.jar",
          "url": "piratecashkit-200ae7d-sources.jar",
          "size": 291844,
          "sha512": "6508f8392f6e4cf0797b2cb355ca924ad85d1ef1781290e68b11c4a9d5c67877fb8c81296daaa1be8d9b48c5fb5845c1da39ac953e8fb1634614435d507b00d1",
          "sha256": "13c4856da6ca3cb7cd86b00ba437e62d71823f0c52470abbd3e7d62a0fc3fd5b",
          "sha1": "362f7e5e653d7f4c9ecfb7439b0e19ca39fe1c81",
          "md5": "aecd0f0f5c0699cd2512962feef6c7b8"
        }
      ]
    }
  ]
}
