{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "bitcoincore",
    "version": "v0.1.0-pcash.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash",
          "module": "hd-wallet-kit-android",
          "version": {
            "requires": "46a441d"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bitcoincore-v0.1.0-pcash.21.aar",
          "url": "bitcoincore-v0.1.0-pcash.21.aar",
          "size": 1165228,
          "sha512": "20317e8dfe6888e879b46a84cd98d924982cbe5ab90dcaa83f914e391467de072b01ceb5f08152a68de39f181937e0d4fd47a0ffd93805ac577ec676d751e612",
          "sha256": "ab1532126b0973dad42e7f9ff6cbe531df54dca4b926ef3c97cf20fbad6a6900",
          "sha1": "6879d1b213628bbf09e947a86ef6bf3ea1009aa6",
          "md5": "f8eb4541202a25d2b3e26756b15c51d0"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.5.0"
          }
        },
        {
          "group": "com.github.piratecash",
          "module": "hd-wallet-kit-android",
          "version": {
            "requires": "46a441d"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bitcoincore-v0.1.0-pcash.21.aar",
          "url": "bitcoincore-v0.1.0-pcash.21.aar",
          "size": 1165228,
          "sha512": "20317e8dfe6888e879b46a84cd98d924982cbe5ab90dcaa83f914e391467de072b01ceb5f08152a68de39f181937e0d4fd47a0ffd93805ac577ec676d751e612",
          "sha256": "ab1532126b0973dad42e7f9ff6cbe531df54dca4b926ef3c97cf20fbad6a6900",
          "sha1": "6879d1b213628bbf09e947a86ef6bf3ea1009aa6",
          "md5": "f8eb4541202a25d2b3e26756b15c51d0"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "bitcoincore-v0.1.0-pcash.21-sources.jar",
          "url": "bitcoincore-v0.1.0-pcash.21-sources.jar",
          "size": 1268996,
          "sha512": "2f58cf21f948b306af5ccbf1036c80e412553ba8ba4619cd5ec52aa17c53590d1650443dfafeb90766248bbcb4fe609a1c73037b1188091f683b7639c365c73a",
          "sha256": "c0d53cd628c211f3f053f4b7860409a5eb3d568c82ca2c3441c60f0edeebaa56",
          "sha1": "77431f172581142529bfae33a11526eb081f4dfd",
          "md5": "1c15442a1b510b2c3e844665c1e03b79"
        }
      ]
    }
  ]
}
