{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "litecoinkit",
    "version": "a49d6b8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "a49d6b8"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "hodler",
          "version": {
            "requires": "a49d6b8"
          }
        }
      ],
      "files": [
        {
          "name": "litecoinkit-a49d6b8.aar",
          "url": "litecoinkit-a49d6b8.aar",
          "size": 595927,
          "sha512": "6f36adf6b266becab2eb39deddb1fa5bbfe803a6f0ab0557ab5a4125e05e9fb5e25a6be59a4cfc4492f0d625be48cc9f55f2150e74bfba94bcc1b412c3c986d9",
          "sha256": "79f2d2c637bbdf7cd514eac42fc35b3e3c33f6b9ddca03e55576896a63445241",
          "sha1": "b0dfe5f159c7cb2557cced25a0055dea3bfc0cf4",
          "md5": "f8aaf91c69202763c6bcc59360d5d975"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.github.piratecash",
          "module": "mwebd-android",
          "version": {
            "requires": "v0.1.19-pcash.9"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "a49d6b8"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "hodler",
          "version": {
            "requires": "a49d6b8"
          }
        }
      ],
      "files": [
        {
          "name": "litecoinkit-a49d6b8.aar",
          "url": "litecoinkit-a49d6b8.aar",
          "size": 595927,
          "sha512": "6f36adf6b266becab2eb39deddb1fa5bbfe803a6f0ab0557ab5a4125e05e9fb5e25a6be59a4cfc4492f0d625be48cc9f55f2150e74bfba94bcc1b412c3c986d9",
          "sha256": "79f2d2c637bbdf7cd514eac42fc35b3e3c33f6b9ddca03e55576896a63445241",
          "sha1": "b0dfe5f159c7cb2557cced25a0055dea3bfc0cf4",
          "md5": "f8aaf91c69202763c6bcc59360d5d975"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "litecoinkit-a49d6b8-sources.jar",
          "url": "litecoinkit-a49d6b8-sources.jar",
          "size": 301155,
          "sha512": "40ed16c304108662eb94a15250dbc67e965bbd6f78f53a45137bd3e6341621f5ef9efdca8f0e53d643608d095517970614319f2642112a5fea3769de4880deea",
          "sha256": "8fa0a951a7bbf946300e44e36435c54c024db9abdb7d6ad0a55faf79304af9eb",
          "sha1": "ef522c3fff84f7abfcb5f429ca87c13bec369515",
          "md5": "f0b04efd45e2ac0a5bebbca605dc8fdc"
        }
      ]
    }
  ]
}
