{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "cosantakit",
    "version": "e0a27c4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "e0a27c4"
          }
        }
      ],
      "files": [
        {
          "name": "cosantakit-e0a27c4.aar",
          "url": "cosantakit-e0a27c4.aar",
          "size": 286096,
          "sha512": "18b64dc8a7c06d02559d4e1215fb4864c0dea5f34b06acd21ff00c967e0a409e3f94c3fcc8d8190170a0865907376909b5d76c690aaa7ed56bc6b4d7ab13416a",
          "sha256": "4f401890dca7e548bb555657d35eecd16d48c3f395d2356a54a8b59f1128aa05",
          "sha1": "f16ce50665f414f7e08bc932acca23ff8e30abb6",
          "md5": "e46bf82d1236aecabbf89a67b9037004"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "dashlib",
          "version": {
            "requires": "e0a27c4"
          }
        },
        {
          "group": "de.sfuhrm",
          "module": "saphir-hash-jca",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "com.github.all3fox",
          "module": "lyra2",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "e0a27c4"
          }
        }
      ],
      "files": [
        {
          "name": "cosantakit-e0a27c4.aar",
          "url": "cosantakit-e0a27c4.aar",
          "size": 286096,
          "sha512": "18b64dc8a7c06d02559d4e1215fb4864c0dea5f34b06acd21ff00c967e0a409e3f94c3fcc8d8190170a0865907376909b5d76c690aaa7ed56bc6b4d7ab13416a",
          "sha256": "4f401890dca7e548bb555657d35eecd16d48c3f395d2356a54a8b59f1128aa05",
          "sha1": "f16ce50665f414f7e08bc932acca23ff8e30abb6",
          "md5": "e46bf82d1236aecabbf89a67b9037004"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "cosantakit-e0a27c4-sources.jar",
          "url": "cosantakit-e0a27c4-sources.jar",
          "size": 284582,
          "sha512": "369a094290853484ba666272d28f29c46b4ebe11a863350fcc568c2b00f4a04bd3e7987ad34c50366fd83bfe43549e03a7d6285e5cf71b18ec408cb7ad4fe6ff",
          "sha256": "cfa0f519af285b32842c485f66f3f751a7d8c7ad3202a90da9a7c5474da74caf",
          "sha1": "6057c9f95cd6ddd690a35fa1b14b7517a23158e1",
          "md5": "bdaf5d22077da2278d3d5b0b417d536b"
        }
      ]
    }
  ]
}
