{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "litecoinkit",
    "version": "200ae7d",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "200ae7d"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "hodler",
          "version": {
            "requires": "200ae7d"
          }
        }
      ],
      "files": [
        {
          "name": "litecoinkit-200ae7d.aar",
          "url": "litecoinkit-200ae7d.aar",
          "size": 595668,
          "sha512": "20982d00ec0ec57199ff096acbce7afcb0516973649248da5c48751617f4582261af53b77b517836dc57a41670eb60ad0ba47c9b8bfdd9eef9bd7b56d0e8e745",
          "sha256": "fdc87ca582f1dd8d5a24383066245fbe6e9446e83af399ae0669a4d26644b284",
          "sha1": "c9cf7edaaf3f7c0d733dc76fb0d51dcc1054cbfc",
          "md5": "9b81654fdbb9a862471ad89983630125"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.github.piratecash",
          "module": "mwebd-android",
          "version": {
            "requires": "v0.1.19-pcash.9"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "200ae7d"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "hodler",
          "version": {
            "requires": "200ae7d"
          }
        }
      ],
      "files": [
        {
          "name": "litecoinkit-200ae7d.aar",
          "url": "litecoinkit-200ae7d.aar",
          "size": 595668,
          "sha512": "20982d00ec0ec57199ff096acbce7afcb0516973649248da5c48751617f4582261af53b77b517836dc57a41670eb60ad0ba47c9b8bfdd9eef9bd7b56d0e8e745",
          "sha256": "fdc87ca582f1dd8d5a24383066245fbe6e9446e83af399ae0669a4d26644b284",
          "sha1": "c9cf7edaaf3f7c0d733dc76fb0d51dcc1054cbfc",
          "md5": "9b81654fdbb9a862471ad89983630125"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "litecoinkit-200ae7d-sources.jar",
          "url": "litecoinkit-200ae7d-sources.jar",
          "size": 300480,
          "sha512": "7603917764182074a71db70471ca679a414dd84e43d9dbcba66e866a2a626066b6a5d7203dd991685456cd01e8773dc120dfa3da817b4f9e74d40cac706aa5e2",
          "sha256": "af6d54ab48fae9c56cb7302fab93e8675b6660f46ed6abed8afabd80673c9f61",
          "sha1": "0f498219d5afdf8258ea142eabfe4ce5527bb085",
          "md5": "49cdd8d1dfeba28d8e85ff2646d2d88e"
        }
      ]
    }
  ]
}
