{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "bitcoincore",
    "version": "efe2e53",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash",
          "module": "hd-wallet-kit-android",
          "version": {
            "requires": "46a441d"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bitcoincore-efe2e53.aar",
          "url": "bitcoincore-efe2e53.aar",
          "size": 1125669,
          "sha512": "9d884bbf286d8dd29d9659ff8f581853324580aefb2dbbedb31c32f6517881d6cf1b81057e716e125d40d78033d1adf67695ce1c8e22391a2fdad1d4b67f9068",
          "sha256": "ee5d825d86b4f2ecdb00a8915d2a1efce2bffe72433003bb8c48d78e2a868b43",
          "sha1": "8a0893b5f957859f1310185d02d20f7a00394826",
          "md5": "d26c6d842f58cac0f476f64037a44656"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.5.0"
          }
        },
        {
          "group": "com.github.piratecash",
          "module": "hd-wallet-kit-android",
          "version": {
            "requires": "46a441d"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bitcoincore-efe2e53.aar",
          "url": "bitcoincore-efe2e53.aar",
          "size": 1125669,
          "sha512": "9d884bbf286d8dd29d9659ff8f581853324580aefb2dbbedb31c32f6517881d6cf1b81057e716e125d40d78033d1adf67695ce1c8e22391a2fdad1d4b67f9068",
          "sha256": "ee5d825d86b4f2ecdb00a8915d2a1efce2bffe72433003bb8c48d78e2a868b43",
          "sha1": "8a0893b5f957859f1310185d02d20f7a00394826",
          "md5": "d26c6d842f58cac0f476f64037a44656"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "bitcoincore-efe2e53-sources.jar",
          "url": "bitcoincore-efe2e53-sources.jar",
          "size": 1197498,
          "sha512": "446e9996002ebf1e22444e441a81a010701fe28250fbdb519a2dcaa2788ea34f450054389e99c7d53ef8dd470b3eff5379b2202c57535080186c20246422c8fa",
          "sha256": "4e7656ddace06b1d83a819c5d71d4292459c22efcf650671138c2621684a675b",
          "sha1": "0ca42765915a40a38c5a1b806b5e31c389482e18",
          "md5": "474b3949e63bc8ebe0a1ff91de73e3d3"
        }
      ]
    }
  ]
}
