{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "bitcoincore",
    "version": "086b341",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash",
          "module": "hd-wallet-kit-android",
          "version": {
            "requires": "46a441d"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bitcoincore-086b341.aar",
          "url": "bitcoincore-086b341.aar",
          "size": 1125669,
          "sha512": "9d884bbf286d8dd29d9659ff8f581853324580aefb2dbbedb31c32f6517881d6cf1b81057e716e125d40d78033d1adf67695ce1c8e22391a2fdad1d4b67f9068",
          "sha256": "ee5d825d86b4f2ecdb00a8915d2a1efce2bffe72433003bb8c48d78e2a868b43",
          "sha1": "8a0893b5f957859f1310185d02d20f7a00394826",
          "md5": "d26c6d842f58cac0f476f64037a44656"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.5.0"
          }
        },
        {
          "group": "com.github.piratecash",
          "module": "hd-wallet-kit-android",
          "version": {
            "requires": "46a441d"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bitcoincore-086b341.aar",
          "url": "bitcoincore-086b341.aar",
          "size": 1125669,
          "sha512": "9d884bbf286d8dd29d9659ff8f581853324580aefb2dbbedb31c32f6517881d6cf1b81057e716e125d40d78033d1adf67695ce1c8e22391a2fdad1d4b67f9068",
          "sha256": "ee5d825d86b4f2ecdb00a8915d2a1efce2bffe72433003bb8c48d78e2a868b43",
          "sha1": "8a0893b5f957859f1310185d02d20f7a00394826",
          "md5": "d26c6d842f58cac0f476f64037a44656"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "bitcoincore-086b341-sources.jar",
          "url": "bitcoincore-086b341-sources.jar",
          "size": 1197498,
          "sha512": "6da0cb35150e97c49103de6196f88e5b82b1a86f8f38bbfb713317aa1b20c5caf0e090bc6a1ec4f20860cb59a82179a98c38429a5804e91edfe184b069bba7f5",
          "sha256": "68fdbe9377ef58ef7a068b4847bb298bc7deec05ba1f13c9430235c089294729",
          "sha1": "c497d4c4d08fd93bda2bc5156e3cfd04c9c1fbe8",
          "md5": "59746c05480de027efe1e671f1c7c981"
        }
      ]
    }
  ]
}
