{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "litecoinkit",
    "version": "1e29656",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "1e29656"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "hodler",
          "version": {
            "requires": "1e29656"
          }
        }
      ],
      "files": [
        {
          "name": "litecoinkit-1e29656.aar",
          "url": "litecoinkit-1e29656.aar",
          "size": 554930,
          "sha512": "5351f22338aa40974392364199cfa41f20cc9dafd63383d40c56a4e96a45d83f9e3ad0ba824a559109c2765b3b5f0244b6659c80676861e83d5eeb5caffe45de",
          "sha256": "436e719e876a1f6beadd13289b48bcf50fcf9eeada5e7bc89c387fbb565cda02",
          "sha1": "ad8e384481e4b65bc6d1a1519db3505716795819",
          "md5": "186faf7bbaefbf62be75dfd2565f4304"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.github.piratecash",
          "module": "mwebd-android",
          "version": {
            "requires": "v0.1.19-pcash.8"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "1e29656"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "hodler",
          "version": {
            "requires": "1e29656"
          }
        }
      ],
      "files": [
        {
          "name": "litecoinkit-1e29656.aar",
          "url": "litecoinkit-1e29656.aar",
          "size": 554930,
          "sha512": "5351f22338aa40974392364199cfa41f20cc9dafd63383d40c56a4e96a45d83f9e3ad0ba824a559109c2765b3b5f0244b6659c80676861e83d5eeb5caffe45de",
          "sha256": "436e719e876a1f6beadd13289b48bcf50fcf9eeada5e7bc89c387fbb565cda02",
          "sha1": "ad8e384481e4b65bc6d1a1519db3505716795819",
          "md5": "186faf7bbaefbf62be75dfd2565f4304"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "litecoinkit-1e29656-sources.jar",
          "url": "litecoinkit-1e29656-sources.jar",
          "size": 284110,
          "sha512": "b10663f42ccd34026f57fe528b38406d11a21d9d27fedbe5e3c48aa3766ce2da8391e4bc45c1f808c68af67d2652b57d1073272e99790887009fbf5e53a95d44",
          "sha256": "59e87ca7cbf4733e125d5da2a634279473e15788949b9e69e2cc0cabf2d33598",
          "sha1": "af50de1f40a3149c26b739988da55bca92cc0985",
          "md5": "9251802622169cf7b23fffab1f53a2dd"
        }
      ]
    }
  ]
}
