{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "dashkit",
    "version": "3cf21db",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "3cf21db"
          }
        }
      ],
      "files": [
        {
          "name": "dashkit-3cf21db.aar",
          "url": "dashkit-3cf21db.aar",
          "size": 234315,
          "sha512": "3cd5b710a1e4f1731f7dc481acd31df68df1bc5219644954020870d5cf53461984abd4ea0f6c0513607bdb36d20d43f578d21c802aaddbd0af377dd3302a80c4",
          "sha256": "a6447b0b8d0e5cd0af0715ca430f0fd95ff5f1f62315f5774653d0ecd087d9b2",
          "sha1": "51d703a01b85d2fd8495174e5e941b79a631f855",
          "md5": "5edb964d285ca8a20ea88099bd791028"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "dashlib",
          "version": {
            "requires": "3cf21db"
          }
        },
        {
          "group": "de.sfuhrm",
          "module": "saphir-hash-jca",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "3cf21db"
          }
        }
      ],
      "files": [
        {
          "name": "dashkit-3cf21db.aar",
          "url": "dashkit-3cf21db.aar",
          "size": 234315,
          "sha512": "3cd5b710a1e4f1731f7dc481acd31df68df1bc5219644954020870d5cf53461984abd4ea0f6c0513607bdb36d20d43f578d21c802aaddbd0af377dd3302a80c4",
          "sha256": "a6447b0b8d0e5cd0af0715ca430f0fd95ff5f1f62315f5774653d0ecd087d9b2",
          "sha1": "51d703a01b85d2fd8495174e5e941b79a631f855",
          "md5": "5edb964d285ca8a20ea88099bd791028"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "dashkit-3cf21db-sources.jar",
          "url": "dashkit-3cf21db-sources.jar",
          "size": 278306,
          "sha512": "4a2d70641610674ec7f3365b628b9585d0028aa7007ce353a5a6ca2b7f5f3f8076de8b72b56fe61ef06dc5cc436ffcc93b27c16460a795651c984d66ee42ac88",
          "sha256": "49156fcdd5cf04f427d4eee9e6836622b59c6c239a8e62f8789220051d9327d3",
          "sha1": "5bfcd6d3cfe14ac616fce699bae7d7e1e6b9f8af",
          "md5": "4281bd4f87fee9a88246345ba579a829"
        }
      ]
    }
  ]
}
