{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "litecoinkit",
    "version": "9a2d6a7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "9a2d6a7"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "hodler",
          "version": {
            "requires": "9a2d6a7"
          }
        }
      ],
      "files": [
        {
          "name": "litecoinkit-9a2d6a7.aar",
          "url": "litecoinkit-9a2d6a7.aar",
          "size": 523470,
          "sha512": "affea419e1ae771225fabb327c1a030bb1389cd3ba8df1ecac4e0e31f2b3f2cebb5010c72487a07f074ea49317f98a4c8b9b4468387bfdc6190d8c336a32d277",
          "sha256": "45ce52bb546964846f90f1b8ab3590120eced30b4c016c3c74e2189deb35b8bc",
          "sha1": "ac3d246a932145177ef6969190e7d7f52fccd71e",
          "md5": "9ac906130412072afaf918b260adf4df"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.github.piratecash",
          "module": "mwebd-android",
          "version": {
            "requires": "v0.1.19-pcash.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "9a2d6a7"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "hodler",
          "version": {
            "requires": "9a2d6a7"
          }
        }
      ],
      "files": [
        {
          "name": "litecoinkit-9a2d6a7.aar",
          "url": "litecoinkit-9a2d6a7.aar",
          "size": 523470,
          "sha512": "affea419e1ae771225fabb327c1a030bb1389cd3ba8df1ecac4e0e31f2b3f2cebb5010c72487a07f074ea49317f98a4c8b9b4468387bfdc6190d8c336a32d277",
          "sha256": "45ce52bb546964846f90f1b8ab3590120eced30b4c016c3c74e2189deb35b8bc",
          "sha1": "ac3d246a932145177ef6969190e7d7f52fccd71e",
          "md5": "9ac906130412072afaf918b260adf4df"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "litecoinkit-9a2d6a7-sources.jar",
          "url": "litecoinkit-9a2d6a7-sources.jar",
          "size": 262240,
          "sha512": "e73c170708d80f9176562ae2799111adfd4fcda922bea1fd0e0fb8128c1b1407680f617e2748a2c219a70c358d9c37528832e2c1904fd9d643a6b9cd5493f529",
          "sha256": "70719429010616c3581276a792c9b7a7855502be745772748289ece42b3f0671",
          "sha1": "77ad8554ac236fc32577e11b21e8e79e6fdc042e",
          "md5": "6dc80a079000dd285a500896804f4c5f"
        }
      ]
    }
  ]
}
