{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "litecoinkit",
    "version": "v0.1.0-pcash.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "v0.1.0-pcash.3"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "hodler",
          "version": {
            "requires": "v0.1.0-pcash.3"
          }
        }
      ],
      "files": [
        {
          "name": "litecoinkit-v0.1.0-pcash.3.aar",
          "url": "litecoinkit-v0.1.0-pcash.3.aar",
          "size": 551796,
          "sha512": "fcf28057082ed9527d211825b5a21ea8087d6e84a2f1d22ab603403b6d2a0dfa04e32bd598d01afac6b4adab3eee52f1ef55114d0be728fd2bbc7c8dd30daeb4",
          "sha256": "b04447cc2ecd2fa69eac88e03f6d36692e123c3ab8712079715ae3b50ed60c2b",
          "sha1": "43138a9391e33903b11acf8ce3813558f3354b5d",
          "md5": "5b3682958bf7d79aed1fcaab3238949e"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.github.piratecash",
          "module": "mwebd-android",
          "version": {
            "requires": "v0.1.19-pcash.8"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "v0.1.0-pcash.3"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "hodler",
          "version": {
            "requires": "v0.1.0-pcash.3"
          }
        }
      ],
      "files": [
        {
          "name": "litecoinkit-v0.1.0-pcash.3.aar",
          "url": "litecoinkit-v0.1.0-pcash.3.aar",
          "size": 551796,
          "sha512": "fcf28057082ed9527d211825b5a21ea8087d6e84a2f1d22ab603403b6d2a0dfa04e32bd598d01afac6b4adab3eee52f1ef55114d0be728fd2bbc7c8dd30daeb4",
          "sha256": "b04447cc2ecd2fa69eac88e03f6d36692e123c3ab8712079715ae3b50ed60c2b",
          "sha1": "43138a9391e33903b11acf8ce3813558f3354b5d",
          "md5": "5b3682958bf7d79aed1fcaab3238949e"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "litecoinkit-v0.1.0-pcash.3-sources.jar",
          "url": "litecoinkit-v0.1.0-pcash.3-sources.jar",
          "size": 282340,
          "sha512": "3d84606d86225602399f7880c1ef5967ae49630abed008a3e1f0af7770f1c5aff0756cfdeee3b11ac3adc32bcfc5ee51a94905a7100b8b71ecc5182ebca14fbf",
          "sha256": "9a7c7dd150c1a0c78a5c96ccabb0e9ec98e682545cab791080b798b3d6e78e56",
          "sha1": "2d5b10112b122304992508dbbfa614b04ff556a2",
          "md5": "3eda39bfa207b95497cc4d79e87e6d41"
        }
      ]
    }
  ]
}
