{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "piratecashkit",
    "version": "v0.1.0-pcash.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "v0.1.0-pcash.25"
          }
        }
      ],
      "files": [
        {
          "name": "piratecashkit-v0.1.0-pcash.25.aar",
          "url": "piratecashkit-v0.1.0-pcash.25.aar",
          "size": 291563,
          "sha512": "acf6cd66c23feb839bff6eac53ea8b51eb780f92cc2a657b9f062b4f1e6ef56b60e7db9d2f754819a0b104070f1612cee4b148e3697d231822d3be382ee9be1e",
          "sha256": "a8d072793a0d561d2365abe37ac49d3f13a3e1f649b81d89bbf9d3bcf4ff6c87",
          "sha1": "daa6087e8a0dabbddcb7a17f8acdc043f7a00556",
          "md5": "81b201168bba1ff656971adf0212eceb"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "dashlib",
          "version": {
            "requires": "v0.1.0-pcash.25"
          }
        },
        {
          "group": "de.sfuhrm",
          "module": "saphir-hash-jca",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "com.github.all3fox",
          "module": "lyra2",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "v0.1.0-pcash.25"
          }
        }
      ],
      "files": [
        {
          "name": "piratecashkit-v0.1.0-pcash.25.aar",
          "url": "piratecashkit-v0.1.0-pcash.25.aar",
          "size": 291563,
          "sha512": "acf6cd66c23feb839bff6eac53ea8b51eb780f92cc2a657b9f062b4f1e6ef56b60e7db9d2f754819a0b104070f1612cee4b148e3697d231822d3be382ee9be1e",
          "sha256": "a8d072793a0d561d2365abe37ac49d3f13a3e1f649b81d89bbf9d3bcf4ff6c87",
          "sha1": "daa6087e8a0dabbddcb7a17f8acdc043f7a00556",
          "md5": "81b201168bba1ff656971adf0212eceb"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "piratecashkit-v0.1.0-pcash.25-sources.jar",
          "url": "piratecashkit-v0.1.0-pcash.25-sources.jar",
          "size": 293629,
          "sha512": "2df1a97b7a3368a5e50d6271700e98cdefe069d6655bee700c70e2f48d36a53bcd2461fbb89d7dd51d5d52655544ecc81df509ce2327b407ae9feb908a351d3c",
          "sha256": "f216b7483677bd19a77b324cff0b5d31a63a2405af4a82daee2eeba2a37d0fac",
          "sha1": "aa3356c9f2a0a2eec5ecbb2e3c279026a574385a",
          "md5": "a9ef2b3e64ccb238118195c02a17b51b"
        }
      ]
    }
  ]
}
