{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "bitcoincore",
    "version": "fadfbf9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash",
          "module": "hd-wallet-kit-android",
          "version": {
            "requires": "8f873a1"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bitcoincore-fadfbf9.aar",
          "url": "bitcoincore-fadfbf9.aar",
          "size": 1080571,
          "sha512": "18d3484dc99a0f779aa3b667850c73bff2c0703c215799ddb88715fdc20fb37a42ce81f11d736af77583b8c59753dd87acd4717e04e212c3a7a5105ebcde07bf",
          "sha256": "ed642fffd04a178110861921d508e484c2d4e73a2054a0d121154f94e40d7bf4",
          "sha1": "b86441741ad47d91fbee0bb5b026a68a04215834",
          "md5": "071927968778d64d60e466c08b8a211f"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.5.0"
          }
        },
        {
          "group": "com.github.piratecash",
          "module": "hd-wallet-kit-android",
          "version": {
            "requires": "8f873a1"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bitcoincore-fadfbf9.aar",
          "url": "bitcoincore-fadfbf9.aar",
          "size": 1080571,
          "sha512": "18d3484dc99a0f779aa3b667850c73bff2c0703c215799ddb88715fdc20fb37a42ce81f11d736af77583b8c59753dd87acd4717e04e212c3a7a5105ebcde07bf",
          "sha256": "ed642fffd04a178110861921d508e484c2d4e73a2054a0d121154f94e40d7bf4",
          "sha1": "b86441741ad47d91fbee0bb5b026a68a04215834",
          "md5": "071927968778d64d60e466c08b8a211f"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "bitcoincore-fadfbf9-sources.jar",
          "url": "bitcoincore-fadfbf9-sources.jar",
          "size": 1169730,
          "sha512": "2418ad817cc39212abd8a139fb5b2b8883e16e9d2afbe9ec8577d1a049061994ae05c0fa74c31721c537e8b277a7a9d988e914285a41d67915acb5440d52ed09",
          "sha256": "68f7073529277e140b6d98540e8f8bd46296a1e27b2549e7f2b8cbd1adbf2899",
          "sha1": "4b471b92f0944750f53eb40588b91ddef3e21281",
          "md5": "654f3fef33eccbe61169286d9e74f00f"
        }
      ]
    }
  ]
}
