{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "piratecashkit",
    "version": "bbf7636",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "bbf7636"
          }
        }
      ],
      "files": [
        {
          "name": "piratecashkit-bbf7636.aar",
          "url": "piratecashkit-bbf7636.aar",
          "size": 291133,
          "sha512": "8435b12c893c522c24954def6bfe81c39a1d652f1d22b75dff1dec0b8beb9a9bdf945f25650080ff4f6f75f387b1b537719c19146520ddccd48867675c148e48",
          "sha256": "4e9536848313eca8adab296a5cc440752cf6188d993a562b01d4b6fac23d13a9",
          "sha1": "ce834ab953da647f4d17948fe7258a6709384ff8",
          "md5": "2d39453293c3698adcef25fce49d07aa"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "dashlib",
          "version": {
            "requires": "bbf7636"
          }
        },
        {
          "group": "de.sfuhrm",
          "module": "saphir-hash-jca",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "com.github.all3fox",
          "module": "lyra2",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "bbf7636"
          }
        }
      ],
      "files": [
        {
          "name": "piratecashkit-bbf7636.aar",
          "url": "piratecashkit-bbf7636.aar",
          "size": 291133,
          "sha512": "8435b12c893c522c24954def6bfe81c39a1d652f1d22b75dff1dec0b8beb9a9bdf945f25650080ff4f6f75f387b1b537719c19146520ddccd48867675c148e48",
          "sha256": "4e9536848313eca8adab296a5cc440752cf6188d993a562b01d4b6fac23d13a9",
          "sha1": "ce834ab953da647f4d17948fe7258a6709384ff8",
          "md5": "2d39453293c3698adcef25fce49d07aa"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "piratecashkit-bbf7636-sources.jar",
          "url": "piratecashkit-bbf7636-sources.jar",
          "size": 292144,
          "sha512": "307746e1e601f5b5f5f964fee885da4f31e343c99f1d8c08838f910f491939d2e2a93cec3b53a1156299fb304c116f166e11088340eb919d6abaeacbc3db1ea1",
          "sha256": "04c6efb933f8786b33252efc8ed196f6c2ffdc8dd187ef0b8360bb377c49cb11",
          "sha1": "ab46240beee03fe3a44f5887f7a879df3bb9a673",
          "md5": "058985fefc672c1812a3e2b8a4426444"
        }
      ]
    }
  ]
}
