{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "piratecashkit",
    "version": "e0a27c4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "e0a27c4"
          }
        }
      ],
      "files": [
        {
          "name": "piratecashkit-e0a27c4.aar",
          "url": "piratecashkit-e0a27c4.aar",
          "size": 290658,
          "sha512": "43a6606fc12c14da23bc5f7a3e96787c13a7eebe0df3566f2812801cb0f3b1614e1caa3918c5190cbdc17c1deb865d594414e0ecc0cf922ebf24be53f0e09baf",
          "sha256": "b0c99527b86955871649bd553b8beb941b185ccdad306a2016f19ff034b474e8",
          "sha1": "416be934a7dd7c1d62b920b6c78a57153e44af67",
          "md5": "0985196e376d945a3918422d46b38b7c"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "dashlib",
          "version": {
            "requires": "e0a27c4"
          }
        },
        {
          "group": "de.sfuhrm",
          "module": "saphir-hash-jca",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "com.github.all3fox",
          "module": "lyra2",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "e0a27c4"
          }
        }
      ],
      "files": [
        {
          "name": "piratecashkit-e0a27c4.aar",
          "url": "piratecashkit-e0a27c4.aar",
          "size": 290658,
          "sha512": "43a6606fc12c14da23bc5f7a3e96787c13a7eebe0df3566f2812801cb0f3b1614e1caa3918c5190cbdc17c1deb865d594414e0ecc0cf922ebf24be53f0e09baf",
          "sha256": "b0c99527b86955871649bd553b8beb941b185ccdad306a2016f19ff034b474e8",
          "sha1": "416be934a7dd7c1d62b920b6c78a57153e44af67",
          "md5": "0985196e376d945a3918422d46b38b7c"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "piratecashkit-e0a27c4-sources.jar",
          "url": "piratecashkit-e0a27c4-sources.jar",
          "size": 289464,
          "sha512": "e6b01de12f464d308573a01cceb748459e1ba9680003dbf871933c3e0febb70a20dadb0377c1fcb72a91a29277c3a14564bf7be3c9f3fccd0c3c1e4c0abaa258",
          "sha256": "020ed3908b854cf210a08425a2c2484f1ea36a637ad53c40aa35037ad7f764ab",
          "sha1": "3c93652aa963e07d432feb6dc87b9f486fa73ec9",
          "md5": "dee24d157469f5b4b6d02c1cef05f38b"
        }
      ]
    }
  ]
}
