[versions]
annotation = "1.1.0"
espressoCore = "3.2.0"
junit = "4.13.2"
junitVersion = "1.1.1"
kotlin = "2.0.21"
room = "2.6.1"
kotlinStdlibJdk7 = "2.0.21"

[libraries]
annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
ext-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlin-stdlib-jdk7 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk7", version.ref = "kotlinStdlibJdk7" }

room-rxjava2 = { module = "androidx.room:room-rxjava2", version.ref = "room" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }

[plugins]
