{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "cosantakit",
    "version": "054fa54",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "054fa54"
          }
        }
      ],
      "files": [
        {
          "name": "cosantakit-054fa54.aar",
          "url": "cosantakit-054fa54.aar",
          "size": 286089,
          "sha512": "d6cc2a5da719248fa399fdbc9e71a171f02d16d34c800be210762e53069d2b19ea295cc149aae9128c5f372e57b51a47800376a542e5ebef7bd8a6186bb08c39",
          "sha256": "32fe0844b8759dae45908b8c60efd65e36b7ce02f4a2db2fcf53f4f6d03898ff",
          "sha1": "0ca4aa2a48f1cee4a854c737597c998f596df356",
          "md5": "49bbd1ce5a4e9dc11494533eb63c303f"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "dashlib",
          "version": {
            "requires": "054fa54"
          }
        },
        {
          "group": "de.sfuhrm",
          "module": "saphir-hash-jca",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "com.github.all3fox",
          "module": "lyra2",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "054fa54"
          }
        }
      ],
      "files": [
        {
          "name": "cosantakit-054fa54.aar",
          "url": "cosantakit-054fa54.aar",
          "size": 286089,
          "sha512": "d6cc2a5da719248fa399fdbc9e71a171f02d16d34c800be210762e53069d2b19ea295cc149aae9128c5f372e57b51a47800376a542e5ebef7bd8a6186bb08c39",
          "sha256": "32fe0844b8759dae45908b8c60efd65e36b7ce02f4a2db2fcf53f4f6d03898ff",
          "sha1": "0ca4aa2a48f1cee4a854c737597c998f596df356",
          "md5": "49bbd1ce5a4e9dc11494533eb63c303f"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "cosantakit-054fa54-sources.jar",
          "url": "cosantakit-054fa54-sources.jar",
          "size": 284577,
          "sha512": "74c8cfbcb4f25aec8ccd4e296cd2d2619e163322057e29739277fe61546ac9a597eda2302653f6c37cf75934a8f17a7757e94fadec012cd35e3610dd65bcd7b1",
          "sha256": "5a8e570c6a642bc42740037b959d0d5e716674e6333a3464918ea6f03fd0a51d",
          "sha1": "e09387f73b48c0982454c7a0348e0ef6a20317be",
          "md5": "52219440ea8c666b2711b3241e6d6f70"
        }
      ]
    }
  ]
}
