{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "dashkit",
    "version": "v0.1.0-pcash.24",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "v0.1.0-pcash.24"
          }
        }
      ],
      "files": [
        {
          "name": "dashkit-v0.1.0-pcash.24.aar",
          "url": "dashkit-v0.1.0-pcash.24.aar",
          "size": 234837,
          "sha512": "e94ea8453e76673b827d5a9672b7b8d85c46773f8afc97ccaa805ccea85e12b3c5959d2cc6bb7bbc021739541cbdb68aefe18185ce906d2c74f4599886537ec0",
          "sha256": "010171257ef95e69878461ddd4297960bd5495989eccc43321efb5832b2125a6",
          "sha1": "b4dd684351cc66b762a33da53335c4fd911895f6",
          "md5": "8a4aed5a8c745c2ab84adc1c7064cdb1"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "dashlib",
          "version": {
            "requires": "v0.1.0-pcash.24"
          }
        },
        {
          "group": "de.sfuhrm",
          "module": "saphir-hash-jca",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "v0.1.0-pcash.24"
          }
        }
      ],
      "files": [
        {
          "name": "dashkit-v0.1.0-pcash.24.aar",
          "url": "dashkit-v0.1.0-pcash.24.aar",
          "size": 234837,
          "sha512": "e94ea8453e76673b827d5a9672b7b8d85c46773f8afc97ccaa805ccea85e12b3c5959d2cc6bb7bbc021739541cbdb68aefe18185ce906d2c74f4599886537ec0",
          "sha256": "010171257ef95e69878461ddd4297960bd5495989eccc43321efb5832b2125a6",
          "sha1": "b4dd684351cc66b762a33da53335c4fd911895f6",
          "md5": "8a4aed5a8c745c2ab84adc1c7064cdb1"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "dashkit-v0.1.0-pcash.24-sources.jar",
          "url": "dashkit-v0.1.0-pcash.24-sources.jar",
          "size": 279921,
          "sha512": "819a1e83207fa9367134b4fb3c439b203856af60a78ccd6705607b387163ddddc40b0a1009a6c951a2d4ad35e584edadab4e2126ec7cb25bc0d8c13c31eb399c",
          "sha256": "f0fc03c014a9625857e9311f295d36543cb0ff616085b6f6950a93daba85ebf1",
          "sha1": "e444c9d303ab5a9c19491a8595e59d20c24b55b3",
          "md5": "875d40a9c4c70bc6f64b805169eade22"
        }
      ]
    }
  ]
}
