{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "bitcoincore",
    "version": "18ce969",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash",
          "module": "hd-wallet-kit-android",
          "version": {
            "requires": "46a441d"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bitcoincore-18ce969.aar",
          "url": "bitcoincore-18ce969.aar",
          "size": 1080571,
          "sha512": "18d3484dc99a0f779aa3b667850c73bff2c0703c215799ddb88715fdc20fb37a42ce81f11d736af77583b8c59753dd87acd4717e04e212c3a7a5105ebcde07bf",
          "sha256": "ed642fffd04a178110861921d508e484c2d4e73a2054a0d121154f94e40d7bf4",
          "sha1": "b86441741ad47d91fbee0bb5b026a68a04215834",
          "md5": "071927968778d64d60e466c08b8a211f"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.5.0"
          }
        },
        {
          "group": "com.github.piratecash",
          "module": "hd-wallet-kit-android",
          "version": {
            "requires": "46a441d"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bitcoincore-18ce969.aar",
          "url": "bitcoincore-18ce969.aar",
          "size": 1080571,
          "sha512": "18d3484dc99a0f779aa3b667850c73bff2c0703c215799ddb88715fdc20fb37a42ce81f11d736af77583b8c59753dd87acd4717e04e212c3a7a5105ebcde07bf",
          "sha256": "ed642fffd04a178110861921d508e484c2d4e73a2054a0d121154f94e40d7bf4",
          "sha1": "b86441741ad47d91fbee0bb5b026a68a04215834",
          "md5": "071927968778d64d60e466c08b8a211f"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "bitcoincore-18ce969-sources.jar",
          "url": "bitcoincore-18ce969-sources.jar",
          "size": 1169730,
          "sha512": "63795a4923e9023432e5741d939a435696026001d0d5630f343536a2bf0cc3ee6f8c46fcfe4fd133470f1d91ee4fa27f9c666a9584884fc72895631bda6cee35",
          "sha256": "f3cd13000c5f540354787368704ac1e705a11499b0dfe3a3a31d446bfa30be89",
          "sha1": "e4ad46835261b9deb0f71ae51fe7266c5a01086c",
          "md5": "77d3a82f62cb9f6ecbb35fa8e0d88e2e"
        }
      ]
    }
  ]
}
