{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "bitcoincore",
    "version": "a073324",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash",
          "module": "hd-wallet-kit-android",
          "version": {
            "requires": "46a441d"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bitcoincore-a073324.aar",
          "url": "bitcoincore-a073324.aar",
          "size": 1126833,
          "sha512": "c7a86f3dc6512f50573afcb8d87ca150e53633af2b69007bd2e8e286082ee764e2392a62cd774cd95770126ff03cabafb0d312e66b9a23f8efe3365630f8bd22",
          "sha256": "3c7f4e4f5de49e593bffbbe03bac337a3785948f875c61459ee1153b8b6b4df9",
          "sha1": "33a8f7a72baf74d4f366d90c9c01d4c9b57404c6",
          "md5": "8eda15e83cc8b0ea94afbab758531e84"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.5.0"
          }
        },
        {
          "group": "com.github.piratecash",
          "module": "hd-wallet-kit-android",
          "version": {
            "requires": "46a441d"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bitcoincore-a073324.aar",
          "url": "bitcoincore-a073324.aar",
          "size": 1126833,
          "sha512": "c7a86f3dc6512f50573afcb8d87ca150e53633af2b69007bd2e8e286082ee764e2392a62cd774cd95770126ff03cabafb0d312e66b9a23f8efe3365630f8bd22",
          "sha256": "3c7f4e4f5de49e593bffbbe03bac337a3785948f875c61459ee1153b8b6b4df9",
          "sha1": "33a8f7a72baf74d4f366d90c9c01d4c9b57404c6",
          "md5": "8eda15e83cc8b0ea94afbab758531e84"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "bitcoincore-a073324-sources.jar",
          "url": "bitcoincore-a073324-sources.jar",
          "size": 1199433,
          "sha512": "4939410991fa8757b947cf784a2cd8f1c0c89342acbb6e8ded011f53e181e621452e01de0a805e6b9a8d1a35561ca514f30d66e1d202961f202c8a253e8e5f63",
          "sha256": "6554ffc52e281c633855caa54ec899941d673f31aba2402a81d05bd24d7322eb",
          "sha1": "730a35652e794390e4f5dff494a494f27fde85fb",
          "md5": "0cf885e1b9158e7b20926f64d92a8ee5"
        }
      ]
    }
  ]
}
