{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "cosantakit",
    "version": "7f1dd29",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "7f1dd29"
          }
        }
      ],
      "files": [
        {
          "name": "cosantakit-7f1dd29.aar",
          "url": "cosantakit-7f1dd29.aar",
          "size": 285980,
          "sha512": "46c623e27ba1d53407b3ad7d4ad279108c8cbd43337f6ac49b67e0857c7fa1b02ebe28666562bec3d66d3ed81fe673e905a3da3176422ed1d0021d78467116b7",
          "sha256": "79cbcbab8acddcac1ac1a290d40a08cb2b8b7a58d448bf816c21f1c641209426",
          "sha1": "068d8bedd8f47f91b3e991099ce5c96cb32fa625",
          "md5": "dce1f1aecc5e57d687fa578f5d6dd681"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "dashlib",
          "version": {
            "requires": "7f1dd29"
          }
        },
        {
          "group": "de.sfuhrm",
          "module": "saphir-hash-jca",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "com.github.all3fox",
          "module": "lyra2",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "7f1dd29"
          }
        }
      ],
      "files": [
        {
          "name": "cosantakit-7f1dd29.aar",
          "url": "cosantakit-7f1dd29.aar",
          "size": 285980,
          "sha512": "46c623e27ba1d53407b3ad7d4ad279108c8cbd43337f6ac49b67e0857c7fa1b02ebe28666562bec3d66d3ed81fe673e905a3da3176422ed1d0021d78467116b7",
          "sha256": "79cbcbab8acddcac1ac1a290d40a08cb2b8b7a58d448bf816c21f1c641209426",
          "sha1": "068d8bedd8f47f91b3e991099ce5c96cb32fa625",
          "md5": "dce1f1aecc5e57d687fa578f5d6dd681"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "cosantakit-7f1dd29-sources.jar",
          "url": "cosantakit-7f1dd29-sources.jar",
          "size": 284582,
          "sha512": "0450ceb1644ea9fc23c124ae5bbcf13c1598b55c45b641bef925ce316bde93dbd874c0ead754bdfab812e0bdc1a41751ef2d62b0324f7ed59abf9fd6f16b66ff",
          "sha256": "ea96f196a1ece71ebe23f2ad158be46f56c049b3521c35f9710a02b6e1bf2bd2",
          "sha1": "f5728cddd7fc50e87a76e7909fffcc6b1e0c7ab7",
          "md5": "6a5f1cea3b45cf0bf67d21aa7962dd5b"
        }
      ]
    }
  ]
}
