{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "litecoinkit",
    "version": "dc3aa12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "dc3aa12"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "hodler",
          "version": {
            "requires": "dc3aa12"
          }
        }
      ],
      "files": [
        {
          "name": "litecoinkit-dc3aa12.aar",
          "url": "litecoinkit-dc3aa12.aar",
          "size": 314090,
          "sha512": "0a8341e3d946de67aa42c7e504c34535cf67f05e8dc34478c6f366942fc6ad51f0c7413c24b42ffcf6cf434febe01628513ae63aafb17c11b4492f151a3f1a98",
          "sha256": "5c8ebf321f8aa0604420211f144239c2e3a568f58ed4fbca7aa55f9bbe0f65a0",
          "sha1": "4366f3eef3dabbe3643c2287df9c12dbe72c1404",
          "md5": "98795c7300042e03eda57b02349dd0b7"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.github.piratecash",
          "module": "mwebd-android",
          "version": {
            "requires": "v0.1.19-pcash.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "dc3aa12"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "hodler",
          "version": {
            "requires": "dc3aa12"
          }
        }
      ],
      "files": [
        {
          "name": "litecoinkit-dc3aa12.aar",
          "url": "litecoinkit-dc3aa12.aar",
          "size": 314090,
          "sha512": "0a8341e3d946de67aa42c7e504c34535cf67f05e8dc34478c6f366942fc6ad51f0c7413c24b42ffcf6cf434febe01628513ae63aafb17c11b4492f151a3f1a98",
          "sha256": "5c8ebf321f8aa0604420211f144239c2e3a568f58ed4fbca7aa55f9bbe0f65a0",
          "sha1": "4366f3eef3dabbe3643c2287df9c12dbe72c1404",
          "md5": "98795c7300042e03eda57b02349dd0b7"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "litecoinkit-dc3aa12-sources.jar",
          "url": "litecoinkit-dc3aa12-sources.jar",
          "size": 203495,
          "sha512": "d69180c049f3b5702e3212be888ef85be5df7f53cd88c69e9ae3c4b2ab99074192b344e4933607efc8514f3864be5ab223113bf511e7ab0b6e1b2823040271f2",
          "sha256": "d09610df69f8dc91e62eea4a909fe7d0a1aed8f82d2f9f25697327f9eb996c14",
          "sha1": "5da7fa81259b064991f13d126c3c84886a63884d",
          "md5": "ff505ca1c26ea76a9b8d102569da38de"
        }
      ]
    }
  ]
}
