{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "bitcoinkit",
    "version": "1c68398",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "1c68398"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "hodler",
          "version": {
            "requires": "1c68398"
          }
        }
      ],
      "files": [
        {
          "name": "bitcoinkit-1c68398.aar",
          "url": "bitcoinkit-1c68398.aar",
          "size": 26885,
          "sha512": "1b05f03416fb83b894fa6f164bb951ff87c7e70e21bfe37263273a4def186e42af016b7f70851110c10207e386a0488a0e95faece217723e3af590ab7c0b7b19",
          "sha256": "37b523b23262bf55532bce5c94946e77f4a3c12719ccdb37a05449b982aca808",
          "sha1": "afadf16f033c45731f0e8628999ce8c88740a1f1",
          "md5": "ebf7a90de75c940c75da922ab101bec3"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "1c68398"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "hodler",
          "version": {
            "requires": "1c68398"
          }
        }
      ],
      "files": [
        {
          "name": "bitcoinkit-1c68398.aar",
          "url": "bitcoinkit-1c68398.aar",
          "size": 26885,
          "sha512": "1b05f03416fb83b894fa6f164bb951ff87c7e70e21bfe37263273a4def186e42af016b7f70851110c10207e386a0488a0e95faece217723e3af590ab7c0b7b19",
          "sha256": "37b523b23262bf55532bce5c94946e77f4a3c12719ccdb37a05449b982aca808",
          "sha1": "afadf16f033c45731f0e8628999ce8c88740a1f1",
          "md5": "ebf7a90de75c940c75da922ab101bec3"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "bitcoinkit-1c68398-sources.jar",
          "url": "bitcoinkit-1c68398-sources.jar",
          "size": 34665,
          "sha512": "f346665e04b3747d64aa96411ed2cae858e759c842ea6328b38fbd1b5cb0ad3a17626b7492980ec8cd73ee2213df5ed704164f5e08bd99b8cb1447e38d49ce7d",
          "sha256": "0323e6630368114bcb58daacdedfcb3683d8e38c8b702049ffee6296696e7dec",
          "sha1": "cd232677273b8ab55ed60660f15e52772b668346",
          "md5": "d7bf5bde09646dc3634703f1709ee8c2"
        }
      ]
    }
  ]
}
