{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "litecoinkit",
    "version": "fb59c34",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "fb59c34"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "hodler",
          "version": {
            "requires": "fb59c34"
          }
        }
      ],
      "files": [
        {
          "name": "litecoinkit-fb59c34.aar",
          "url": "litecoinkit-fb59c34.aar",
          "size": 359050,
          "sha512": "fce767e1d20bf4af1d29fa925aebb9d6d5c99c3bbed9f95e9793ab105bad6293e607191a848fa8f35d7eaac95d2b0781cace39eeb830897a0a8dd0502f827147",
          "sha256": "4d7005a8b38b3cbbd8a922940b8b35782d9837674d83c81d2d71d000d2f5cb62",
          "sha1": "1e3eef7dc452276fcc390ba1625ce04e1eca0830",
          "md5": "a753c5f3b5efb89a4cc7d8a23659f81e"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.github.piratecash",
          "module": "mwebd-android",
          "version": {
            "requires": "v0.1.19-pcash.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "fb59c34"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "hodler",
          "version": {
            "requires": "fb59c34"
          }
        }
      ],
      "files": [
        {
          "name": "litecoinkit-fb59c34.aar",
          "url": "litecoinkit-fb59c34.aar",
          "size": 359050,
          "sha512": "fce767e1d20bf4af1d29fa925aebb9d6d5c99c3bbed9f95e9793ab105bad6293e607191a848fa8f35d7eaac95d2b0781cace39eeb830897a0a8dd0502f827147",
          "sha256": "4d7005a8b38b3cbbd8a922940b8b35782d9837674d83c81d2d71d000d2f5cb62",
          "sha1": "1e3eef7dc452276fcc390ba1625ce04e1eca0830",
          "md5": "a753c5f3b5efb89a4cc7d8a23659f81e"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "litecoinkit-fb59c34-sources.jar",
          "url": "litecoinkit-fb59c34-sources.jar",
          "size": 233870,
          "sha512": "405a1f07b59dfc4a3a02679ebc5c87160f8f1799dbf9dafc658685337f6823fe0efb1b2e0e4a7d280e433ddf6453b7bd75e19fcdc19c9ed82cc7aed148e1a17f",
          "sha256": "96986b05dafc7d5b05d1aebcca5edb4111e49e7948e1e5fefb133a382575e5ee",
          "sha1": "15040284d1f0d058568977943ba4d05d5ee2e331",
          "md5": "8743541c2dc19f541a4a7e62dab4db77"
        }
      ]
    }
  ]
}
