{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "litecoinkit",
    "version": "v0.1.0-pcash.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "v0.1.0-pcash.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "hodler",
          "version": {
            "requires": "v0.1.0-pcash.1"
          }
        }
      ],
      "files": [
        {
          "name": "litecoinkit-v0.1.0-pcash.1.aar",
          "url": "litecoinkit-v0.1.0-pcash.1.aar",
          "size": 551758,
          "sha512": "2867944b7617fcb8b2ef654b050ce9e07f2c95b378b6c521064bd7f3707323036fe47512a3bd3faa2d8be28418329a7ebb0ded870b0a3cc72a4de00c51281b17",
          "sha256": "866cad4b3c85871c4de9c71b58ab6175dd9d92c2d4ce120eb661f2ba18e6afed",
          "sha1": "f92be06fca1efaa7ddc680fe91e2a479044f054d",
          "md5": "eed693f3244ebe6199ab7b27b53891eb"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.github.piratecash",
          "module": "mwebd-android",
          "version": {
            "requires": "v0.1.19-pcash.8"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "v0.1.0-pcash.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "hodler",
          "version": {
            "requires": "v0.1.0-pcash.1"
          }
        }
      ],
      "files": [
        {
          "name": "litecoinkit-v0.1.0-pcash.1.aar",
          "url": "litecoinkit-v0.1.0-pcash.1.aar",
          "size": 551758,
          "sha512": "2867944b7617fcb8b2ef654b050ce9e07f2c95b378b6c521064bd7f3707323036fe47512a3bd3faa2d8be28418329a7ebb0ded870b0a3cc72a4de00c51281b17",
          "sha256": "866cad4b3c85871c4de9c71b58ab6175dd9d92c2d4ce120eb661f2ba18e6afed",
          "sha1": "f92be06fca1efaa7ddc680fe91e2a479044f054d",
          "md5": "eed693f3244ebe6199ab7b27b53891eb"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "litecoinkit-v0.1.0-pcash.1-sources.jar",
          "url": "litecoinkit-v0.1.0-pcash.1-sources.jar",
          "size": 282240,
          "sha512": "9718660cb5d914893e1348f945312e8b0738f5965d8f312bb1b46c48c4aef02b33efcdc40f13f4eb03adc4eca38d8a544b046b70b1fce473b44bca82abaea387",
          "sha256": "c3dbe0195cee37c61f60874aa45da34b3b7ba260e8f67c6cf97ef9e66a7645b9",
          "sha1": "8ed9cdc81128e58251d3a581279eb5a0e1196504",
          "md5": "32a269c8b5b22d6026727ea253208307"
        }
      ]
    }
  ]
}
