{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "cosantakit",
    "version": "v0.1.0-pcash.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "v0.1.0-pcash.8"
          }
        }
      ],
      "files": [
        {
          "name": "cosantakit-v0.1.0-pcash.8.aar",
          "url": "cosantakit-v0.1.0-pcash.8.aar",
          "size": 286096,
          "sha512": "18b64dc8a7c06d02559d4e1215fb4864c0dea5f34b06acd21ff00c967e0a409e3f94c3fcc8d8190170a0865907376909b5d76c690aaa7ed56bc6b4d7ab13416a",
          "sha256": "4f401890dca7e548bb555657d35eecd16d48c3f395d2356a54a8b59f1128aa05",
          "sha1": "f16ce50665f414f7e08bc932acca23ff8e30abb6",
          "md5": "e46bf82d1236aecabbf89a67b9037004"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "dashlib",
          "version": {
            "requires": "v0.1.0-pcash.8"
          }
        },
        {
          "group": "de.sfuhrm",
          "module": "saphir-hash-jca",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "com.github.all3fox",
          "module": "lyra2",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "v0.1.0-pcash.8"
          }
        }
      ],
      "files": [
        {
          "name": "cosantakit-v0.1.0-pcash.8.aar",
          "url": "cosantakit-v0.1.0-pcash.8.aar",
          "size": 286096,
          "sha512": "18b64dc8a7c06d02559d4e1215fb4864c0dea5f34b06acd21ff00c967e0a409e3f94c3fcc8d8190170a0865907376909b5d76c690aaa7ed56bc6b4d7ab13416a",
          "sha256": "4f401890dca7e548bb555657d35eecd16d48c3f395d2356a54a8b59f1128aa05",
          "sha1": "f16ce50665f414f7e08bc932acca23ff8e30abb6",
          "md5": "e46bf82d1236aecabbf89a67b9037004"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "cosantakit-v0.1.0-pcash.8-sources.jar",
          "url": "cosantakit-v0.1.0-pcash.8-sources.jar",
          "size": 284582,
          "sha512": "675a0a741a02494cd873b0eab7eecd90a9665a55d45873c476ab894ac3dabdf0760f44795b00fcf9edbf005992fb1989b0f39444b70bf65fc630239703c087cf",
          "sha256": "27965c0d16e973fd4ae6549310967688298617edc46da7060f30de1dd0ad4ace",
          "sha1": "a047fae5c3d5bc285a501ca58319ee7fc2ef759f",
          "md5": "9bb81800c5c03a5af52d6598e7ba2e8b"
        }
      ]
    }
  ]
}
