{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "litecoinkit",
    "version": "9183c63",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "9183c63"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "hodler",
          "version": {
            "requires": "9183c63"
          }
        }
      ],
      "files": [
        {
          "name": "litecoinkit-9183c63.aar",
          "url": "litecoinkit-9183c63.aar",
          "size": 309614,
          "sha512": "011856d2f641030af80407d3f28dc5403aa0e5efd266fafee90b68878c09a8920a798a03a67c6a9bf9ad6b1f21e47f0d87b14075a729c4d83b3598273f891f5c",
          "sha256": "5aa1159d7853a91ed725365591cec449b512f599ee188c0e4ff221a20b26eb3e",
          "sha1": "714ff2b3e64f5b2c91fc3dc11d510bf437753d1f",
          "md5": "c8bb56a43803dc3a5770ce3ddff1b924"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.github.piratecash",
          "module": "mwebd-android",
          "version": {
            "requires": "v0.1.19-pcash.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "9183c63"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "hodler",
          "version": {
            "requires": "9183c63"
          }
        }
      ],
      "files": [
        {
          "name": "litecoinkit-9183c63.aar",
          "url": "litecoinkit-9183c63.aar",
          "size": 309614,
          "sha512": "011856d2f641030af80407d3f28dc5403aa0e5efd266fafee90b68878c09a8920a798a03a67c6a9bf9ad6b1f21e47f0d87b14075a729c4d83b3598273f891f5c",
          "sha256": "5aa1159d7853a91ed725365591cec449b512f599ee188c0e4ff221a20b26eb3e",
          "sha1": "714ff2b3e64f5b2c91fc3dc11d510bf437753d1f",
          "md5": "c8bb56a43803dc3a5770ce3ddff1b924"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "litecoinkit-9183c63-sources.jar",
          "url": "litecoinkit-9183c63-sources.jar",
          "size": 202765,
          "sha512": "666b532aa07fa254d4b4525df47e0db6050d6ce6ace2c4a8023c4de5557a0f42ce1c08d108721d1e38e397a1873dafabcf50ea5ff93b4edd0ebf39d7651bcff1",
          "sha256": "8624282e10074b7bf3ebd158d5098197b1eb51dbdeedc9b0eb3fc72573a7dd02",
          "sha1": "0b91276bb867e10094e04db234904591f8e33f8a",
          "md5": "a3e085be955ae5023ba3a377a4ec6d5f"
        }
      ]
    }
  ]
}
