plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'org.jetbrains.kotlin.plugin.compose'
}

configurations.all {
    resolutionStrategy {
        eachDependency { details ->
            if (details.requested.group == 'org.bouncycastle' && details.requested.name == 'bcprov-jdk15on') {
                details.useTarget 'org.bouncycastle:bcprov-jdk15to18:1.80'
            }
        }
    }
}

android {
    namespace 'io.horizontalsystems.bitcoinkit.demo'
    compileSdk 36

    defaultConfig {
        applicationId "io.horizontalsystems.bitcoinkit.demo"
        minSdkVersion 24
        targetSdkVersion 36
        versionCode 1
        versionName "0.3.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    buildFeatures {
        compose true
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions { jvmTarget = '17' }
    packagingOptions {
        resources {
            pickFirsts += ['META-INF/atomicfu.kotlin_module']
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation project(':demo-shared')

    implementation libs.androidx.activity.compose
    implementation libs.androidx.lifecycle.viewmodel.compose
    implementation libs.compose.multiplatform.material3
    implementation libs.compose.multiplatform.ui
    implementation libs.compose.multiplatform.ui.tooling.preview
    debugImplementation libs.compose.multiplatform.ui.tooling

    //LeakCanary
    debugImplementation libs.leakcanary.android

    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
}
