{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "cosantakit",
    "version": "v0.1.0-pcash.26",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "v0.1.0-pcash.26"
          }
        }
      ],
      "files": [
        {
          "name": "cosantakit-v0.1.0-pcash.26.aar",
          "url": "cosantakit-v0.1.0-pcash.26.aar",
          "size": 283269,
          "sha512": "4f000c5e6941fe0b1c082e09e7ab00e55d0d9a4d856beabe26ae0ac1ca9a385ebde2912fdaad80f4e5aab63ca5aafbb93e34a80b73adbf99ea292403476a6b98",
          "sha256": "eb5eb16f06f46c0564a9657949d2f0ee4232ec152ffc9658c38af94ba7580d73",
          "sha1": "142708530994bb377c32c90d551b1265255d3daa",
          "md5": "20df81f5d2fb00c46d3b16d646ec057b"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "dashlib",
          "version": {
            "requires": "v0.1.0-pcash.26"
          }
        },
        {
          "group": "de.sfuhrm",
          "module": "saphir-hash-jca",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "com.github.all3fox",
          "module": "lyra2",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "v0.1.0-pcash.26"
          }
        }
      ],
      "files": [
        {
          "name": "cosantakit-v0.1.0-pcash.26.aar",
          "url": "cosantakit-v0.1.0-pcash.26.aar",
          "size": 283269,
          "sha512": "4f000c5e6941fe0b1c082e09e7ab00e55d0d9a4d856beabe26ae0ac1ca9a385ebde2912fdaad80f4e5aab63ca5aafbb93e34a80b73adbf99ea292403476a6b98",
          "sha256": "eb5eb16f06f46c0564a9657949d2f0ee4232ec152ffc9658c38af94ba7580d73",
          "sha1": "142708530994bb377c32c90d551b1265255d3daa",
          "md5": "20df81f5d2fb00c46d3b16d646ec057b"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "cosantakit-v0.1.0-pcash.26-sources.jar",
          "url": "cosantakit-v0.1.0-pcash.26-sources.jar",
          "size": 288657,
          "sha512": "9c56a453880cd97c21b8068e1ddff34f600bffc0f0b53b742cb5c20515ba2aecd527a075d31e125eebb465b8482016e7b4dbc93cff6b10d7dfe8c9de18adb2a3",
          "sha256": "1229d86acd2c0a3954c3ac333038028e781ed9bd1303dc5bf275d1fe051dfa30",
          "sha1": "8ae136a48a958e8675060e4153582ced1cddffd7",
          "md5": "75964b42de739b9f3cea798ddb540528"
        }
      ]
    }
  ]
}
