{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "cosantakit",
    "version": "v0.1.0-pcash.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "v0.1.0-pcash.21"
          }
        }
      ],
      "files": [
        {
          "name": "cosantakit-v0.1.0-pcash.21.aar",
          "url": "cosantakit-v0.1.0-pcash.21.aar",
          "size": 286147,
          "sha512": "31936cbfcfa05ca77c7c6387d2607d0df155b59c55a1548ba5850cd9f314e86eda804fd22a8410bcdc5309f67898fb72b1bf730ef1901426daf544f889218522",
          "sha256": "0495a4b50c42a25e5e176ef3e3f2517ccfee13d02a0ee443be8bc5ab11b77893",
          "sha1": "a8dd11a7233a089f57bd764da44d3842ae48c758",
          "md5": "89764cda9bc7046dc2e3b6b61a2250f5"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "dashlib",
          "version": {
            "requires": "v0.1.0-pcash.21"
          }
        },
        {
          "group": "de.sfuhrm",
          "module": "saphir-hash-jca",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "com.github.all3fox",
          "module": "lyra2",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "v0.1.0-pcash.21"
          }
        }
      ],
      "files": [
        {
          "name": "cosantakit-v0.1.0-pcash.21.aar",
          "url": "cosantakit-v0.1.0-pcash.21.aar",
          "size": 286147,
          "sha512": "31936cbfcfa05ca77c7c6387d2607d0df155b59c55a1548ba5850cd9f314e86eda804fd22a8410bcdc5309f67898fb72b1bf730ef1901426daf544f889218522",
          "sha256": "0495a4b50c42a25e5e176ef3e3f2517ccfee13d02a0ee443be8bc5ab11b77893",
          "sha1": "a8dd11a7233a089f57bd764da44d3842ae48c758",
          "md5": "89764cda9bc7046dc2e3b6b61a2250f5"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "cosantakit-v0.1.0-pcash.21-sources.jar",
          "url": "cosantakit-v0.1.0-pcash.21-sources.jar",
          "size": 287787,
          "sha512": "574c3f318bc4fbc306436011c41dffdb113854ddf306489eb60019f12bba51caf465ff1aecf7da0365ffd98bb21e8b4e1e175be858232378b756c55f37d690dd",
          "sha256": "0a2c94cd0fcc71f04c45167ad01f4d467580845e5969ac64d08d98027e994ece",
          "sha1": "7f0c1c8bf4e3548059485c629aed24632b59f73c",
          "md5": "90f8830c9b2de1d014fdda3ffe06cc12"
        }
      ]
    }
  ]
}
