{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "dashkit",
    "version": "3b49e4c",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "3b49e4c"
          }
        }
      ],
      "files": [
        {
          "name": "dashkit-3b49e4c.aar",
          "url": "dashkit-3b49e4c.aar",
          "size": 234044,
          "sha512": "99df3101bc6856c90191a37ae022fd3ec5b4e936058955e98fa53dc8aa8dc2ddd8f40d36f3efce983a9d8165d6ba656772fba7a9726927ebdf833dec59647c08",
          "sha256": "93b5535637aa8b975403a70afdb0b1f3a3c235e982c486447f23812563215f74",
          "sha1": "7c2ae9471777c036e80e0f12b69d6e635ad79b75",
          "md5": "6794bbcad449cb40a65dc8f6d98ccac2"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "dashlib",
          "version": {
            "requires": "3b49e4c"
          }
        },
        {
          "group": "de.sfuhrm",
          "module": "saphir-hash-jca",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "3b49e4c"
          }
        }
      ],
      "files": [
        {
          "name": "dashkit-3b49e4c.aar",
          "url": "dashkit-3b49e4c.aar",
          "size": 234044,
          "sha512": "99df3101bc6856c90191a37ae022fd3ec5b4e936058955e98fa53dc8aa8dc2ddd8f40d36f3efce983a9d8165d6ba656772fba7a9726927ebdf833dec59647c08",
          "sha256": "93b5535637aa8b975403a70afdb0b1f3a3c235e982c486447f23812563215f74",
          "sha1": "7c2ae9471777c036e80e0f12b69d6e635ad79b75",
          "md5": "6794bbcad449cb40a65dc8f6d98ccac2"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "dashkit-3b49e4c-sources.jar",
          "url": "dashkit-3b49e4c-sources.jar",
          "size": 277466,
          "sha512": "48a1d019201118cc265b02f6cb2924ad3466334692397725579988befb4bf75588be3e629e61f7d551671d7c58b52094883fa3075ff905f8b50bd4a2790e7327",
          "sha256": "1f1b20ccd81911990ce83007fba9e3b12bc897f8df4cb18ffb7b9e65da30fc28",
          "sha1": "4bcf515f95bc179afb62bb29a1fcc394eff9a3c0",
          "md5": "9e7cfdc3192aecf5aa99192042d31534"
        }
      ]
    }
  ]
}
