{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "cosantakit",
    "version": "v0.1.0-pcash.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "v0.1.0-pcash.9"
          }
        }
      ],
      "files": [
        {
          "name": "cosantakit-v0.1.0-pcash.9.aar",
          "url": "cosantakit-v0.1.0-pcash.9.aar",
          "size": 286096,
          "sha512": "18b64dc8a7c06d02559d4e1215fb4864c0dea5f34b06acd21ff00c967e0a409e3f94c3fcc8d8190170a0865907376909b5d76c690aaa7ed56bc6b4d7ab13416a",
          "sha256": "4f401890dca7e548bb555657d35eecd16d48c3f395d2356a54a8b59f1128aa05",
          "sha1": "f16ce50665f414f7e08bc932acca23ff8e30abb6",
          "md5": "e46bf82d1236aecabbf89a67b9037004"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "dashlib",
          "version": {
            "requires": "v0.1.0-pcash.9"
          }
        },
        {
          "group": "de.sfuhrm",
          "module": "saphir-hash-jca",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "com.github.all3fox",
          "module": "lyra2",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "v0.1.0-pcash.9"
          }
        }
      ],
      "files": [
        {
          "name": "cosantakit-v0.1.0-pcash.9.aar",
          "url": "cosantakit-v0.1.0-pcash.9.aar",
          "size": 286096,
          "sha512": "18b64dc8a7c06d02559d4e1215fb4864c0dea5f34b06acd21ff00c967e0a409e3f94c3fcc8d8190170a0865907376909b5d76c690aaa7ed56bc6b4d7ab13416a",
          "sha256": "4f401890dca7e548bb555657d35eecd16d48c3f395d2356a54a8b59f1128aa05",
          "sha1": "f16ce50665f414f7e08bc932acca23ff8e30abb6",
          "md5": "e46bf82d1236aecabbf89a67b9037004"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "cosantakit-v0.1.0-pcash.9-sources.jar",
          "url": "cosantakit-v0.1.0-pcash.9-sources.jar",
          "size": 284582,
          "sha512": "6ed03182ffc2f6bb6c55486a326b75d0e9e8e6f8d017e1572e8858271b0ad63029be5f125a0157b8f6bd494d6ac61da5916aa16b4afe77dda175167f0fdcdad3",
          "sha256": "692cfbf9279a8c3a9c4c04d8ba60236a44f01e1035a76a9ad1f2721367d80a4d",
          "sha1": "6da99deb8cae9e0a5ff3c6f0367a2ce4f1c8a8bd",
          "md5": "f37a49a1f168c2c5365e50052a437614"
        }
      ]
    }
  ]
}
