{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "bitcoincore",
    "version": "v0.1.0-pcash.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash",
          "module": "hd-wallet-kit-android",
          "version": {
            "requires": "46a441d"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bitcoincore-v0.1.0-pcash.23.aar",
          "url": "bitcoincore-v0.1.0-pcash.23.aar",
          "size": 1174685,
          "sha512": "54994a858a07a37295f77cb09dfd3f2090dcd25d28dceba20c7b7a12add10b9a489f3ddc6a18a2625cc72b0176d48cb8a75c26176a1b00db0c20174654e148a7",
          "sha256": "c263549770e823e6fd5b33735658f15928e5618546dd2409c41043370161669a",
          "sha1": "776ee8919f242e4a958b8ad3af6533796fbf06d5",
          "md5": "ce7c5cd432e51a4c509ab59d46add39f"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.5.0"
          }
        },
        {
          "group": "com.github.piratecash",
          "module": "hd-wallet-kit-android",
          "version": {
            "requires": "46a441d"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bitcoincore-v0.1.0-pcash.23.aar",
          "url": "bitcoincore-v0.1.0-pcash.23.aar",
          "size": 1174685,
          "sha512": "54994a858a07a37295f77cb09dfd3f2090dcd25d28dceba20c7b7a12add10b9a489f3ddc6a18a2625cc72b0176d48cb8a75c26176a1b00db0c20174654e148a7",
          "sha256": "c263549770e823e6fd5b33735658f15928e5618546dd2409c41043370161669a",
          "sha1": "776ee8919f242e4a958b8ad3af6533796fbf06d5",
          "md5": "ce7c5cd432e51a4c509ab59d46add39f"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "bitcoincore-v0.1.0-pcash.23-sources.jar",
          "url": "bitcoincore-v0.1.0-pcash.23-sources.jar",
          "size": 1291406,
          "sha512": "248d9f2318ace74f806ee10d004e7da818f21d17e5fdf61f717770d19b4127282658bc219daa3e4080cf3736522b24e28f62cfd083425cdc1fb399d6f4e257d9",
          "sha256": "48930c20ef9511b16675497dcef7682a1009c746d882696789327b9effd344fc",
          "sha1": "deb93536fac90d78ec073c1f7d61cd95faa4b827",
          "md5": "144b22d4485c9ed968fd34e409420ecd"
        }
      ]
    }
  ]
}
