{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "bitcoincore",
    "version": "1c9fba3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash",
          "module": "hd-wallet-kit-android",
          "version": {
            "requires": "46a441d"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bitcoincore-1c9fba3.aar",
          "url": "bitcoincore-1c9fba3.aar",
          "size": 1125111,
          "sha512": "4e8dabc0d3d08b5de13eabf9b72d63165450f51db3720c1d6a93e6862b9359d2c7b1b0816a9e4c22df8be4789a4ab6d8e91081700e4e757d3dc119bccbe08d6b",
          "sha256": "67e80cd1da34169baade7168dad3c02ef5374999506724aa52ec05daac30b0a6",
          "sha1": "9a6f682fdeeeee7b69c375340677675dbcd848ff",
          "md5": "c3666f4f5d44badc43f73c50d7f848b0"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.5.0"
          }
        },
        {
          "group": "com.github.piratecash",
          "module": "hd-wallet-kit-android",
          "version": {
            "requires": "46a441d"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bitcoincore-1c9fba3.aar",
          "url": "bitcoincore-1c9fba3.aar",
          "size": 1125111,
          "sha512": "4e8dabc0d3d08b5de13eabf9b72d63165450f51db3720c1d6a93e6862b9359d2c7b1b0816a9e4c22df8be4789a4ab6d8e91081700e4e757d3dc119bccbe08d6b",
          "sha256": "67e80cd1da34169baade7168dad3c02ef5374999506724aa52ec05daac30b0a6",
          "sha1": "9a6f682fdeeeee7b69c375340677675dbcd848ff",
          "md5": "c3666f4f5d44badc43f73c50d7f848b0"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "bitcoincore-1c9fba3-sources.jar",
          "url": "bitcoincore-1c9fba3-sources.jar",
          "size": 1203563,
          "sha512": "d1a07af9ab0c54d3b2d4bdf9e61fd2e2b9ec62a4d02a31d7920f12cfaf8a8fcf27c7bfcc286068a1b931653fdeeae0eb8e89d17519b9fc9dd96d02a6cab9cc55",
          "sha256": "4fe119c84ab10159c93a77fc17a54a50b6b83a66309cadbac22e55a2e84cf70c",
          "sha1": "322717c13a2446035e6cda674febc16c082a9fdd",
          "md5": "ac721334fc8489ca5a7d1ace797a4110"
        }
      ]
    }
  ]
}
