{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "piratecashkit",
    "version": "054fa54",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "054fa54"
          }
        }
      ],
      "files": [
        {
          "name": "piratecashkit-054fa54.aar",
          "url": "piratecashkit-054fa54.aar",
          "size": 290650,
          "sha512": "59ecadceb573beb250f7294b84597c39d9a5122d8129eb139e59371040ead5cc0ed885432c64927197046af7a416f9688bcbcc1dfd0a7b912426f82f2621e9e5",
          "sha256": "b06043fcb15c856926297b776a5cea968ecc864fa7e352007327fd4df96e7247",
          "sha1": "7399d61911d10fc64f56d05a66be0bd567d37060",
          "md5": "67389235057d91626ae17a3ed6f50cdb"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "dashlib",
          "version": {
            "requires": "054fa54"
          }
        },
        {
          "group": "de.sfuhrm",
          "module": "saphir-hash-jca",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "com.github.all3fox",
          "module": "lyra2",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "054fa54"
          }
        }
      ],
      "files": [
        {
          "name": "piratecashkit-054fa54.aar",
          "url": "piratecashkit-054fa54.aar",
          "size": 290650,
          "sha512": "59ecadceb573beb250f7294b84597c39d9a5122d8129eb139e59371040ead5cc0ed885432c64927197046af7a416f9688bcbcc1dfd0a7b912426f82f2621e9e5",
          "sha256": "b06043fcb15c856926297b776a5cea968ecc864fa7e352007327fd4df96e7247",
          "sha1": "7399d61911d10fc64f56d05a66be0bd567d37060",
          "md5": "67389235057d91626ae17a3ed6f50cdb"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "piratecashkit-054fa54-sources.jar",
          "url": "piratecashkit-054fa54-sources.jar",
          "size": 289464,
          "sha512": "5f9782f5c19fced45f93d43fae4983566961cb0b222764f394fa0666cbad8baa14c9baa35714870ad51ddf9ed71d20485bb4213ca99cd6dfd47d02110d055163",
          "sha256": "bbe5efcb5c5c8416b1e13d3a09ec854fc6ad1c0981f4250036b70704c80e8d10",
          "sha1": "b58f968555382522135325fb199fe752c648f4a5",
          "md5": "7a1b775489d18910fb4274cd43ba8983"
        }
      ]
    }
  ]
}
