{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "dashkit",
    "version": "fadfbf9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "fadfbf9"
          }
        }
      ],
      "files": [
        {
          "name": "dashkit-fadfbf9.aar",
          "url": "dashkit-fadfbf9.aar",
          "size": 234128,
          "sha512": "84c3669e1afe9bcdef4486039ca0e4c9d2f80cf342ecb737051078e515fb59598dadf440797c83da0c63d479038962f3a91d9fb7c3fd7d77312ac6cedab2ca7b",
          "sha256": "1493d222991c97abb9e29533d349ae0465ea2e3a9742b0a72b56c3d86742c3b5",
          "sha1": "dea338b173237af0897325aca2eee3dbbd2eb8f8",
          "md5": "6576a40d84e2281b317be18d6c345e93"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "dashlib",
          "version": {
            "requires": "fadfbf9"
          }
        },
        {
          "group": "de.sfuhrm",
          "module": "saphir-hash-jca",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "fadfbf9"
          }
        }
      ],
      "files": [
        {
          "name": "dashkit-fadfbf9.aar",
          "url": "dashkit-fadfbf9.aar",
          "size": 234128,
          "sha512": "84c3669e1afe9bcdef4486039ca0e4c9d2f80cf342ecb737051078e515fb59598dadf440797c83da0c63d479038962f3a91d9fb7c3fd7d77312ac6cedab2ca7b",
          "sha256": "1493d222991c97abb9e29533d349ae0465ea2e3a9742b0a72b56c3d86742c3b5",
          "sha1": "dea338b173237af0897325aca2eee3dbbd2eb8f8",
          "md5": "6576a40d84e2281b317be18d6c345e93"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "dashkit-fadfbf9-sources.jar",
          "url": "dashkit-fadfbf9-sources.jar",
          "size": 277466,
          "sha512": "668dae1bc53a9ac35840e2fe1015137c0f9a7e2382c4fc87afcb2c278633588dcaff82fd63cadadb9f8468d8063277b82972dfea713d476903db8c9660c694bb",
          "sha256": "7db683472fb38d460d0280b1306aa392872f7b96b3c0c1cd9c421b0ed32113fd",
          "sha1": "9c079d4d09f529eeb81dcf182d2395033e46a7b5",
          "md5": "d448ae1b683b98ae628af060394044a5"
        }
      ]
    }
  ]
}
