{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "dashkit",
    "version": "v0.1.0-pcash.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "v0.1.0-pcash.6"
          }
        }
      ],
      "files": [
        {
          "name": "dashkit-v0.1.0-pcash.6.aar",
          "url": "dashkit-v0.1.0-pcash.6.aar",
          "size": 234253,
          "sha512": "29b994d4e35fb729ba7539bab20c5c4f93ec1ff8221e65b817c2d0a926a7c5f6f3fa29f0f0505d3b9aac63aa1fd6bdcb6787d386622e0e0d3b4e446cd9c4fee3",
          "sha256": "da32f0d860c61b2b494c922e160a05555388aa4860bd68186132d95e9a7cd931",
          "sha1": "d26b4da5ee88aba67546b4c742b3e63fa5968a44",
          "md5": "cc2d352eb453ab2c172cdd6a4eaaa622"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "dashlib",
          "version": {
            "requires": "v0.1.0-pcash.6"
          }
        },
        {
          "group": "de.sfuhrm",
          "module": "saphir-hash-jca",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "v0.1.0-pcash.6"
          }
        }
      ],
      "files": [
        {
          "name": "dashkit-v0.1.0-pcash.6.aar",
          "url": "dashkit-v0.1.0-pcash.6.aar",
          "size": 234253,
          "sha512": "29b994d4e35fb729ba7539bab20c5c4f93ec1ff8221e65b817c2d0a926a7c5f6f3fa29f0f0505d3b9aac63aa1fd6bdcb6787d386622e0e0d3b4e446cd9c4fee3",
          "sha256": "da32f0d860c61b2b494c922e160a05555388aa4860bd68186132d95e9a7cd931",
          "sha1": "d26b4da5ee88aba67546b4c742b3e63fa5968a44",
          "md5": "cc2d352eb453ab2c172cdd6a4eaaa622"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "dashkit-v0.1.0-pcash.6-sources.jar",
          "url": "dashkit-v0.1.0-pcash.6-sources.jar",
          "size": 277501,
          "sha512": "c5ea791728aa396524576528703fdc865cdc040625a95c6623256fba9921f3e1de7c87c88a5c456d699571d5ff3b0cf5db78bfdb61ee6c661016c3422d565bcd",
          "sha256": "8805004b0dbdf167c08be0dfdc608524b79be39f8954dc455bff752ef4c4420c",
          "sha1": "66ae3842a3ab59b4276a209df4b974b9d10a1c2a",
          "md5": "6e2904a9ed27a080d609e86eef041ed4"
        }
      ]
    }
  ]
}
