{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "bitcoincore",
    "version": "3c61171",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash",
          "module": "hd-wallet-kit-android",
          "version": {
            "requires": "46a441d"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bitcoincore-3c61171.aar",
          "url": "bitcoincore-3c61171.aar",
          "size": 1133428,
          "sha512": "acb7651ca4fbade958dfb76835597ab739876eb4657f824e787ce66add2297b31e23900be4ea497b1932d69c74e16bd7e34243b9933fdb752c2a442d5e4832df",
          "sha256": "1f0af83c9effc0b5e670161a631f9190be34c219f79cf77dd9b14e4e5197f734",
          "sha1": "ca0e9fba477f820f820b56eb8cb9f89dd33c6855",
          "md5": "5414ec228083a851ada410b8f0b3054b"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.5.0"
          }
        },
        {
          "group": "com.github.piratecash",
          "module": "hd-wallet-kit-android",
          "version": {
            "requires": "46a441d"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bitcoincore-3c61171.aar",
          "url": "bitcoincore-3c61171.aar",
          "size": 1133428,
          "sha512": "acb7651ca4fbade958dfb76835597ab739876eb4657f824e787ce66add2297b31e23900be4ea497b1932d69c74e16bd7e34243b9933fdb752c2a442d5e4832df",
          "sha256": "1f0af83c9effc0b5e670161a631f9190be34c219f79cf77dd9b14e4e5197f734",
          "sha1": "ca0e9fba477f820f820b56eb8cb9f89dd33c6855",
          "md5": "5414ec228083a851ada410b8f0b3054b"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "bitcoincore-3c61171-sources.jar",
          "url": "bitcoincore-3c61171-sources.jar",
          "size": 1236592,
          "sha512": "50a2fe1fc777744a1421a5c0e9d51d554f9e5803b5fbf2cecaffaf9a0a61c8f06e32237e900b98a40b76f7aca6a508dbb666592d0819819c87d61c10b144bb13",
          "sha256": "edaf50126e44a7c6a61c215a5ade7fca0d961062601cb2a90964130fcba796f1",
          "sha1": "7e3c2db2cc2c9fdbe74a9920a82db0e79b1b1e93",
          "md5": "90a1559298da1c2d11e5eaddf011db50"
        }
      ]
    }
  ]
}
