{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "cosantakit",
    "version": "8e318e2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "8e318e2"
          }
        }
      ],
      "files": [
        {
          "name": "cosantakit-8e318e2.aar",
          "url": "cosantakit-8e318e2.aar",
          "size": 286747,
          "sha512": "f9adaae022056bb5bb61358df92c82aa23bacc2480d9412c319921fe146ad6f0c73aeaae2251f7ace7dee000fc256f955080a12fc8b3288e966ed3d2142501b2",
          "sha256": "79ad4ab2b4f281cb66fee1d578edd4f750950ed6479ea0d2fcfd6ccb561cf48e",
          "sha1": "62388a082dc9b0f00437120931fc6a4742b72a0d",
          "md5": "150435246320cc9d072d9e35e8e83746"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "dashlib",
          "version": {
            "requires": "8e318e2"
          }
        },
        {
          "group": "de.sfuhrm",
          "module": "saphir-hash-jca",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "com.github.all3fox",
          "module": "lyra2",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "8e318e2"
          }
        }
      ],
      "files": [
        {
          "name": "cosantakit-8e318e2.aar",
          "url": "cosantakit-8e318e2.aar",
          "size": 286747,
          "sha512": "f9adaae022056bb5bb61358df92c82aa23bacc2480d9412c319921fe146ad6f0c73aeaae2251f7ace7dee000fc256f955080a12fc8b3288e966ed3d2142501b2",
          "sha256": "79ad4ab2b4f281cb66fee1d578edd4f750950ed6479ea0d2fcfd6ccb561cf48e",
          "sha1": "62388a082dc9b0f00437120931fc6a4742b72a0d",
          "md5": "150435246320cc9d072d9e35e8e83746"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "cosantakit-8e318e2-sources.jar",
          "url": "cosantakit-8e318e2-sources.jar",
          "size": 289532,
          "sha512": "9773ca390f5f507977188c0a6fd56d20a190245cfb39b762ca44ba773a55e5e382879b34b4a333ed3ee02b8a072c525d43ce6808a578fd10a0742d4efed64bd3",
          "sha256": "a3b9cef5764401141832057052d30cd90a7dccdfecd371725c78d7fe305f8ca3",
          "sha1": "9ed7763444ab42c7fe06d5a773d748a438594757",
          "md5": "5fbfd755aa729c20561d280b5e6c686e"
        }
      ]
    }
  ]
}
