{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "litecoinkit",
    "version": "v0.1.0-pcash.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "v0.1.0-pcash.2"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "hodler",
          "version": {
            "requires": "v0.1.0-pcash.2"
          }
        }
      ],
      "files": [
        {
          "name": "litecoinkit-v0.1.0-pcash.2.aar",
          "url": "litecoinkit-v0.1.0-pcash.2.aar",
          "size": 551758,
          "sha512": "2867944b7617fcb8b2ef654b050ce9e07f2c95b378b6c521064bd7f3707323036fe47512a3bd3faa2d8be28418329a7ebb0ded870b0a3cc72a4de00c51281b17",
          "sha256": "866cad4b3c85871c4de9c71b58ab6175dd9d92c2d4ce120eb661f2ba18e6afed",
          "sha1": "f92be06fca1efaa7ddc680fe91e2a479044f054d",
          "md5": "eed693f3244ebe6199ab7b27b53891eb"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.github.piratecash",
          "module": "mwebd-android",
          "version": {
            "requires": "v0.1.19-pcash.8"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "v0.1.0-pcash.2"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "hodler",
          "version": {
            "requires": "v0.1.0-pcash.2"
          }
        }
      ],
      "files": [
        {
          "name": "litecoinkit-v0.1.0-pcash.2.aar",
          "url": "litecoinkit-v0.1.0-pcash.2.aar",
          "size": 551758,
          "sha512": "2867944b7617fcb8b2ef654b050ce9e07f2c95b378b6c521064bd7f3707323036fe47512a3bd3faa2d8be28418329a7ebb0ded870b0a3cc72a4de00c51281b17",
          "sha256": "866cad4b3c85871c4de9c71b58ab6175dd9d92c2d4ce120eb661f2ba18e6afed",
          "sha1": "f92be06fca1efaa7ddc680fe91e2a479044f054d",
          "md5": "eed693f3244ebe6199ab7b27b53891eb"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "litecoinkit-v0.1.0-pcash.2-sources.jar",
          "url": "litecoinkit-v0.1.0-pcash.2-sources.jar",
          "size": 282240,
          "sha512": "23630960dec062919d3289c6c41a1cc62250150d522a5b39d7893d12ffb9f2cc644a5d238ad5ad18bcaf25e9a2c367c3256a18fa9c87fdadcde25f69d4feec58",
          "sha256": "352765d22166ea9f8bbdcb5bb3f6bcedc1f55d0940fae2894131156ad7e930f2",
          "sha1": "47e66a444054790c19db18f63532c907cd720a76",
          "md5": "4c82da439cf3a5d839b871a841985574"
        }
      ]
    }
  ]
}
