{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "bitcoincore",
    "version": "91b9795",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash",
          "module": "hd-wallet-kit-android",
          "version": {
            "requires": "46a441d"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bitcoincore-91b9795.aar",
          "url": "bitcoincore-91b9795.aar",
          "size": 1126617,
          "sha512": "2826e0d2e7bc9597f25367df8a602109d3d2e7ccd9ca8e835f80114df31e70f9bc155bab740d16a464383a8c7fe54488494d7c87fa234524dcf155780717fcba",
          "sha256": "51e1cdc32b9587d91f6b5cf96bf8199db1771933c29db4632d4582fb2a44e60c",
          "sha1": "47fc22e415d3f4f1becb09abc2016ad5640a29a5",
          "md5": "057b332ef3cb0e5bcc40ae6fcaa86263"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.5.0"
          }
        },
        {
          "group": "com.github.piratecash",
          "module": "hd-wallet-kit-android",
          "version": {
            "requires": "46a441d"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bitcoincore-91b9795.aar",
          "url": "bitcoincore-91b9795.aar",
          "size": 1126617,
          "sha512": "2826e0d2e7bc9597f25367df8a602109d3d2e7ccd9ca8e835f80114df31e70f9bc155bab740d16a464383a8c7fe54488494d7c87fa234524dcf155780717fcba",
          "sha256": "51e1cdc32b9587d91f6b5cf96bf8199db1771933c29db4632d4582fb2a44e60c",
          "sha1": "47fc22e415d3f4f1becb09abc2016ad5640a29a5",
          "md5": "057b332ef3cb0e5bcc40ae6fcaa86263"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "bitcoincore-91b9795-sources.jar",
          "url": "bitcoincore-91b9795-sources.jar",
          "size": 1198838,
          "sha512": "caf317f8280b60350856b69714b048e8aae9957f1c5423a214600a98b8e345163eb91ecd684dfde99095ddfd4ce6e7e9e9f6fc89e6717710d4f5ef0b52b1923e",
          "sha256": "ef616572b5339e3cadb1bd562fe3b71677e932ae9e29bb6431a117627802888a",
          "sha1": "85f02280cbe29df5cee579b197c0c6482c7a51ae",
          "md5": "a9c4db74479896acb3be10634e065ac8"
        }
      ]
    }
  ]
}
