{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "litecoinkit",
    "version": "3a320fa",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "3a320fa"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "hodler",
          "version": {
            "requires": "3a320fa"
          }
        }
      ],
      "files": [
        {
          "name": "litecoinkit-3a320fa.aar",
          "url": "litecoinkit-3a320fa.aar",
          "size": 527293,
          "sha512": "a08fd7047a01969543d8e7b44f2f3a2b5cfddcc10b38dd2d8812359cb2487689e3df0f3a8cccb47020366d6bb539d5ee5fd91284438d768a06af34dfda19f0e2",
          "sha256": "8e1aae547aadb11aaf48e713df64b9276eafc962c13508725a0a90c32a0cede9",
          "sha1": "399c0d078200b2caa10bd07d3e87b74fe40f09ec",
          "md5": "fdc459e8766fea1d43979240ac7f6011"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.github.piratecash",
          "module": "mwebd-android",
          "version": {
            "requires": "v0.1.19-pcash.7"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "3a320fa"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "hodler",
          "version": {
            "requires": "3a320fa"
          }
        }
      ],
      "files": [
        {
          "name": "litecoinkit-3a320fa.aar",
          "url": "litecoinkit-3a320fa.aar",
          "size": 527293,
          "sha512": "a08fd7047a01969543d8e7b44f2f3a2b5cfddcc10b38dd2d8812359cb2487689e3df0f3a8cccb47020366d6bb539d5ee5fd91284438d768a06af34dfda19f0e2",
          "sha256": "8e1aae547aadb11aaf48e713df64b9276eafc962c13508725a0a90c32a0cede9",
          "sha1": "399c0d078200b2caa10bd07d3e87b74fe40f09ec",
          "md5": "fdc459e8766fea1d43979240ac7f6011"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "litecoinkit-3a320fa-sources.jar",
          "url": "litecoinkit-3a320fa-sources.jar",
          "size": 267990,
          "sha512": "b7fc1106e50e913a6a6e28ee48c5b7245733b8dd2225b0440ef3b75cabf7dedd52b088f1de0dcdba68e0d31d18030174f450f817c5235cdee0288d56a734967c",
          "sha256": "cf11c5df318f0d81c598b325573808fab04528d03e67bc94fbb1a804bdb3e0f7",
          "sha1": "f1ac1e59b063814ab911327b2cd65e7df904c0d5",
          "md5": "6ab7c5f9198809a1e7b1257fec14c1ef"
        }
      ]
    }
  ]
}
