{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "litecoinkit",
    "version": "edd535d",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "edd535d"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "hodler",
          "version": {
            "requires": "edd535d"
          }
        }
      ],
      "files": [
        {
          "name": "litecoinkit-edd535d.aar",
          "url": "litecoinkit-edd535d.aar",
          "size": 389853,
          "sha512": "0144a3a96a2b694d0614a0d6a8e6a2113e1829051d1e5a09cd83824ef7c31ad192d2fb9a9985a42299142d88698d0dfa68818dba4b0a6b93a37e04152b7ecdab",
          "sha256": "82548f1a4b82645e0e76e969680bd5dfa0e14dc2a2989e048392288bc532fb01",
          "sha1": "b17652cb5b6c6c3faf00fc5f77d88254048a8b43",
          "md5": "1ce3161d4297c54e85e815d987f0517a"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.github.piratecash",
          "module": "mwebd-android",
          "version": {
            "requires": "v0.1.19-pcash.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "edd535d"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "hodler",
          "version": {
            "requires": "edd535d"
          }
        }
      ],
      "files": [
        {
          "name": "litecoinkit-edd535d.aar",
          "url": "litecoinkit-edd535d.aar",
          "size": 389853,
          "sha512": "0144a3a96a2b694d0614a0d6a8e6a2113e1829051d1e5a09cd83824ef7c31ad192d2fb9a9985a42299142d88698d0dfa68818dba4b0a6b93a37e04152b7ecdab",
          "sha256": "82548f1a4b82645e0e76e969680bd5dfa0e14dc2a2989e048392288bc532fb01",
          "sha1": "b17652cb5b6c6c3faf00fc5f77d88254048a8b43",
          "md5": "1ce3161d4297c54e85e815d987f0517a"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "litecoinkit-edd535d-sources.jar",
          "url": "litecoinkit-edd535d-sources.jar",
          "size": 254185,
          "sha512": "9438752f1866db1b4c304badabf9206aa19920808c2782ec576a462e61386586ef1e36134c20f743a9583dd9bc6a024394aff13cad79571a3cf1b1eb1b47978f",
          "sha256": "1c3eb03dc77ab68f04bad86bd229710130fe23aa5b88882d0ccd4238913b98ba",
          "sha1": "3891e1d95a5f107167e28938d1d18159680c54ea",
          "md5": "21dc72b809e505d76736d0bc46dcb8af"
        }
      ]
    }
  ]
}
