{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "bitcoinkit",
    "version": "bbf7636",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "bbf7636"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "hodler",
          "version": {
            "requires": "bbf7636"
          }
        }
      ],
      "files": [
        {
          "name": "bitcoinkit-bbf7636.aar",
          "url": "bitcoinkit-bbf7636.aar",
          "size": 26977,
          "sha512": "ca908caad516342a84af4f5e771aa85ea750c2d32e21f7c203f808f907d8f552af9201cd5980aed041206ed851d278ad6457bf4be2f371bec517d246f9a735ab",
          "sha256": "8fc1bf99c1b148db15b00b06e146600b64fbe5b660e27a6b4a84d73594de8474",
          "sha1": "c941a3601beae9da9eff465e60986e73ffecdaaa",
          "md5": "7ae034a2e9ce3d7d68ffe5a640b504a9"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "bbf7636"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "hodler",
          "version": {
            "requires": "bbf7636"
          }
        }
      ],
      "files": [
        {
          "name": "bitcoinkit-bbf7636.aar",
          "url": "bitcoinkit-bbf7636.aar",
          "size": 26977,
          "sha512": "ca908caad516342a84af4f5e771aa85ea750c2d32e21f7c203f808f907d8f552af9201cd5980aed041206ed851d278ad6457bf4be2f371bec517d246f9a735ab",
          "sha256": "8fc1bf99c1b148db15b00b06e146600b64fbe5b660e27a6b4a84d73594de8474",
          "sha1": "c941a3601beae9da9eff465e60986e73ffecdaaa",
          "md5": "7ae034a2e9ce3d7d68ffe5a640b504a9"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "bitcoinkit-bbf7636-sources.jar",
          "url": "bitcoinkit-bbf7636-sources.jar",
          "size": 34755,
          "sha512": "4f7b8f9b733214baf85972fe1f5d450f363ad8a4be89c3b616789f6470ce398577394104b192397888eef2d94076ffa9fc0e7b531719a4c597938245a21c8e08",
          "sha256": "8e4ab8a89b86d27c5368a1f3a885caf1986849fc77adf8ec61cf65200430cee6",
          "sha1": "f254e293b2ba72305df5ef4b9f14230ddcce577f",
          "md5": "ac267f1072370d83d02058a33c07427f"
        }
      ]
    }
  ]
}
