{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "litecoinkit",
    "version": "v0.1.0-pcash.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "v0.1.0-pcash.23"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "hodler",
          "version": {
            "requires": "v0.1.0-pcash.23"
          }
        }
      ],
      "files": [
        {
          "name": "litecoinkit-v0.1.0-pcash.23.aar",
          "url": "litecoinkit-v0.1.0-pcash.23.aar",
          "size": 595742,
          "sha512": "87b313a89b63f8b4865068b33b6a1bb7c3a458d6ce2fdc318f6959525e87655c3133a96356233694d779968ab43438910a746da66a13a5a2d5440b000c4affcf",
          "sha256": "38972f5cd3a1189b3664112c689d8d52873b213dbe893e6de718337ec5d89853",
          "sha1": "632103c43bc7441f499ab0ff7507bfa29b800e20",
          "md5": "f0ece284c4ed1cefd1d4f1ff43dcfb54"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.github.piratecash",
          "module": "mwebd-android",
          "version": {
            "requires": "v0.1.19-pcash.9"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "v0.1.0-pcash.23"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "hodler",
          "version": {
            "requires": "v0.1.0-pcash.23"
          }
        }
      ],
      "files": [
        {
          "name": "litecoinkit-v0.1.0-pcash.23.aar",
          "url": "litecoinkit-v0.1.0-pcash.23.aar",
          "size": 595742,
          "sha512": "87b313a89b63f8b4865068b33b6a1bb7c3a458d6ce2fdc318f6959525e87655c3133a96356233694d779968ab43438910a746da66a13a5a2d5440b000c4affcf",
          "sha256": "38972f5cd3a1189b3664112c689d8d52873b213dbe893e6de718337ec5d89853",
          "sha1": "632103c43bc7441f499ab0ff7507bfa29b800e20",
          "md5": "f0ece284c4ed1cefd1d4f1ff43dcfb54"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "litecoinkit-v0.1.0-pcash.23-sources.jar",
          "url": "litecoinkit-v0.1.0-pcash.23-sources.jar",
          "size": 300565,
          "sha512": "624f50ee2b8a7eb42234606eb533e0674986d08c7512b1721a7fd0cb3815da03b2323bca5bfacab4413ef01287c57d533084815a710b3ee21ffda2426c4c96d6",
          "sha256": "c9d020bfcc216653ad4b1b8cc2c6166e570549623fbc25595e5cbfbf0fe1677f",
          "sha1": "15c8564c233859d2090abd56895f5e633689bf95",
          "md5": "d57d25dbe0e174cf6befed791a068f24"
        }
      ]
    }
  ]
}
