{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "litecoinkit",
    "version": "1c9fba3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "1c9fba3"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "hodler",
          "version": {
            "requires": "1c9fba3"
          }
        }
      ],
      "files": [
        {
          "name": "litecoinkit-1c9fba3.aar",
          "url": "litecoinkit-1c9fba3.aar",
          "size": 551796,
          "sha512": "fcf28057082ed9527d211825b5a21ea8087d6e84a2f1d22ab603403b6d2a0dfa04e32bd598d01afac6b4adab3eee52f1ef55114d0be728fd2bbc7c8dd30daeb4",
          "sha256": "b04447cc2ecd2fa69eac88e03f6d36692e123c3ab8712079715ae3b50ed60c2b",
          "sha1": "43138a9391e33903b11acf8ce3813558f3354b5d",
          "md5": "5b3682958bf7d79aed1fcaab3238949e"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.github.piratecash",
          "module": "mwebd-android",
          "version": {
            "requires": "v0.1.19-pcash.8"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "1c9fba3"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "hodler",
          "version": {
            "requires": "1c9fba3"
          }
        }
      ],
      "files": [
        {
          "name": "litecoinkit-1c9fba3.aar",
          "url": "litecoinkit-1c9fba3.aar",
          "size": 551796,
          "sha512": "fcf28057082ed9527d211825b5a21ea8087d6e84a2f1d22ab603403b6d2a0dfa04e32bd598d01afac6b4adab3eee52f1ef55114d0be728fd2bbc7c8dd30daeb4",
          "sha256": "b04447cc2ecd2fa69eac88e03f6d36692e123c3ab8712079715ae3b50ed60c2b",
          "sha1": "43138a9391e33903b11acf8ce3813558f3354b5d",
          "md5": "5b3682958bf7d79aed1fcaab3238949e"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "litecoinkit-1c9fba3-sources.jar",
          "url": "litecoinkit-1c9fba3-sources.jar",
          "size": 282340,
          "sha512": "56fc59e99e26e0bf5a1fbbd363f373af224ce8a896c099e87af39134c767a3febacb16d17a7e15fd833140fb26f593833cf0884f67c44c5a22627ef8d234e979",
          "sha256": "acdd3dd92b9ec420b4f236788ad169fba745235a7d448f378463e915920189a5",
          "sha1": "1b6c85e8f19af63bab64293704ab5921302d01fa",
          "md5": "d3253e153d11422955e9a14b9982393e"
        }
      ]
    }
  ]
}
