{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "bitcoincore",
    "version": "1702e2f",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash",
          "module": "hd-wallet-kit-android",
          "version": {
            "requires": "46a441d"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bitcoincore-1702e2f.aar",
          "url": "bitcoincore-1702e2f.aar",
          "size": 1159581,
          "sha512": "3f76745d85248b7d447ab89219750c6fbe5538040af8bbc497d64cf881b6566632cf1a4ec56f22733092bf18f5014ede7ef79c80fdf6cdb39a9af2be9a484c29",
          "sha256": "1c932bc84c373b81d1b1ad61298f7cd060ded228ca9ae80d1438f7080e824aad",
          "sha1": "96c62233766273053e6109c7080a7db90552fa0b",
          "md5": "06b4200a076575f9cdffa1426e87673a"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.5.0"
          }
        },
        {
          "group": "com.github.piratecash",
          "module": "hd-wallet-kit-android",
          "version": {
            "requires": "46a441d"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bitcoincore-1702e2f.aar",
          "url": "bitcoincore-1702e2f.aar",
          "size": 1159581,
          "sha512": "3f76745d85248b7d447ab89219750c6fbe5538040af8bbc497d64cf881b6566632cf1a4ec56f22733092bf18f5014ede7ef79c80fdf6cdb39a9af2be9a484c29",
          "sha256": "1c932bc84c373b81d1b1ad61298f7cd060ded228ca9ae80d1438f7080e824aad",
          "sha1": "96c62233766273053e6109c7080a7db90552fa0b",
          "md5": "06b4200a076575f9cdffa1426e87673a"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "bitcoincore-1702e2f-sources.jar",
          "url": "bitcoincore-1702e2f-sources.jar",
          "size": 1261866,
          "sha512": "9bad4f08122b2b5d74a650b362a1b132dd36febace7e6baae6a21563dac9ea34d613288efae4666a9f414817dffc64b634c1a8615f236f3fdf7fa05ddc319cd8",
          "sha256": "814897db9b64d3153a6ded3d989ee36a60125313af010d381759afbce3b4b549",
          "sha1": "c19eeea4587bf1ed16dcbf8b88d00bc4bf4d0de9",
          "md5": "7737e16eb9282f763bb5aa129bca94bc"
        }
      ]
    }
  ]
}
