{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "bitcoincore",
    "version": "8205084",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash",
          "module": "hd-wallet-kit-android",
          "version": {
            "requires": "46a441d"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bitcoincore-8205084.aar",
          "url": "bitcoincore-8205084.aar",
          "size": 1133462,
          "sha512": "fb6b09d4cb18a9c3bc482b63b8d411204dc00d346890a14162abc5a9072336c5113e0473577d2e5c71ed7b5b87e6f8ffde3b42d0f23bebb90054047cb05ebaf2",
          "sha256": "6d74c55aa2f1117f7483e9e77ae7e4f7b1021960afe8ffa0ac66e0240765ba70",
          "sha1": "229d9708d6a1437efdad2f73a658b39b09dc7dc2",
          "md5": "1a3aa6b21e64e69d38e054af773be1f2"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.5.0"
          }
        },
        {
          "group": "com.github.piratecash",
          "module": "hd-wallet-kit-android",
          "version": {
            "requires": "46a441d"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bitcoincore-8205084.aar",
          "url": "bitcoincore-8205084.aar",
          "size": 1133462,
          "sha512": "fb6b09d4cb18a9c3bc482b63b8d411204dc00d346890a14162abc5a9072336c5113e0473577d2e5c71ed7b5b87e6f8ffde3b42d0f23bebb90054047cb05ebaf2",
          "sha256": "6d74c55aa2f1117f7483e9e77ae7e4f7b1021960afe8ffa0ac66e0240765ba70",
          "sha1": "229d9708d6a1437efdad2f73a658b39b09dc7dc2",
          "md5": "1a3aa6b21e64e69d38e054af773be1f2"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "bitcoincore-8205084-sources.jar",
          "url": "bitcoincore-8205084-sources.jar",
          "size": 1238597,
          "sha512": "a36d9d876e1f59c1cfdfb5d2d54a913b74ee08ba60eac1832ea0e9f9757ad69fc99efefcf2c93b82604204f54290c738d977cbebd54aba2ec1bbead4a9b4bec2",
          "sha256": "2de7f629e55dc8509f772a31786c3039a73c9aeb4085fab24d4d585f86ea028e",
          "sha1": "3803191b7b7e6c01c69d841d94ffbfaee9e55549",
          "md5": "2aea870f617ef1639af4c9b408bedb64"
        }
      ]
    }
  ]
}
