{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "bitcoincore",
    "version": "2444c01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash",
          "module": "hd-wallet-kit-android",
          "version": {
            "requires": "46a441d"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bitcoincore-2444c01.aar",
          "url": "bitcoincore-2444c01.aar",
          "size": 1133428,
          "sha512": "acb7651ca4fbade958dfb76835597ab739876eb4657f824e787ce66add2297b31e23900be4ea497b1932d69c74e16bd7e34243b9933fdb752c2a442d5e4832df",
          "sha256": "1f0af83c9effc0b5e670161a631f9190be34c219f79cf77dd9b14e4e5197f734",
          "sha1": "ca0e9fba477f820f820b56eb8cb9f89dd33c6855",
          "md5": "5414ec228083a851ada410b8f0b3054b"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.5.0"
          }
        },
        {
          "group": "com.github.piratecash",
          "module": "hd-wallet-kit-android",
          "version": {
            "requires": "46a441d"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bitcoincore-2444c01.aar",
          "url": "bitcoincore-2444c01.aar",
          "size": 1133428,
          "sha512": "acb7651ca4fbade958dfb76835597ab739876eb4657f824e787ce66add2297b31e23900be4ea497b1932d69c74e16bd7e34243b9933fdb752c2a442d5e4832df",
          "sha256": "1f0af83c9effc0b5e670161a631f9190be34c219f79cf77dd9b14e4e5197f734",
          "sha1": "ca0e9fba477f820f820b56eb8cb9f89dd33c6855",
          "md5": "5414ec228083a851ada410b8f0b3054b"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "bitcoincore-2444c01-sources.jar",
          "url": "bitcoincore-2444c01-sources.jar",
          "size": 1236592,
          "sha512": "ddbdfe0d33a0fb005393ad1c9185b16ad3a4f8e9184cc60992aebea43af49ed8cc304f8e46dd52ff4078a7a58face174d259cd60927c3028fd05c6f0189920f7",
          "sha256": "913c798102a2ef0cb568bed9f3001327d714ad4f4a0a6f04f7daa867662a966f",
          "sha1": "a5e26e0fe3b785fe99f32034410b492e575d8145",
          "md5": "77549a9880ea5367401322859a0abe61"
        }
      ]
    }
  ]
}
