{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "cosantakit",
    "version": "3b49e4c",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "3b49e4c"
          }
        }
      ],
      "files": [
        {
          "name": "cosantakit-3b49e4c.aar",
          "url": "cosantakit-3b49e4c.aar",
          "size": 285980,
          "sha512": "46c623e27ba1d53407b3ad7d4ad279108c8cbd43337f6ac49b67e0857c7fa1b02ebe28666562bec3d66d3ed81fe673e905a3da3176422ed1d0021d78467116b7",
          "sha256": "79cbcbab8acddcac1ac1a290d40a08cb2b8b7a58d448bf816c21f1c641209426",
          "sha1": "068d8bedd8f47f91b3e991099ce5c96cb32fa625",
          "md5": "dce1f1aecc5e57d687fa578f5d6dd681"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "dashlib",
          "version": {
            "requires": "3b49e4c"
          }
        },
        {
          "group": "de.sfuhrm",
          "module": "saphir-hash-jca",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "com.github.all3fox",
          "module": "lyra2",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "3b49e4c"
          }
        }
      ],
      "files": [
        {
          "name": "cosantakit-3b49e4c.aar",
          "url": "cosantakit-3b49e4c.aar",
          "size": 285980,
          "sha512": "46c623e27ba1d53407b3ad7d4ad279108c8cbd43337f6ac49b67e0857c7fa1b02ebe28666562bec3d66d3ed81fe673e905a3da3176422ed1d0021d78467116b7",
          "sha256": "79cbcbab8acddcac1ac1a290d40a08cb2b8b7a58d448bf816c21f1c641209426",
          "sha1": "068d8bedd8f47f91b3e991099ce5c96cb32fa625",
          "md5": "dce1f1aecc5e57d687fa578f5d6dd681"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "cosantakit-3b49e4c-sources.jar",
          "url": "cosantakit-3b49e4c-sources.jar",
          "size": 284582,
          "sha512": "9d279a0efdba441072f398d19526872752aeb66a7ea5327bff98e94592ae8da2d03adf568241d45f8edd300f630da41826dafce8ebd0fbabd2773ab8ce4ca228",
          "sha256": "885deeaf7a068df62203766bd8bb21d5d4530d5c9b1d65dd91074a68f63d219c",
          "sha1": "701432fb46ececfe8501861ce1cf6342c55798de",
          "md5": "b6b025256654097ff2c1a89fd028aeef"
        }
      ]
    }
  ]
}
