{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "cosantakit",
    "version": "3f0c17e",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "3f0c17e"
          }
        }
      ],
      "files": [
        {
          "name": "cosantakit-3f0c17e.aar",
          "url": "cosantakit-3f0c17e.aar",
          "size": 285980,
          "sha512": "46c623e27ba1d53407b3ad7d4ad279108c8cbd43337f6ac49b67e0857c7fa1b02ebe28666562bec3d66d3ed81fe673e905a3da3176422ed1d0021d78467116b7",
          "sha256": "79cbcbab8acddcac1ac1a290d40a08cb2b8b7a58d448bf816c21f1c641209426",
          "sha1": "068d8bedd8f47f91b3e991099ce5c96cb32fa625",
          "md5": "dce1f1aecc5e57d687fa578f5d6dd681"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "dashlib",
          "version": {
            "requires": "3f0c17e"
          }
        },
        {
          "group": "de.sfuhrm",
          "module": "saphir-hash-jca",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "com.github.all3fox",
          "module": "lyra2",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "3f0c17e"
          }
        }
      ],
      "files": [
        {
          "name": "cosantakit-3f0c17e.aar",
          "url": "cosantakit-3f0c17e.aar",
          "size": 285980,
          "sha512": "46c623e27ba1d53407b3ad7d4ad279108c8cbd43337f6ac49b67e0857c7fa1b02ebe28666562bec3d66d3ed81fe673e905a3da3176422ed1d0021d78467116b7",
          "sha256": "79cbcbab8acddcac1ac1a290d40a08cb2b8b7a58d448bf816c21f1c641209426",
          "sha1": "068d8bedd8f47f91b3e991099ce5c96cb32fa625",
          "md5": "dce1f1aecc5e57d687fa578f5d6dd681"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "cosantakit-3f0c17e-sources.jar",
          "url": "cosantakit-3f0c17e-sources.jar",
          "size": 284582,
          "sha512": "9048b8ca3d0d48cc26bf8919aea006cc5e1f6a38c043826a63aade458529cef8c674fada6098e2913fde7719d4db3472bcc280d373934ddd3d89e2a82f176269",
          "sha256": "997b916ca58ef3a44e45ca09da5d5ca103ca9483a627d2450c177c68dbb40cb9",
          "sha1": "f8583c7e09550a701b26f73eb340e45b414642f5",
          "md5": "474caf1c9d09edff20a76d4065f5e4b0"
        }
      ]
    }
  ]
}
