{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "litecoinkit",
    "version": "5316246",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "5316246"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "hodler",
          "version": {
            "requires": "5316246"
          }
        }
      ],
      "files": [
        {
          "name": "litecoinkit-5316246.aar",
          "url": "litecoinkit-5316246.aar",
          "size": 353360,
          "sha512": "85eeb915152fad53a719afcff0c4eb895ffe6cbeae94ee9ff70a90c52a9f9f02d4d811680780d668d618113de72782ca95ed61b0200813125df2b45c28a6ed6f",
          "sha256": "b03c42acd4f7af24df34029badd273d1b009192b7e697ebbb963f7cbefacfd9a",
          "sha1": "9e0ad7f8ca64707b37057589d12095dfac7d4b52",
          "md5": "f2ab3ad6be330e5e2651be2c78fbf09a"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.github.piratecash",
          "module": "mwebd-android",
          "version": {
            "requires": "v0.1.19-pcash.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "5316246"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "hodler",
          "version": {
            "requires": "5316246"
          }
        }
      ],
      "files": [
        {
          "name": "litecoinkit-5316246.aar",
          "url": "litecoinkit-5316246.aar",
          "size": 353360,
          "sha512": "85eeb915152fad53a719afcff0c4eb895ffe6cbeae94ee9ff70a90c52a9f9f02d4d811680780d668d618113de72782ca95ed61b0200813125df2b45c28a6ed6f",
          "sha256": "b03c42acd4f7af24df34029badd273d1b009192b7e697ebbb963f7cbefacfd9a",
          "sha1": "9e0ad7f8ca64707b37057589d12095dfac7d4b52",
          "md5": "f2ab3ad6be330e5e2651be2c78fbf09a"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "litecoinkit-5316246-sources.jar",
          "url": "litecoinkit-5316246-sources.jar",
          "size": 229920,
          "sha512": "49cefb223ddf8614f5a1f63e7e178f61d8d5f6a363c4322b8923bee5604f1f84b2a8e1c8b2d0907f787fd97691f607994a6c23056f78e632d81bfe1d7aad9e01",
          "sha256": "527c8d8d7b1a656abfde5aeb3e516c4033345fca34a5566275e8286b5fb0f4d5",
          "sha1": "27be4851071ca619e09fda80847c332f3f710307",
          "md5": "3f5dcc51dbd3ed9eb9111329a7b3262f"
        }
      ]
    }
  ]
}
