{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "dashkit",
    "version": "bbf7636",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "bbf7636"
          }
        }
      ],
      "files": [
        {
          "name": "dashkit-bbf7636.aar",
          "url": "dashkit-bbf7636.aar",
          "size": 234438,
          "sha512": "3548f36526f3678a75f94b24494764d1212e6143dcb4462fad92667d924cf1bb7a68e196f878076a24166bad87294b16301639c563372d6362d445140dbe46a1",
          "sha256": "681a629538752a56a57352974aeb7d2aef54ae9f46dd974434f2f98d833a2222",
          "sha1": "1d276bafb7d013ce4134de8c5fc805ca283a46a2",
          "md5": "67cb21313bb77ba8b2473733e6143784"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "dashlib",
          "version": {
            "requires": "bbf7636"
          }
        },
        {
          "group": "de.sfuhrm",
          "module": "saphir-hash-jca",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "bbf7636"
          }
        }
      ],
      "files": [
        {
          "name": "dashkit-bbf7636.aar",
          "url": "dashkit-bbf7636.aar",
          "size": 234438,
          "sha512": "3548f36526f3678a75f94b24494764d1212e6143dcb4462fad92667d924cf1bb7a68e196f878076a24166bad87294b16301639c563372d6362d445140dbe46a1",
          "sha256": "681a629538752a56a57352974aeb7d2aef54ae9f46dd974434f2f98d833a2222",
          "sha1": "1d276bafb7d013ce4134de8c5fc805ca283a46a2",
          "md5": "67cb21313bb77ba8b2473733e6143784"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "dashkit-bbf7636-sources.jar",
          "url": "dashkit-bbf7636-sources.jar",
          "size": 278416,
          "sha512": "5039aa63ed7f7a74eaa3cd52fca500134d7f055f0e299490971711c437b1cfe5ec079be0e2dd33b79036e75d8d64bc77422cdb4ee10f90497b2c8b189aab843b",
          "sha256": "c765c8a8e53881f965258363fdac2e0f0de85d965e20456f783c5c8b732a25e2",
          "sha1": "be4ab0abc03f512384626d7d1203c728efb39876",
          "md5": "399f3cf7ee48a6abef62ac34dad2273a"
        }
      ]
    }
  ]
}
