{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "bitcoincore",
    "version": "ddb3497",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash",
          "module": "hd-wallet-kit-android",
          "version": {
            "requires": "46a441d"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bitcoincore-ddb3497.aar",
          "url": "bitcoincore-ddb3497.aar",
          "size": 1159581,
          "sha512": "3f76745d85248b7d447ab89219750c6fbe5538040af8bbc497d64cf881b6566632cf1a4ec56f22733092bf18f5014ede7ef79c80fdf6cdb39a9af2be9a484c29",
          "sha256": "1c932bc84c373b81d1b1ad61298f7cd060ded228ca9ae80d1438f7080e824aad",
          "sha1": "96c62233766273053e6109c7080a7db90552fa0b",
          "md5": "06b4200a076575f9cdffa1426e87673a"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.5.0"
          }
        },
        {
          "group": "com.github.piratecash",
          "module": "hd-wallet-kit-android",
          "version": {
            "requires": "46a441d"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bitcoincore-ddb3497.aar",
          "url": "bitcoincore-ddb3497.aar",
          "size": 1159581,
          "sha512": "3f76745d85248b7d447ab89219750c6fbe5538040af8bbc497d64cf881b6566632cf1a4ec56f22733092bf18f5014ede7ef79c80fdf6cdb39a9af2be9a484c29",
          "sha256": "1c932bc84c373b81d1b1ad61298f7cd060ded228ca9ae80d1438f7080e824aad",
          "sha1": "96c62233766273053e6109c7080a7db90552fa0b",
          "md5": "06b4200a076575f9cdffa1426e87673a"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "bitcoincore-ddb3497-sources.jar",
          "url": "bitcoincore-ddb3497-sources.jar",
          "size": 1261866,
          "sha512": "931bddce787c3237b29ea4c57008bdc3df53d648bb36742203b25a1bd34411884e36e2f45339870ca0f020978b1e16dd981f3c5a64b3052e44cf29316c42ffea",
          "sha256": "7deb9fb7f9c4f333ef1e594b647f3f08523ecc9ae285aa5b344137e89976b7fc",
          "sha1": "41cd0ce0baaed1416f087c3fae16e30ebabc3981",
          "md5": "4483a03bc9380165fa3000ebbdfbc374"
        }
      ]
    }
  ]
}
