{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "cosantakit",
    "version": "407858a",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "407858a"
          }
        }
      ],
      "files": [
        {
          "name": "cosantakit-407858a.aar",
          "url": "cosantakit-407858a.aar",
          "size": 286096,
          "sha512": "18b64dc8a7c06d02559d4e1215fb4864c0dea5f34b06acd21ff00c967e0a409e3f94c3fcc8d8190170a0865907376909b5d76c690aaa7ed56bc6b4d7ab13416a",
          "sha256": "4f401890dca7e548bb555657d35eecd16d48c3f395d2356a54a8b59f1128aa05",
          "sha1": "f16ce50665f414f7e08bc932acca23ff8e30abb6",
          "md5": "e46bf82d1236aecabbf89a67b9037004"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "dashlib",
          "version": {
            "requires": "407858a"
          }
        },
        {
          "group": "de.sfuhrm",
          "module": "saphir-hash-jca",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "com.github.all3fox",
          "module": "lyra2",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "407858a"
          }
        }
      ],
      "files": [
        {
          "name": "cosantakit-407858a.aar",
          "url": "cosantakit-407858a.aar",
          "size": 286096,
          "sha512": "18b64dc8a7c06d02559d4e1215fb4864c0dea5f34b06acd21ff00c967e0a409e3f94c3fcc8d8190170a0865907376909b5d76c690aaa7ed56bc6b4d7ab13416a",
          "sha256": "4f401890dca7e548bb555657d35eecd16d48c3f395d2356a54a8b59f1128aa05",
          "sha1": "f16ce50665f414f7e08bc932acca23ff8e30abb6",
          "md5": "e46bf82d1236aecabbf89a67b9037004"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "cosantakit-407858a-sources.jar",
          "url": "cosantakit-407858a-sources.jar",
          "size": 284582,
          "sha512": "79cc9c2b0c01772b124ae9ce0d4e3124703b4756f4141822db67141977d1e7393225842725c9bef174a74f1a952113cd9290b7321de229bd8eda38816b39972b",
          "sha256": "8f47d180b19dfe7f0a14b956a06776ca206637b3ce7d852358f00de579ce0039",
          "sha1": "a0a830ba18e99ff2bd2273261eaa45b2b989d84a",
          "md5": "2fd7f15be2d7afcf0ae8b93053e678b9"
        }
      ]
    }
  ]
}
