{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "piratecashkit",
    "version": "acddeb9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "acddeb9"
          }
        }
      ],
      "files": [
        {
          "name": "piratecashkit-acddeb9.aar",
          "url": "piratecashkit-acddeb9.aar",
          "size": 290650,
          "sha512": "59ecadceb573beb250f7294b84597c39d9a5122d8129eb139e59371040ead5cc0ed885432c64927197046af7a416f9688bcbcc1dfd0a7b912426f82f2621e9e5",
          "sha256": "b06043fcb15c856926297b776a5cea968ecc864fa7e352007327fd4df96e7247",
          "sha1": "7399d61911d10fc64f56d05a66be0bd567d37060",
          "md5": "67389235057d91626ae17a3ed6f50cdb"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "dashlib",
          "version": {
            "requires": "acddeb9"
          }
        },
        {
          "group": "de.sfuhrm",
          "module": "saphir-hash-jca",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "com.github.all3fox",
          "module": "lyra2",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "acddeb9"
          }
        }
      ],
      "files": [
        {
          "name": "piratecashkit-acddeb9.aar",
          "url": "piratecashkit-acddeb9.aar",
          "size": 290650,
          "sha512": "59ecadceb573beb250f7294b84597c39d9a5122d8129eb139e59371040ead5cc0ed885432c64927197046af7a416f9688bcbcc1dfd0a7b912426f82f2621e9e5",
          "sha256": "b06043fcb15c856926297b776a5cea968ecc864fa7e352007327fd4df96e7247",
          "sha1": "7399d61911d10fc64f56d05a66be0bd567d37060",
          "md5": "67389235057d91626ae17a3ed6f50cdb"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "piratecashkit-acddeb9-sources.jar",
          "url": "piratecashkit-acddeb9-sources.jar",
          "size": 289464,
          "sha512": "fffd9054e8b29bf95fbe78c07f7f4a4f5aaae4ccb184180105c0ffde916585f597dd9a4aa65176ea617f7db00c98d0e03b01c2cc5a504a55544b71d148582e3b",
          "sha256": "621e9af0aa455ca983e71d2273ec8be9261a2d4cdc184a80579c649f61bf3bac",
          "sha1": "364b04a29961b34b4d361d26b7fcff8947c4400e",
          "md5": "a5c50861538e975d4683ee04db639ec2"
        }
      ]
    }
  ]
}
