{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "cosantakit",
    "version": "ab92f0f",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "ab92f0f"
          }
        }
      ],
      "files": [
        {
          "name": "cosantakit-ab92f0f.aar",
          "url": "cosantakit-ab92f0f.aar",
          "size": 286139,
          "sha512": "e0f53c2a8e094d529877bf5c53e938c71d28a228ea3027d747a6f30e49ce99cfbdfec0e53151e33d50cf51de8f98d1a804f19e6addfb7c5509982594bffc0766",
          "sha256": "e062e300242b68b31613222c1c3331d088104fbb5b3df2fd02b58897666be247",
          "sha1": "5a480e0c9de6fce550a376960faec4486207e863",
          "md5": "8c195f24e4c0bd83bbf09f6683909a58"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "dashlib",
          "version": {
            "requires": "ab92f0f"
          }
        },
        {
          "group": "de.sfuhrm",
          "module": "saphir-hash-jca",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "com.github.all3fox",
          "module": "lyra2",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "ab92f0f"
          }
        }
      ],
      "files": [
        {
          "name": "cosantakit-ab92f0f.aar",
          "url": "cosantakit-ab92f0f.aar",
          "size": 286139,
          "sha512": "e0f53c2a8e094d529877bf5c53e938c71d28a228ea3027d747a6f30e49ce99cfbdfec0e53151e33d50cf51de8f98d1a804f19e6addfb7c5509982594bffc0766",
          "sha256": "e062e300242b68b31613222c1c3331d088104fbb5b3df2fd02b58897666be247",
          "sha1": "5a480e0c9de6fce550a376960faec4486207e863",
          "md5": "8c195f24e4c0bd83bbf09f6683909a58"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "cosantakit-ab92f0f-sources.jar",
          "url": "cosantakit-ab92f0f-sources.jar",
          "size": 287782,
          "sha512": "cbf27d5609b2dd1496016cf3662574a6f47a55072653629b744a0d68c39f75cdd5449af27bad2752c2721806bb2eef312c79832966253db6a07b6b72cbbab260",
          "sha256": "00696196d350654d4b760d15405a35da185577de8a8d68b27ddf946d646426dd",
          "sha1": "b16f28c2d8466c42d08f03f3b0b0a1b0e27aef9f",
          "md5": "d0db80fc1dbf186f253103304faad328"
        }
      ]
    }
  ]
}
