{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "piratecashkit",
    "version": "v0.1.0-pcash.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "v0.1.0-pcash.23"
          }
        }
      ],
      "files": [
        {
          "name": "piratecashkit-v0.1.0-pcash.23.aar",
          "url": "piratecashkit-v0.1.0-pcash.23.aar",
          "size": 291133,
          "sha512": "8435b12c893c522c24954def6bfe81c39a1d652f1d22b75dff1dec0b8beb9a9bdf945f25650080ff4f6f75f387b1b537719c19146520ddccd48867675c148e48",
          "sha256": "4e9536848313eca8adab296a5cc440752cf6188d993a562b01d4b6fac23d13a9",
          "sha1": "ce834ab953da647f4d17948fe7258a6709384ff8",
          "md5": "2d39453293c3698adcef25fce49d07aa"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "dashlib",
          "version": {
            "requires": "v0.1.0-pcash.23"
          }
        },
        {
          "group": "de.sfuhrm",
          "module": "saphir-hash-jca",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "com.github.all3fox",
          "module": "lyra2",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "v0.1.0-pcash.23"
          }
        }
      ],
      "files": [
        {
          "name": "piratecashkit-v0.1.0-pcash.23.aar",
          "url": "piratecashkit-v0.1.0-pcash.23.aar",
          "size": 291133,
          "sha512": "8435b12c893c522c24954def6bfe81c39a1d652f1d22b75dff1dec0b8beb9a9bdf945f25650080ff4f6f75f387b1b537719c19146520ddccd48867675c148e48",
          "sha256": "4e9536848313eca8adab296a5cc440752cf6188d993a562b01d4b6fac23d13a9",
          "sha1": "ce834ab953da647f4d17948fe7258a6709384ff8",
          "md5": "2d39453293c3698adcef25fce49d07aa"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "piratecashkit-v0.1.0-pcash.23-sources.jar",
          "url": "piratecashkit-v0.1.0-pcash.23-sources.jar",
          "size": 292144,
          "sha512": "c1e50688de7d0a84f8d9547c51cec58a0cef6237125926786fb8f16386022b813ccb64cf932cc43cd54829f460833dfce019b261e826f4447963b38444dd6ea5",
          "sha256": "11b08d6ec121755a256276a17573888588ccaa2c0bc4da3f460ad54bb18b8f41",
          "sha1": "472f3ec8ead8c180d85525b5a46f23733e9eed9a",
          "md5": "838d0825d47478c4239ecc07ee910529"
        }
      ]
    }
  ]
}
