{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "bitcoincore",
    "version": "3cf21db",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash",
          "module": "hd-wallet-kit-android",
          "version": {
            "requires": "46a441d"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bitcoincore-3cf21db.aar",
          "url": "bitcoincore-3cf21db.aar",
          "size": 1143945,
          "sha512": "ba5ce1cb9d90d9d1866e39b160c2ecf575569a0b184d0c3309fd7a6ee7584bfc28eb5db4ff8120fcb61df875351921fd76b2050e874a184371a9ee03deb1b0b0",
          "sha256": "207bfb2e6b33de37bfc47c15c787027facf1eac8525d4eaf0fd6798bbd1fbc00",
          "sha1": "33ae3c48efc52f5c8a4b60507dbbb097bee38828",
          "md5": "3427fd4bbbbe4801e7065d31eeb3320a"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.5.0"
          }
        },
        {
          "group": "com.github.piratecash",
          "module": "hd-wallet-kit-android",
          "version": {
            "requires": "46a441d"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bitcoincore-3cf21db.aar",
          "url": "bitcoincore-3cf21db.aar",
          "size": 1143945,
          "sha512": "ba5ce1cb9d90d9d1866e39b160c2ecf575569a0b184d0c3309fd7a6ee7584bfc28eb5db4ff8120fcb61df875351921fd76b2050e874a184371a9ee03deb1b0b0",
          "sha256": "207bfb2e6b33de37bfc47c15c787027facf1eac8525d4eaf0fd6798bbd1fbc00",
          "sha1": "33ae3c48efc52f5c8a4b60507dbbb097bee38828",
          "md5": "3427fd4bbbbe4801e7065d31eeb3320a"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "bitcoincore-3cf21db-sources.jar",
          "url": "bitcoincore-3cf21db-sources.jar",
          "size": 1249320,
          "sha512": "3c3f0b0ab3456c1a3d54c74eb32ad9997b7884b39bd8085fe576f97fe10c32a15166cd6954785d8ef2409765ca89c34bf0ba74f4726c2f5ca61b3f83a781debf",
          "sha256": "fc9378b4f9cee8b080a89bba25d216ecbf0d8e9e143435b662812f4d227dc3c8",
          "sha1": "e51d9cafd04e2540c720d92258f9e0faf99a3cce",
          "md5": "406b436a37b6df5a9f7621afad091dd0"
        }
      ]
    }
  ]
}
