{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "litecoinkit",
    "version": "v0.1.0-pcash.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "v0.1.0-pcash.22"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "hodler",
          "version": {
            "requires": "v0.1.0-pcash.22"
          }
        }
      ],
      "files": [
        {
          "name": "litecoinkit-v0.1.0-pcash.22.aar",
          "url": "litecoinkit-v0.1.0-pcash.22.aar",
          "size": 595668,
          "sha512": "20982d00ec0ec57199ff096acbce7afcb0516973649248da5c48751617f4582261af53b77b517836dc57a41670eb60ad0ba47c9b8bfdd9eef9bd7b56d0e8e745",
          "sha256": "fdc87ca582f1dd8d5a24383066245fbe6e9446e83af399ae0669a4d26644b284",
          "sha1": "c9cf7edaaf3f7c0d733dc76fb0d51dcc1054cbfc",
          "md5": "9b81654fdbb9a862471ad89983630125"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.github.piratecash",
          "module": "mwebd-android",
          "version": {
            "requires": "v0.1.19-pcash.9"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "v0.1.0-pcash.22"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "hodler",
          "version": {
            "requires": "v0.1.0-pcash.22"
          }
        }
      ],
      "files": [
        {
          "name": "litecoinkit-v0.1.0-pcash.22.aar",
          "url": "litecoinkit-v0.1.0-pcash.22.aar",
          "size": 595668,
          "sha512": "20982d00ec0ec57199ff096acbce7afcb0516973649248da5c48751617f4582261af53b77b517836dc57a41670eb60ad0ba47c9b8bfdd9eef9bd7b56d0e8e745",
          "sha256": "fdc87ca582f1dd8d5a24383066245fbe6e9446e83af399ae0669a4d26644b284",
          "sha1": "c9cf7edaaf3f7c0d733dc76fb0d51dcc1054cbfc",
          "md5": "9b81654fdbb9a862471ad89983630125"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "litecoinkit-v0.1.0-pcash.22-sources.jar",
          "url": "litecoinkit-v0.1.0-pcash.22-sources.jar",
          "size": 300480,
          "sha512": "50f1d139000dadd59feff61698596bcb83e45811e7fbef1a417a5bf078ee44a983e1d564b1718f000faee52fbb52f1e4c947ab5a9d89c08ffc1db3d2c80dad8e",
          "sha256": "acddb83204e67912588eba0160af8e804457ff90ee6ece90b9325ff582b718cb",
          "sha1": "841d4db2d421def71b86dda478a2c097d6647b5f",
          "md5": "7bcb60c9ba96e67900c47a9bddfcee65"
        }
      ]
    }
  ]
}
