{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "piratecashkit",
    "version": "92eee50",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "92eee50"
          }
        }
      ],
      "files": [
        {
          "name": "piratecashkit-92eee50.aar",
          "url": "piratecashkit-92eee50.aar",
          "size": 290870,
          "sha512": "406d7fd489595b34712fef98270c080032016b7006cad601907898a85090d06c2dc4cd41ab9b4eefacbf8b909ee6e60b25e1655e5b9e360e3a457b2e853812da",
          "sha256": "ebebb9900f966177b3dbcbb89f3ab69d4720a0b4eb236d0791ac1bc265947b50",
          "sha1": "c124b6647f7ebc48041e62febbe90efe4322c6cc",
          "md5": "2c62e376d5c7cdd37eb018d7e715d7eb"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "dashlib",
          "version": {
            "requires": "92eee50"
          }
        },
        {
          "group": "de.sfuhrm",
          "module": "saphir-hash-jca",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "com.github.all3fox",
          "module": "lyra2",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "92eee50"
          }
        }
      ],
      "files": [
        {
          "name": "piratecashkit-92eee50.aar",
          "url": "piratecashkit-92eee50.aar",
          "size": 290870,
          "sha512": "406d7fd489595b34712fef98270c080032016b7006cad601907898a85090d06c2dc4cd41ab9b4eefacbf8b909ee6e60b25e1655e5b9e360e3a457b2e853812da",
          "sha256": "ebebb9900f966177b3dbcbb89f3ab69d4720a0b4eb236d0791ac1bc265947b50",
          "sha1": "c124b6647f7ebc48041e62febbe90efe4322c6cc",
          "md5": "2c62e376d5c7cdd37eb018d7e715d7eb"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "piratecashkit-92eee50-sources.jar",
          "url": "piratecashkit-92eee50-sources.jar",
          "size": 291839,
          "sha512": "960776925033d5565cbec7a22f772df69b0be526b0d693238cfd3a23bab77d0cfd4297cd35ae89e0053d07008a3fe5308d84ab2e6a5e54230c1e7a60c3fa6e25",
          "sha256": "1bffcba67d08bf2cd37c2c31b0f6ad7f302195b0ace7b185f6f78b655e0c732d",
          "sha1": "c0f454fd9646e074cb3650866b1ba8302ec41b23",
          "md5": "5075ca02cd34f27d2b7193e535a5b661"
        }
      ]
    }
  ]
}
