{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "bitcoincore",
    "version": "a49d6b8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash",
          "module": "hd-wallet-kit-android",
          "version": {
            "requires": "46a441d"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bitcoincore-a49d6b8.aar",
          "url": "bitcoincore-a49d6b8.aar",
          "size": 1256449,
          "sha512": "3812770c16a693f6b28a4a6edaf19d87a6575e9f7854fd41723856e4da93d84c20011a0da23b69c33d9fab5cf45d3e33c7642a424bc38fd63a4f47147572b7aa",
          "sha256": "288b0ae8dacbeec7d9a6e0d51f3a3498e544950b3decd7ba08fd10cee646b53c",
          "sha1": "80deb5cdcb33bbe8fcd867f464fdc52e77a383bc",
          "md5": "c4fa9b56c69b7e350f28c586eddb3dbb"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.5.0"
          }
        },
        {
          "group": "com.github.piratecash",
          "module": "hd-wallet-kit-android",
          "version": {
            "requires": "46a441d"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bitcoincore-a49d6b8.aar",
          "url": "bitcoincore-a49d6b8.aar",
          "size": 1256449,
          "sha512": "3812770c16a693f6b28a4a6edaf19d87a6575e9f7854fd41723856e4da93d84c20011a0da23b69c33d9fab5cf45d3e33c7642a424bc38fd63a4f47147572b7aa",
          "sha256": "288b0ae8dacbeec7d9a6e0d51f3a3498e544950b3decd7ba08fd10cee646b53c",
          "sha1": "80deb5cdcb33bbe8fcd867f464fdc52e77a383bc",
          "md5": "c4fa9b56c69b7e350f28c586eddb3dbb"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "bitcoincore-a49d6b8-sources.jar",
          "url": "bitcoincore-a49d6b8-sources.jar",
          "size": 1465902,
          "sha512": "821e911e723bb1f88ece8b57c2faee4002f4e7f7f30b5a444139567ef40f42a3c1c430e29b3cef11e0500e19a2e5253846983beff2b88a6ba20683c219c8b77f",
          "sha256": "e6088512269d32c27c0b5c385cad98340b6f35dc1501f307ba8f1666a605aec1",
          "sha1": "0132bb2b0cfc3575aae987ca163b14b4969859b4",
          "md5": "1e0273987440cb3249c7e2c5588581d6"
        }
      ]
    }
  ]
}
