{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "bitcoincore",
    "version": "a49d6b8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash",
          "module": "hd-wallet-kit-android",
          "version": {
            "requires": "46a441d"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bitcoincore-a49d6b8.aar",
          "url": "bitcoincore-a49d6b8.aar",
          "size": 1256449,
          "sha512": "3812770c16a693f6b28a4a6edaf19d87a6575e9f7854fd41723856e4da93d84c20011a0da23b69c33d9fab5cf45d3e33c7642a424bc38fd63a4f47147572b7aa",
          "sha256": "288b0ae8dacbeec7d9a6e0d51f3a3498e544950b3decd7ba08fd10cee646b53c",
          "sha1": "80deb5cdcb33bbe8fcd867f464fdc52e77a383bc",
          "md5": "c4fa9b56c69b7e350f28c586eddb3dbb"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.5.0"
          }
        },
        {
          "group": "com.github.piratecash",
          "module": "hd-wallet-kit-android",
          "version": {
            "requires": "46a441d"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bitcoincore-a49d6b8.aar",
          "url": "bitcoincore-a49d6b8.aar",
          "size": 1256449,
          "sha512": "3812770c16a693f6b28a4a6edaf19d87a6575e9f7854fd41723856e4da93d84c20011a0da23b69c33d9fab5cf45d3e33c7642a424bc38fd63a4f47147572b7aa",
          "sha256": "288b0ae8dacbeec7d9a6e0d51f3a3498e544950b3decd7ba08fd10cee646b53c",
          "sha1": "80deb5cdcb33bbe8fcd867f464fdc52e77a383bc",
          "md5": "c4fa9b56c69b7e350f28c586eddb3dbb"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "bitcoincore-a49d6b8-sources.jar",
          "url": "bitcoincore-a49d6b8-sources.jar",
          "size": 1465902,
          "sha512": "223015a8f311cb676aea59a388ebd46c328aad08dd800da74a189d98ab2fc7666cc2467900eafd2ae9792622405c9905c78e5bb5df899c6b2afb3b262961cb37",
          "sha256": "b59b07c51617eece6b04979d10c00ff24f24f0ec51b8c436b8ffa46de5d635c2",
          "sha1": "602f2256b2e2e0108d37a076be7ba6ca0bfdc887",
          "md5": "6a0409a4206e9c004d54e6aa25b243c2"
        }
      ]
    }
  ]
}
