{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "piratecashkit",
    "version": "3f0c17e",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "3f0c17e"
          }
        }
      ],
      "files": [
        {
          "name": "piratecashkit-3f0c17e.aar",
          "url": "piratecashkit-3f0c17e.aar",
          "size": 290507,
          "sha512": "ebce1effb9980762d4da0dd52ae54ff32c439c4cc16ac5b9602a48a9403a46097f0c46f17b0d1c9297be9a98b255ce08574e75ddb1fe0c4494da3039f67e842d",
          "sha256": "1ec90275d42d211850a10a0fc0f95b40976e8680edd439296219132530455619",
          "sha1": "31531561b665b3b8793ccada11f343804178df89",
          "md5": "aa9742d89f35704c184380e8da7fc5da"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "dashlib",
          "version": {
            "requires": "3f0c17e"
          }
        },
        {
          "group": "de.sfuhrm",
          "module": "saphir-hash-jca",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "com.github.all3fox",
          "module": "lyra2",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "3f0c17e"
          }
        }
      ],
      "files": [
        {
          "name": "piratecashkit-3f0c17e.aar",
          "url": "piratecashkit-3f0c17e.aar",
          "size": 290507,
          "sha512": "ebce1effb9980762d4da0dd52ae54ff32c439c4cc16ac5b9602a48a9403a46097f0c46f17b0d1c9297be9a98b255ce08574e75ddb1fe0c4494da3039f67e842d",
          "sha256": "1ec90275d42d211850a10a0fc0f95b40976e8680edd439296219132530455619",
          "sha1": "31531561b665b3b8793ccada11f343804178df89",
          "md5": "aa9742d89f35704c184380e8da7fc5da"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "piratecashkit-3f0c17e-sources.jar",
          "url": "piratecashkit-3f0c17e-sources.jar",
          "size": 289469,
          "sha512": "b98064e07496f8d71b8368a61375cbb7b1ec9cf2c70031e9905f050184d66361e7c3bbb065f3e0753f381fbe1f961a31be79f747f57bf340ab5835e229910001",
          "sha256": "e71edbf6979af9986323659382c78b54aac6415c30f3e74324610cbb79ce07a6",
          "sha1": "95e6394ec5ff4abc05c05303b819541ceb9c5c96",
          "md5": "340e5f7d5f102aac489ea59ba5e06bb3"
        }
      ]
    }
  ]
}
