{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "piratecashkit",
    "version": "2444c01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "2444c01"
          }
        }
      ],
      "files": [
        {
          "name": "piratecashkit-2444c01.aar",
          "url": "piratecashkit-2444c01.aar",
          "size": 290696,
          "sha512": "4e59a6dc9e7376b767453dfb2ceb7e72d7a8768be3ddc3c1bd9779a6126ed27b5fffb58610cd2825782ef3ed5263cbb31d10fd58148976c3644ab29f9fcd9ab2",
          "sha256": "9ee6701ac301cb380d10991fd9db501e063eeba5f1ca1d924b73b9561e4a840e",
          "sha1": "527008c7bc40bf212463c888baeba4df01e907fe",
          "md5": "8af7ed5473f3743c764d38ee03ad4b88"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "dashlib",
          "version": {
            "requires": "2444c01"
          }
        },
        {
          "group": "de.sfuhrm",
          "module": "saphir-hash-jca",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "com.github.all3fox",
          "module": "lyra2",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "2444c01"
          }
        }
      ],
      "files": [
        {
          "name": "piratecashkit-2444c01.aar",
          "url": "piratecashkit-2444c01.aar",
          "size": 290696,
          "sha512": "4e59a6dc9e7376b767453dfb2ceb7e72d7a8768be3ddc3c1bd9779a6126ed27b5fffb58610cd2825782ef3ed5263cbb31d10fd58148976c3644ab29f9fcd9ab2",
          "sha256": "9ee6701ac301cb380d10991fd9db501e063eeba5f1ca1d924b73b9561e4a840e",
          "sha1": "527008c7bc40bf212463c888baeba4df01e907fe",
          "md5": "8af7ed5473f3743c764d38ee03ad4b88"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "piratecashkit-2444c01-sources.jar",
          "url": "piratecashkit-2444c01-sources.jar",
          "size": 291529,
          "sha512": "41a3da6a0ea9b4cfac76aea61167b30402c292af6903af7d0efb8f469fb66ea5357cc0fa2013d9b4b02fb530b5d74d009a4922d559b7edc6844b077c92a28e0b",
          "sha256": "447ade7a838f7b7c2f453e20f79b3896fa4f36e21d701f6f871d27970ff99697",
          "sha1": "a822496241bc9230bb8d08cd495cd3dcb321b597",
          "md5": "6d0374fd9620cc2ea6674ff6133237c7"
        }
      ]
    }
  ]
}
