{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "bitcoincore",
    "version": "2e7cc5d",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash",
          "module": "hd-wallet-kit-android",
          "version": {
            "requires": "46a441d"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bitcoincore-2e7cc5d.aar",
          "url": "bitcoincore-2e7cc5d.aar",
          "size": 1087122,
          "sha512": "8b34aa3ca3e1bf0fce2b9b2bfffad4534645be34043e59560f4fb85c995a9b158985112287e93a9209d98b35602819e089a601dcee2ca76d9895eae681fd0154",
          "sha256": "b65c8835788e0a05fc742e37e3d325ff838161f82640b5a52fafba872be3cb18",
          "sha1": "51c06f2427437a624777a1384c5502fe66f1f4e9",
          "md5": "445c8df528ade5be0426244cf85ddbc4"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.5.0"
          }
        },
        {
          "group": "com.github.piratecash",
          "module": "hd-wallet-kit-android",
          "version": {
            "requires": "46a441d"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bitcoincore-2e7cc5d.aar",
          "url": "bitcoincore-2e7cc5d.aar",
          "size": 1087122,
          "sha512": "8b34aa3ca3e1bf0fce2b9b2bfffad4534645be34043e59560f4fb85c995a9b158985112287e93a9209d98b35602819e089a601dcee2ca76d9895eae681fd0154",
          "sha256": "b65c8835788e0a05fc742e37e3d325ff838161f82640b5a52fafba872be3cb18",
          "sha1": "51c06f2427437a624777a1384c5502fe66f1f4e9",
          "md5": "445c8df528ade5be0426244cf85ddbc4"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "bitcoincore-2e7cc5d-sources.jar",
          "url": "bitcoincore-2e7cc5d-sources.jar",
          "size": 1175185,
          "sha512": "bfb2a8ad2f95f5f21b292b58aed9360549b023e4615d0f753508c2c25be0eebafed129cb353664bacd9fa4644e6b2818f907722796637a0f533a3adbcca7ee29",
          "sha256": "ba8fff5713a73e0404ef6455a30cf5a7835e3dac9f7b3ee0433796fdcc1d8444",
          "sha1": "52f82b1339a7af54f3391c3eafc9a42590ac7ec2",
          "md5": "e10726da3984775e12dfbc33a725a22c"
        }
      ]
    }
  ]
}
