{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "cosantakit",
    "version": "fadfbf9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "fadfbf9"
          }
        }
      ],
      "files": [
        {
          "name": "cosantakit-fadfbf9.aar",
          "url": "cosantakit-fadfbf9.aar",
          "size": 286053,
          "sha512": "3ebaea80293c49df9aef190c4bab5c55945a77cc1c2dfd896d37393605e46b1fae5fe3632123615341d70a5445baa2aacdee7a89de6713af52572f3d65f6a6e8",
          "sha256": "583bf6c6be1c831d41a2cd01cd846944e1a06570d18a5b99b1afa93e0fe6dcf5",
          "sha1": "e792d2c007923d096caf1270b4eeaffc09152f10",
          "md5": "df2465ee2bd9f94bcf0109088370524e"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "dashlib",
          "version": {
            "requires": "fadfbf9"
          }
        },
        {
          "group": "de.sfuhrm",
          "module": "saphir-hash-jca",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "com.github.all3fox",
          "module": "lyra2",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "fadfbf9"
          }
        }
      ],
      "files": [
        {
          "name": "cosantakit-fadfbf9.aar",
          "url": "cosantakit-fadfbf9.aar",
          "size": 286053,
          "sha512": "3ebaea80293c49df9aef190c4bab5c55945a77cc1c2dfd896d37393605e46b1fae5fe3632123615341d70a5445baa2aacdee7a89de6713af52572f3d65f6a6e8",
          "sha256": "583bf6c6be1c831d41a2cd01cd846944e1a06570d18a5b99b1afa93e0fe6dcf5",
          "sha1": "e792d2c007923d096caf1270b4eeaffc09152f10",
          "md5": "df2465ee2bd9f94bcf0109088370524e"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "cosantakit-fadfbf9-sources.jar",
          "url": "cosantakit-fadfbf9-sources.jar",
          "size": 284582,
          "sha512": "e76b9f4cac1f4111686f2965aaa7fde5534f3916f7f3e8d076929f2b1ed30fed12775ce38c1dfd041696a1fc206f31c0a48122551514734d59f4e983af28c3fa",
          "sha256": "b1272e9cf73fb64fcd2cf4b33f11c1ba60296e670a0c6a75b43be104112e9343",
          "sha1": "efd86d907ef563600f5ecf50a5a6681fea9efb88",
          "md5": "1addbc306ad51a2ddfc32b276481c753"
        }
      ]
    }
  ]
}
