{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "bitcoincore",
    "version": "bbf7636",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash",
          "module": "hd-wallet-kit-android",
          "version": {
            "requires": "46a441d"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bitcoincore-bbf7636.aar",
          "url": "bitcoincore-bbf7636.aar",
          "size": 1174685,
          "sha512": "54994a858a07a37295f77cb09dfd3f2090dcd25d28dceba20c7b7a12add10b9a489f3ddc6a18a2625cc72b0176d48cb8a75c26176a1b00db0c20174654e148a7",
          "sha256": "c263549770e823e6fd5b33735658f15928e5618546dd2409c41043370161669a",
          "sha1": "776ee8919f242e4a958b8ad3af6533796fbf06d5",
          "md5": "ce7c5cd432e51a4c509ab59d46add39f"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.5.0"
          }
        },
        {
          "group": "com.github.piratecash",
          "module": "hd-wallet-kit-android",
          "version": {
            "requires": "46a441d"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bitcoincore-bbf7636.aar",
          "url": "bitcoincore-bbf7636.aar",
          "size": 1174685,
          "sha512": "54994a858a07a37295f77cb09dfd3f2090dcd25d28dceba20c7b7a12add10b9a489f3ddc6a18a2625cc72b0176d48cb8a75c26176a1b00db0c20174654e148a7",
          "sha256": "c263549770e823e6fd5b33735658f15928e5618546dd2409c41043370161669a",
          "sha1": "776ee8919f242e4a958b8ad3af6533796fbf06d5",
          "md5": "ce7c5cd432e51a4c509ab59d46add39f"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "bitcoincore-bbf7636-sources.jar",
          "url": "bitcoincore-bbf7636-sources.jar",
          "size": 1291406,
          "sha512": "d8056ad1414fd1e1316e9af50663ce6069a13285d2e6ff1a7c499efc1745ffe12c6bc8a8f7d75b0367acfe2ec7b79148069c12497e1fe7efbac7badab7eb7d90",
          "sha256": "e72708a6f6646562112856cbef1e78e87e7c5dba1238acdaa27c2ed39b9c3a81",
          "sha1": "6753040a1c0901f3597a10d08f4d290ea234d651",
          "md5": "6f29416fb28b5ab624ab112460a1e2b5"
        }
      ]
    }
  ]
}
