{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "cosantakit",
    "version": "872cfbd",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "872cfbd"
          }
        }
      ],
      "files": [
        {
          "name": "cosantakit-872cfbd.aar",
          "url": "cosantakit-872cfbd.aar",
          "size": 286053,
          "sha512": "11637f30a00c963a9c07c2e2684171c25366b943ff593cdf52c9b62b9c9ed80a134de0c14822b323814c9431427cc9ecfa1c9315786bdfade412912b9afaa753",
          "sha256": "d002518a3232688f3878eab167f2e000f2982b9c9075017530cff75f05dfffbe",
          "sha1": "efbb66624e87c544766a93e18e3334c6f1ec86f8",
          "md5": "c9ecd571441a5d131094cb0bf9c83702"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "dashlib",
          "version": {
            "requires": "872cfbd"
          }
        },
        {
          "group": "de.sfuhrm",
          "module": "saphir-hash-jca",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "com.github.all3fox",
          "module": "lyra2",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "872cfbd"
          }
        }
      ],
      "files": [
        {
          "name": "cosantakit-872cfbd.aar",
          "url": "cosantakit-872cfbd.aar",
          "size": 286053,
          "sha512": "11637f30a00c963a9c07c2e2684171c25366b943ff593cdf52c9b62b9c9ed80a134de0c14822b323814c9431427cc9ecfa1c9315786bdfade412912b9afaa753",
          "sha256": "d002518a3232688f3878eab167f2e000f2982b9c9075017530cff75f05dfffbe",
          "sha1": "efbb66624e87c544766a93e18e3334c6f1ec86f8",
          "md5": "c9ecd571441a5d131094cb0bf9c83702"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "cosantakit-872cfbd-sources.jar",
          "url": "cosantakit-872cfbd-sources.jar",
          "size": 284577,
          "sha512": "ba0f9d93c7556e143c7b1d14f406053a0f93cc5fa2a49b29c5c0bbfeba5de54ac34f69ec059fb0065a72d2a99350b4ed1a4d9088eb14c8982756cc79de84e2df",
          "sha256": "5df672ab37507060d2ec30bfa13774ed8a3cf4f936ccccc1d1a96d138ed9c27e",
          "sha1": "ba0433e539a861ebb143d546e4950e52c978e125",
          "md5": "e11f9a608fb2abc57ccab23640c95b43"
        }
      ]
    }
  ]
}
