{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "bitcoincore",
    "version": "v0.1.0-pcash.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash",
          "module": "hd-wallet-kit-android",
          "version": {
            "requires": "46a441d"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bitcoincore-v0.1.0-pcash.11.aar",
          "url": "bitcoincore-v0.1.0-pcash.11.aar",
          "size": 1133428,
          "sha512": "acb7651ca4fbade958dfb76835597ab739876eb4657f824e787ce66add2297b31e23900be4ea497b1932d69c74e16bd7e34243b9933fdb752c2a442d5e4832df",
          "sha256": "1f0af83c9effc0b5e670161a631f9190be34c219f79cf77dd9b14e4e5197f734",
          "sha1": "ca0e9fba477f820f820b56eb8cb9f89dd33c6855",
          "md5": "5414ec228083a851ada410b8f0b3054b"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.5.0"
          }
        },
        {
          "group": "com.github.piratecash",
          "module": "hd-wallet-kit-android",
          "version": {
            "requires": "46a441d"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bitcoincore-v0.1.0-pcash.11.aar",
          "url": "bitcoincore-v0.1.0-pcash.11.aar",
          "size": 1133428,
          "sha512": "acb7651ca4fbade958dfb76835597ab739876eb4657f824e787ce66add2297b31e23900be4ea497b1932d69c74e16bd7e34243b9933fdb752c2a442d5e4832df",
          "sha256": "1f0af83c9effc0b5e670161a631f9190be34c219f79cf77dd9b14e4e5197f734",
          "sha1": "ca0e9fba477f820f820b56eb8cb9f89dd33c6855",
          "md5": "5414ec228083a851ada410b8f0b3054b"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "bitcoincore-v0.1.0-pcash.11-sources.jar",
          "url": "bitcoincore-v0.1.0-pcash.11-sources.jar",
          "size": 1236592,
          "sha512": "43e8648bbe1c7ba1ea16491f5e657ecae534065d2da5efd2b494569d7594c6c920cac37fef679fcf391586d6508bccbbd1f7b8a821c114ca3f018b562406a9cc",
          "sha256": "43308eb662e98535fd4d60e3a28eb6bcdb2143614fa699b0ea3f0d098b0fae83",
          "sha1": "eff0105ffe6a4fad254640e8829e2a36a82afd58",
          "md5": "383308aaeab89637f689c7da4576a746"
        }
      ]
    }
  ]
}
