{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "cosantakit",
    "version": "v0.1.0-pcash.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "v0.1.0-pcash.10"
          }
        }
      ],
      "files": [
        {
          "name": "cosantakit-v0.1.0-pcash.10.aar",
          "url": "cosantakit-v0.1.0-pcash.10.aar",
          "size": 286119,
          "sha512": "5821749956cecbea7646275026f911fc7b7f04de096501e76d81b8988be3174d05773d016669a8e454dd95ce667e7e62da1cc66fda7b36a1e138d208cfab1269",
          "sha256": "49781c961aac252f9e2fd3489a1beff908f5799f568e2f8d35c055930546d331",
          "sha1": "d2e899aa08542625bf14acece27b41d9e1a8dcf9",
          "md5": "3c99c4b9bc93dc5c82c1b401a7074fc4"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "dashlib",
          "version": {
            "requires": "v0.1.0-pcash.10"
          }
        },
        {
          "group": "de.sfuhrm",
          "module": "saphir-hash-jca",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "com.github.all3fox",
          "module": "lyra2",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "v0.1.0-pcash.10"
          }
        }
      ],
      "files": [
        {
          "name": "cosantakit-v0.1.0-pcash.10.aar",
          "url": "cosantakit-v0.1.0-pcash.10.aar",
          "size": 286119,
          "sha512": "5821749956cecbea7646275026f911fc7b7f04de096501e76d81b8988be3174d05773d016669a8e454dd95ce667e7e62da1cc66fda7b36a1e138d208cfab1269",
          "sha256": "49781c961aac252f9e2fd3489a1beff908f5799f568e2f8d35c055930546d331",
          "sha1": "d2e899aa08542625bf14acece27b41d9e1a8dcf9",
          "md5": "3c99c4b9bc93dc5c82c1b401a7074fc4"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "cosantakit-v0.1.0-pcash.10-sources.jar",
          "url": "cosantakit-v0.1.0-pcash.10-sources.jar",
          "size": 285312,
          "sha512": "67636a2b32c0c11cdaa9b984395f03986d85869625d26a3870e3308df1130246fc627b136d9d181921b03281f929e66788cae6672ff9e41d1c677437a421c126",
          "sha256": "a5856d2e8c728a38009450b05d14c71f8b02d361ac23f8ec5a85ea0c55ee3257",
          "sha1": "a68c63d1c3cac2e144ac9ea84351dd2cb03a62e5",
          "md5": "bc623efa2720eaeacfc0153a32530558"
        }
      ]
    }
  ]
}
