{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "piratecashkit",
    "version": "v0.1.0-pcash.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "v0.1.0-pcash.15"
          }
        }
      ],
      "files": [
        {
          "name": "piratecashkit-v0.1.0-pcash.15.aar",
          "url": "piratecashkit-v0.1.0-pcash.15.aar",
          "size": 290696,
          "sha512": "4e59a6dc9e7376b767453dfb2ceb7e72d7a8768be3ddc3c1bd9779a6126ed27b5fffb58610cd2825782ef3ed5263cbb31d10fd58148976c3644ab29f9fcd9ab2",
          "sha256": "9ee6701ac301cb380d10991fd9db501e063eeba5f1ca1d924b73b9561e4a840e",
          "sha1": "527008c7bc40bf212463c888baeba4df01e907fe",
          "md5": "8af7ed5473f3743c764d38ee03ad4b88"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "dashlib",
          "version": {
            "requires": "v0.1.0-pcash.15"
          }
        },
        {
          "group": "de.sfuhrm",
          "module": "saphir-hash-jca",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "com.github.all3fox",
          "module": "lyra2",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "v0.1.0-pcash.15"
          }
        }
      ],
      "files": [
        {
          "name": "piratecashkit-v0.1.0-pcash.15.aar",
          "url": "piratecashkit-v0.1.0-pcash.15.aar",
          "size": 290696,
          "sha512": "4e59a6dc9e7376b767453dfb2ceb7e72d7a8768be3ddc3c1bd9779a6126ed27b5fffb58610cd2825782ef3ed5263cbb31d10fd58148976c3644ab29f9fcd9ab2",
          "sha256": "9ee6701ac301cb380d10991fd9db501e063eeba5f1ca1d924b73b9561e4a840e",
          "sha1": "527008c7bc40bf212463c888baeba4df01e907fe",
          "md5": "8af7ed5473f3743c764d38ee03ad4b88"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "piratecashkit-v0.1.0-pcash.15-sources.jar",
          "url": "piratecashkit-v0.1.0-pcash.15-sources.jar",
          "size": 291529,
          "sha512": "5478a000ede7d244157d6fa3c306661f9681118ec64b3eb658a9934c42321b99f5d756cd301c623e128012e4d0cba32db596fc7580eae033e369efff8d89ce34",
          "sha256": "4b908ef589f454e9b7917177de9c505f7b118c8b5d8beb2c8412254783509834",
          "sha1": "8294f2efeb3ae7e34465ad125cc40910fcbe4ae0",
          "md5": "b208d672cb435becfc40cb4f86d96674"
        }
      ]
    }
  ]
}
