{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "litecoinkit",
    "version": "d8d5778",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "d8d5778"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "hodler",
          "version": {
            "requires": "d8d5778"
          }
        }
      ],
      "files": [
        {
          "name": "litecoinkit-d8d5778.aar",
          "url": "litecoinkit-d8d5778.aar",
          "size": 523134,
          "sha512": "326105b2ce8aa2ec5f5bd47a52216ee56d94959e5d08c67ac187133ecb7ed155ea2cfe83c752b3cef1eec0ebe2ac995e99b89da6190a06860251a9bfcb20add1",
          "sha256": "e7707cb0234881f8c9958da2faebdf6b8cae5274a6f4ac55aaafc3df0b5cac7e",
          "sha1": "ddca6c3447718451d6aaf54e372a527db011706c",
          "md5": "1d6db772bc968f95d0071def0235dd44"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.github.piratecash",
          "module": "mwebd-android",
          "version": {
            "requires": "v0.1.19-pcash.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "d8d5778"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "hodler",
          "version": {
            "requires": "d8d5778"
          }
        }
      ],
      "files": [
        {
          "name": "litecoinkit-d8d5778.aar",
          "url": "litecoinkit-d8d5778.aar",
          "size": 523134,
          "sha512": "326105b2ce8aa2ec5f5bd47a52216ee56d94959e5d08c67ac187133ecb7ed155ea2cfe83c752b3cef1eec0ebe2ac995e99b89da6190a06860251a9bfcb20add1",
          "sha256": "e7707cb0234881f8c9958da2faebdf6b8cae5274a6f4ac55aaafc3df0b5cac7e",
          "sha1": "ddca6c3447718451d6aaf54e372a527db011706c",
          "md5": "1d6db772bc968f95d0071def0235dd44"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "litecoinkit-d8d5778-sources.jar",
          "url": "litecoinkit-d8d5778-sources.jar",
          "size": 262240,
          "sha512": "3e341d48cbbf90c1f7dc24fca750c3240d21aa298e6d987453d5fd8753ac0e1b1706efa486b2359f83e6e1e45f84be352987395c17af08ebe187a553d3a5d2ec",
          "sha256": "73773e2a033a67ba7c383441cf9feb28c97d62d54c24314e48016c16bd86d561",
          "sha1": "5794b17bbae6f2a3f644e8fa5a64ac45ec00bff8",
          "md5": "f32d640fde2684d9e9a92b5d9dc138a6"
        }
      ]
    }
  ]
}
