{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "piratecashkit",
    "version": "3cd5d1b",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "3cd5d1b"
          }
        }
      ],
      "files": [
        {
          "name": "piratecashkit-3cd5d1b.aar",
          "url": "piratecashkit-3cd5d1b.aar",
          "size": 290600,
          "sha512": "6fd57cd9ee49ee069cc0ef6fd5dc55fa1156fd396c047db3d8ac5546a0a4e143c2c6a9f36b9b20ad9e9b16bf3bfa6edbc0cfd20797c4161163ed455d6c343e06",
          "sha256": "b84074fd3f97e655f1841f0f65374f749654ff10d346aafa57836792b1fb9535",
          "sha1": "bca909749e3d30bf624433f76c3854ca81445fb2",
          "md5": "6c30294aac39c65e6540af857876ee2f"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "dashlib",
          "version": {
            "requires": "3cd5d1b"
          }
        },
        {
          "group": "de.sfuhrm",
          "module": "saphir-hash-jca",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "com.github.all3fox",
          "module": "lyra2",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "3cd5d1b"
          }
        }
      ],
      "files": [
        {
          "name": "piratecashkit-3cd5d1b.aar",
          "url": "piratecashkit-3cd5d1b.aar",
          "size": 290600,
          "sha512": "6fd57cd9ee49ee069cc0ef6fd5dc55fa1156fd396c047db3d8ac5546a0a4e143c2c6a9f36b9b20ad9e9b16bf3bfa6edbc0cfd20797c4161163ed455d6c343e06",
          "sha256": "b84074fd3f97e655f1841f0f65374f749654ff10d346aafa57836792b1fb9535",
          "sha1": "bca909749e3d30bf624433f76c3854ca81445fb2",
          "md5": "6c30294aac39c65e6540af857876ee2f"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "piratecashkit-3cd5d1b-sources.jar",
          "url": "piratecashkit-3cd5d1b-sources.jar",
          "size": 289464,
          "sha512": "6575538e9b9cc6a2a437967665e510c432b16edbf3943aba61c1dc101d35fc2a083e869e4dc5db5c11013cbffe0c325a97a8c1cf5a62ab2226f3c6c7ea5dd053",
          "sha256": "04b007e3e7a93b3f12f62156859ee042082ffc873d4f0d75c64afbd59402dd39",
          "sha1": "5f205606ccaa4cd9ce7d6c9731c476d0f7ddddd6",
          "md5": "811f31efd2ed5e4d6db22265ef6c0068"
        }
      ]
    }
  ]
}
