{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "bitcoincore",
    "version": "5e3abae",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash",
          "module": "hd-wallet-kit-android",
          "version": {
            "requires": "46a441d"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bitcoincore-5e3abae.aar",
          "url": "bitcoincore-5e3abae.aar",
          "size": 1087122,
          "sha512": "8b34aa3ca3e1bf0fce2b9b2bfffad4534645be34043e59560f4fb85c995a9b158985112287e93a9209d98b35602819e089a601dcee2ca76d9895eae681fd0154",
          "sha256": "b65c8835788e0a05fc742e37e3d325ff838161f82640b5a52fafba872be3cb18",
          "sha1": "51c06f2427437a624777a1384c5502fe66f1f4e9",
          "md5": "445c8df528ade5be0426244cf85ddbc4"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.5.0"
          }
        },
        {
          "group": "com.github.piratecash",
          "module": "hd-wallet-kit-android",
          "version": {
            "requires": "46a441d"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bitcoincore-5e3abae.aar",
          "url": "bitcoincore-5e3abae.aar",
          "size": 1087122,
          "sha512": "8b34aa3ca3e1bf0fce2b9b2bfffad4534645be34043e59560f4fb85c995a9b158985112287e93a9209d98b35602819e089a601dcee2ca76d9895eae681fd0154",
          "sha256": "b65c8835788e0a05fc742e37e3d325ff838161f82640b5a52fafba872be3cb18",
          "sha1": "51c06f2427437a624777a1384c5502fe66f1f4e9",
          "md5": "445c8df528ade5be0426244cf85ddbc4"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "bitcoincore-5e3abae-sources.jar",
          "url": "bitcoincore-5e3abae-sources.jar",
          "size": 1175185,
          "sha512": "df98fbde0a5ed59a45146aa3aacdc90ecc92f43e76623a244e29bee25ddf371e30605676d98bb5ba88bf26cabd3d8f35879aefdf1fa2030d9f026b68e9f20e9b",
          "sha256": "5138923b0f6728b6968b8d0c8b7cfed31f1095304a73f97dfe723d859ddd5595",
          "sha1": "a3b317bdd185668bf0febdadf15e97018ea6b1b4",
          "md5": "db93381bc2843802ad31448f9eb16e00"
        }
      ]
    }
  ]
}
