{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "bitcoincore",
    "version": "7b64c21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash",
          "module": "hd-wallet-kit-android",
          "version": {
            "requires": "46a441d"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bitcoincore-7b64c21.aar",
          "url": "bitcoincore-7b64c21.aar",
          "size": 1150609,
          "sha512": "e11ac3aeaf96d1a34811c9fd9448d368b36485de37a7f6ef4db946ccadb9563f050b874e20a205201c7361c2ba385c3129638fb76f13072cf32dd0bdefbc111b",
          "sha256": "deec570c90e7e45241a29501c5ad30c7a8c7b0d72e36ea26becc7363e402e033",
          "sha1": "f395a1fb9c127f36d9970266178d8ec0af8df41c",
          "md5": "3be707b7cb67a3eaf228f714be5e2384"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.5.0"
          }
        },
        {
          "group": "com.github.piratecash",
          "module": "hd-wallet-kit-android",
          "version": {
            "requires": "46a441d"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bitcoincore-7b64c21.aar",
          "url": "bitcoincore-7b64c21.aar",
          "size": 1150609,
          "sha512": "e11ac3aeaf96d1a34811c9fd9448d368b36485de37a7f6ef4db946ccadb9563f050b874e20a205201c7361c2ba385c3129638fb76f13072cf32dd0bdefbc111b",
          "sha256": "deec570c90e7e45241a29501c5ad30c7a8c7b0d72e36ea26becc7363e402e033",
          "sha1": "f395a1fb9c127f36d9970266178d8ec0af8df41c",
          "md5": "3be707b7cb67a3eaf228f714be5e2384"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "bitcoincore-7b64c21-sources.jar",
          "url": "bitcoincore-7b64c21-sources.jar",
          "size": 1255450,
          "sha512": "bcfe1af78a731552ccbabbf803703f911d5b91fe40ec00770b59e30c1306f7ea606da9504a679ab6708ae5e1c51f7f52b7d3ba950959117e8bf35d5acfc6bed8",
          "sha256": "dc7afd0641a3c8eba0079fa7861143a463c6b83c02f961666d1a533873ea8413",
          "sha1": "e6ab48c3942de3484e2c4a29a5e9beda6c802b7d",
          "md5": "0237bfa002851b2a815cd6e55da6527f"
        }
      ]
    }
  ]
}
