{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "bitcoincore",
    "version": "8e318e2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash",
          "module": "hd-wallet-kit-android",
          "version": {
            "requires": "46a441d"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bitcoincore-8e318e2.aar",
          "url": "bitcoincore-8e318e2.aar",
          "size": 1240801,
          "sha512": "a2901c15c581fffa5736cb9998715c15896b0ca3ff9f08215d69805c9a87de577b6080f3040f46b8e8e97dc9a9a5adbb6c1f2a3e71eca086f9c843786efdebac",
          "sha256": "437f654cc48bf6232ff31b621c00172518a9c6d6fb401c73fd418b57c5749bd5",
          "sha1": "2f1260811dfe53d5231198ee9d6fb8823742dc04",
          "md5": "87e5a1a84b773fa9c85f5e075db63898"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.5.0"
          }
        },
        {
          "group": "com.github.piratecash",
          "module": "hd-wallet-kit-android",
          "version": {
            "requires": "46a441d"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bitcoincore-8e318e2.aar",
          "url": "bitcoincore-8e318e2.aar",
          "size": 1240801,
          "sha512": "a2901c15c581fffa5736cb9998715c15896b0ca3ff9f08215d69805c9a87de577b6080f3040f46b8e8e97dc9a9a5adbb6c1f2a3e71eca086f9c843786efdebac",
          "sha256": "437f654cc48bf6232ff31b621c00172518a9c6d6fb401c73fd418b57c5749bd5",
          "sha1": "2f1260811dfe53d5231198ee9d6fb8823742dc04",
          "md5": "87e5a1a84b773fa9c85f5e075db63898"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "bitcoincore-8e318e2-sources.jar",
          "url": "bitcoincore-8e318e2-sources.jar",
          "size": 1446922,
          "sha512": "25fcdfc5c2fac5375bdecb921c207f325d832be1c9e5d93291e9c7b4321a092f01d2e4bba234af03c9f84c3467c1f6feb7bb804ab4feee156367e8cb39cc1a5a",
          "sha256": "77e3d21c49117855a128935e9ab433d6d4d5a3fdb7b2d7ed352c66b7191c8dce",
          "sha1": "55a4297ab469ea39d733f9a80b36bfdcaebcaf47",
          "md5": "614d3e51a1778c6ac2c2270785a66e06"
        }
      ]
    }
  ]
}
