{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "bitcoincore",
    "version": "a079b81",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash",
          "module": "hd-wallet-kit-android",
          "version": {
            "requires": "46a441d"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bitcoincore-a079b81.aar",
          "url": "bitcoincore-a079b81.aar",
          "size": 1126542,
          "sha512": "1e50b2d1a9f75208a88f43e2106b2deea8bd6b18619b8015a3376403092dcc55fa7fe056cc6c244e5dde181158d039eaf4943953b23be414ac760349a0ed28e3",
          "sha256": "a2acc96b68dc8169314f775243199cdea2e5194f9414de7f9b7366ff3b4ef633",
          "sha1": "7c49a8192536de0722b1f580033ab99fc81484f0",
          "md5": "f85099feee137a5614cde2073a5365a5"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.5.0"
          }
        },
        {
          "group": "com.github.piratecash",
          "module": "hd-wallet-kit-android",
          "version": {
            "requires": "46a441d"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bitcoincore-a079b81.aar",
          "url": "bitcoincore-a079b81.aar",
          "size": 1126542,
          "sha512": "1e50b2d1a9f75208a88f43e2106b2deea8bd6b18619b8015a3376403092dcc55fa7fe056cc6c244e5dde181158d039eaf4943953b23be414ac760349a0ed28e3",
          "sha256": "a2acc96b68dc8169314f775243199cdea2e5194f9414de7f9b7366ff3b4ef633",
          "sha1": "7c49a8192536de0722b1f580033ab99fc81484f0",
          "md5": "f85099feee137a5614cde2073a5365a5"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "bitcoincore-a079b81-sources.jar",
          "url": "bitcoincore-a079b81-sources.jar",
          "size": 1198568,
          "sha512": "a6bd8ac62711232b956e60b71fd0c346fa8c0abb6caa1ceed3089a5d9b37992a41ca711270cebad8ced9cf495fb36ffd5f5e59ae2dfb68e8aba920aa82a9e823",
          "sha256": "4077eb33c5aad1a66547e4b1725dc68be70d03de75a9ad99e05abe64d7c90bf9",
          "sha1": "524924657f79f5512e8932c5f53610376a6f15bf",
          "md5": "11196970393fc427127352c7c77007f1"
        }
      ]
    }
  ]
}
