{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "bitcoincore",
    "version": "de0ca47",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash",
          "module": "hd-wallet-kit-android",
          "version": {
            "requires": "46a441d"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bitcoincore-de0ca47.aar",
          "url": "bitcoincore-de0ca47.aar",
          "size": 1122027,
          "sha512": "292f0a2a31075944827666047167b133c62bd1821a1e477a1aaa21e40278138753c8d45119b399d8f8e6c65a44a449d93416a93b8a78f2559925042dd143bf50",
          "sha256": "0c908001c861a1908792a9dc58fad40c41eaad85950d8a0edc8a00b11c1ca8a7",
          "sha1": "f3a670775c8f64126a4e07b228a70f0b98450341",
          "md5": "d5330815ab6ef32503705b6304a72b56"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.5.0"
          }
        },
        {
          "group": "com.github.piratecash",
          "module": "hd-wallet-kit-android",
          "version": {
            "requires": "46a441d"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bitcoincore-de0ca47.aar",
          "url": "bitcoincore-de0ca47.aar",
          "size": 1122027,
          "sha512": "292f0a2a31075944827666047167b133c62bd1821a1e477a1aaa21e40278138753c8d45119b399d8f8e6c65a44a449d93416a93b8a78f2559925042dd143bf50",
          "sha256": "0c908001c861a1908792a9dc58fad40c41eaad85950d8a0edc8a00b11c1ca8a7",
          "sha1": "f3a670775c8f64126a4e07b228a70f0b98450341",
          "md5": "d5330815ab6ef32503705b6304a72b56"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "bitcoincore-de0ca47-sources.jar",
          "url": "bitcoincore-de0ca47-sources.jar",
          "size": 1194518,
          "sha512": "bcc3f98e3ef4ba29ec90c840c28f424fae92464b223219bb7a7b51c5d489493b7d1b83ed581130f7e5cecc75afeb2e38b98b9a2f7342a07be8f92f45d5def81d",
          "sha256": "40a3660230d192b291998e7dc08d6dc5243297beff4cbd62a5f064ed8fa56cb5",
          "sha1": "7022e6b1414a3e247b32cd9da34bbd0dc3b6627d",
          "md5": "7cb966cb090156c71bd7a8ffd7107510"
        }
      ]
    }
  ]
}
