{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "dashkit",
    "version": "a49d6b8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "a49d6b8"
          }
        }
      ],
      "files": [
        {
          "name": "dashkit-a49d6b8.aar",
          "url": "dashkit-a49d6b8.aar",
          "size": 234837,
          "sha512": "e94ea8453e76673b827d5a9672b7b8d85c46773f8afc97ccaa805ccea85e12b3c5959d2cc6bb7bbc021739541cbdb68aefe18185ce906d2c74f4599886537ec0",
          "sha256": "010171257ef95e69878461ddd4297960bd5495989eccc43321efb5832b2125a6",
          "sha1": "b4dd684351cc66b762a33da53335c4fd911895f6",
          "md5": "8a4aed5a8c745c2ab84adc1c7064cdb1"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "dashlib",
          "version": {
            "requires": "a49d6b8"
          }
        },
        {
          "group": "de.sfuhrm",
          "module": "saphir-hash-jca",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "a49d6b8"
          }
        }
      ],
      "files": [
        {
          "name": "dashkit-a49d6b8.aar",
          "url": "dashkit-a49d6b8.aar",
          "size": 234837,
          "sha512": "e94ea8453e76673b827d5a9672b7b8d85c46773f8afc97ccaa805ccea85e12b3c5959d2cc6bb7bbc021739541cbdb68aefe18185ce906d2c74f4599886537ec0",
          "sha256": "010171257ef95e69878461ddd4297960bd5495989eccc43321efb5832b2125a6",
          "sha1": "b4dd684351cc66b762a33da53335c4fd911895f6",
          "md5": "8a4aed5a8c745c2ab84adc1c7064cdb1"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "dashkit-a49d6b8-sources.jar",
          "url": "dashkit-a49d6b8-sources.jar",
          "size": 279921,
          "sha512": "12e7c981971a255a90539fd9208dc09367a796c1ae21a283583c4a31b1892c78b032b17ca92aff6b04e8bec22d75cdc415666148948e7afd3ca263c38be82f3d",
          "sha256": "5fdc51560a33edc86baa65fd50b64a256c88b288816b6e5ff772a441c25d98d3",
          "sha1": "3df9278532ca8dc1d9af153f28f65440cb489b70",
          "md5": "4ca0a80178a5db5306b0111a1b354e19"
        }
      ]
    }
  ]
}
