{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "litecoinkit",
    "version": "5947821",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "5947821"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "hodler",
          "version": {
            "requires": "5947821"
          }
        }
      ],
      "files": [
        {
          "name": "litecoinkit-5947821.aar",
          "url": "litecoinkit-5947821.aar",
          "size": 522332,
          "sha512": "efd54d8d127c3e835182a0d424c995c4764830e8e940d55dafc1a6db585eec214f9d879f7062e67dedfa07fb34e22e777b40f480bbdfe2c14788410880e6c9d6",
          "sha256": "74147c21c3ea45446c956ebba09320be917f49ef97fdc5eafae74caf032494fb",
          "sha1": "feded77e33df0bc524eb3f1fad9e471b0c2f2dee",
          "md5": "97cb14f023c6af64feee67c3afb424f6"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.github.piratecash",
          "module": "mwebd-android",
          "version": {
            "requires": "v0.1.19-pcash.7"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "5947821"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "hodler",
          "version": {
            "requires": "5947821"
          }
        }
      ],
      "files": [
        {
          "name": "litecoinkit-5947821.aar",
          "url": "litecoinkit-5947821.aar",
          "size": 522332,
          "sha512": "efd54d8d127c3e835182a0d424c995c4764830e8e940d55dafc1a6db585eec214f9d879f7062e67dedfa07fb34e22e777b40f480bbdfe2c14788410880e6c9d6",
          "sha256": "74147c21c3ea45446c956ebba09320be917f49ef97fdc5eafae74caf032494fb",
          "sha1": "feded77e33df0bc524eb3f1fad9e471b0c2f2dee",
          "md5": "97cb14f023c6af64feee67c3afb424f6"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "litecoinkit-5947821-sources.jar",
          "url": "litecoinkit-5947821-sources.jar",
          "size": 262505,
          "sha512": "5c7e1f56b278e0450b451ca810ed1b580306c7d9e70672841d0f98822a5a48d6cc236ea45eae90ecb034ad3f44bd0a859edf7c9b5d31e9e9161313cefd9c181a",
          "sha256": "26d6eddc69df5bef708955a6eea719fea43e2702e4c119c91d3cda2c69f1d657",
          "sha1": "080f07bae7296272cb7f146ee1a85f107954bece",
          "md5": "ce06671cc8b915995e86af63fca760f8"
        }
      ]
    }
  ]
}
