{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "dashkit",
    "version": "545988c",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "545988c"
          }
        }
      ],
      "files": [
        {
          "name": "dashkit-545988c.aar",
          "url": "dashkit-545988c.aar",
          "size": 234837,
          "sha512": "e94ea8453e76673b827d5a9672b7b8d85c46773f8afc97ccaa805ccea85e12b3c5959d2cc6bb7bbc021739541cbdb68aefe18185ce906d2c74f4599886537ec0",
          "sha256": "010171257ef95e69878461ddd4297960bd5495989eccc43321efb5832b2125a6",
          "sha1": "b4dd684351cc66b762a33da53335c4fd911895f6",
          "md5": "8a4aed5a8c745c2ab84adc1c7064cdb1"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "dashlib",
          "version": {
            "requires": "545988c"
          }
        },
        {
          "group": "de.sfuhrm",
          "module": "saphir-hash-jca",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "545988c"
          }
        }
      ],
      "files": [
        {
          "name": "dashkit-545988c.aar",
          "url": "dashkit-545988c.aar",
          "size": 234837,
          "sha512": "e94ea8453e76673b827d5a9672b7b8d85c46773f8afc97ccaa805ccea85e12b3c5959d2cc6bb7bbc021739541cbdb68aefe18185ce906d2c74f4599886537ec0",
          "sha256": "010171257ef95e69878461ddd4297960bd5495989eccc43321efb5832b2125a6",
          "sha1": "b4dd684351cc66b762a33da53335c4fd911895f6",
          "md5": "8a4aed5a8c745c2ab84adc1c7064cdb1"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "dashkit-545988c-sources.jar",
          "url": "dashkit-545988c-sources.jar",
          "size": 279921,
          "sha512": "2c4bad3b5997b07ddbf41d016b01920ffda03c6ce6725c71e3014e160a8ef3892619a8346c446b7fdd97128154ba9121d1d32d1fd759ab9663f3a6959d57c931",
          "sha256": "e75ef7b30246cc847c4b600952509dd8f8a1ddfc5a7479e77ab3f13475741662",
          "sha1": "4bcd4ce0a20ec1074216549b9cdd278df43b4133",
          "md5": "b600324e9e2a368f850827ec99b301e3"
        }
      ]
    }
  ]
}
