{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "cosantakit",
    "version": "bbf7636",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "bbf7636"
          }
        }
      ],
      "files": [
        {
          "name": "cosantakit-bbf7636.aar",
          "url": "cosantakit-bbf7636.aar",
          "size": 286368,
          "sha512": "7a690794c4960514404b7f4c3e3854c59416999f82d580c0bc0aaf1439e32333bc4eb4422bfecd7921b2bfe5fce42e36df55b93de2f605db1957216958105b96",
          "sha256": "3b202bdc9da3be620eef92ccce1398ac02b377ec193b03baf3b5e27a136fcec7",
          "sha1": "d1a5fc3cc2aa6bd73113949b8354be3bc6b92a7c",
          "md5": "1ec9f69ad900ff0cf54b2e2ebe69365a"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "dashlib",
          "version": {
            "requires": "bbf7636"
          }
        },
        {
          "group": "de.sfuhrm",
          "module": "saphir-hash-jca",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "com.github.all3fox",
          "module": "lyra2",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "bbf7636"
          }
        }
      ],
      "files": [
        {
          "name": "cosantakit-bbf7636.aar",
          "url": "cosantakit-bbf7636.aar",
          "size": 286368,
          "sha512": "7a690794c4960514404b7f4c3e3854c59416999f82d580c0bc0aaf1439e32333bc4eb4422bfecd7921b2bfe5fce42e36df55b93de2f605db1957216958105b96",
          "sha256": "3b202bdc9da3be620eef92ccce1398ac02b377ec193b03baf3b5e27a136fcec7",
          "sha1": "d1a5fc3cc2aa6bd73113949b8354be3bc6b92a7c",
          "md5": "1ec9f69ad900ff0cf54b2e2ebe69365a"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "cosantakit-bbf7636-sources.jar",
          "url": "cosantakit-bbf7636-sources.jar",
          "size": 288092,
          "sha512": "6029321cb32fee23264561aa63496ef41c225469c8727693aa12ab2de3c13c0659fb2b75066c640c7a2d7ac9051e87d83e7fd8ac15bccae607d0f806e1cf23f1",
          "sha256": "e382430e44f3739f6390c6cef0cd896d8123142ca6fe1232a139ef525aebf75c",
          "sha1": "fd88ee6c70a5afa3e30b454519e6f2ca6903c38d",
          "md5": "54f3d5f233d272e4d1b9fdb80f8933fe"
        }
      ]
    }
  ]
}
