{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "piratecashkit",
    "version": "v0.1.0-pcash.26",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "v0.1.0-pcash.26"
          }
        }
      ],
      "files": [
        {
          "name": "piratecashkit-v0.1.0-pcash.26.aar",
          "url": "piratecashkit-v0.1.0-pcash.26.aar",
          "size": 287782,
          "sha512": "b85b8c5a31f7abb595ce798a817b50c94d17e52630f85b321dd03c9d485af61a38b54655478705f10fb7a9b3bec6bbc1bf499b5349ff288b0b48fe124f087b2a",
          "sha256": "2a2509a13f3bd9d87d78aaac032165fe23986649d1468f114fabcf519f4e8b75",
          "sha1": "ff1c0cf7441a4c4624de92820fcad011939bde55",
          "md5": "f3c6601a1f67791ca066f6b4ab5318e4"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "dashlib",
          "version": {
            "requires": "v0.1.0-pcash.26"
          }
        },
        {
          "group": "de.sfuhrm",
          "module": "saphir-hash-jca",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "com.github.all3fox",
          "module": "lyra2",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "v0.1.0-pcash.26"
          }
        }
      ],
      "files": [
        {
          "name": "piratecashkit-v0.1.0-pcash.26.aar",
          "url": "piratecashkit-v0.1.0-pcash.26.aar",
          "size": 287782,
          "sha512": "b85b8c5a31f7abb595ce798a817b50c94d17e52630f85b321dd03c9d485af61a38b54655478705f10fb7a9b3bec6bbc1bf499b5349ff288b0b48fe124f087b2a",
          "sha256": "2a2509a13f3bd9d87d78aaac032165fe23986649d1468f114fabcf519f4e8b75",
          "sha1": "ff1c0cf7441a4c4624de92820fcad011939bde55",
          "md5": "f3c6601a1f67791ca066f6b4ab5318e4"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "piratecashkit-v0.1.0-pcash.26-sources.jar",
          "url": "piratecashkit-v0.1.0-pcash.26-sources.jar",
          "size": 292764,
          "sha512": "5d53d9908e62cb5af90b549e74b026b0ee9e56e0a595d39fff573ffc0168570ecfb5154cd730d85a74e008aa48999d0f108ae15709b7c90a7acbd1700a88b63e",
          "sha256": "59c0d99288dabd401ca8db1b0fc190a9052fdc83a9014c15e01687e6156cea89",
          "sha1": "eca604651a4729c87257d78010524de784aa7b00",
          "md5": "69311e88773ec1a84101aeb19f638afd"
        }
      ]
    }
  ]
}
