{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "litecoinkit",
    "version": "fd27852",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "fd27852"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "hodler",
          "version": {
            "requires": "fd27852"
          }
        }
      ],
      "files": [
        {
          "name": "litecoinkit-fd27852.aar",
          "url": "litecoinkit-fd27852.aar",
          "size": 390977,
          "sha512": "a65ca780019bbbaadfb6375a3e47ee3c41d1ecb42f3a4557637b210dbfbfb605198a9cd8d7a010115d30a0c652e57135de87280ab06090924442a5d37c243608",
          "sha256": "5637d12538c6826fb4f90f5e332ce57d334b1f796624ec36188acf27386bd9f2",
          "sha1": "dd868f930c5cc1f27713c2e77abed519b7382159",
          "md5": "f7e1b9eb02adf0c36c534862e85f464b"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.github.piratecash",
          "module": "mwebd-android",
          "version": {
            "requires": "v0.1.19-pcash.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "fd27852"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "hodler",
          "version": {
            "requires": "fd27852"
          }
        }
      ],
      "files": [
        {
          "name": "litecoinkit-fd27852.aar",
          "url": "litecoinkit-fd27852.aar",
          "size": 390977,
          "sha512": "a65ca780019bbbaadfb6375a3e47ee3c41d1ecb42f3a4557637b210dbfbfb605198a9cd8d7a010115d30a0c652e57135de87280ab06090924442a5d37c243608",
          "sha256": "5637d12538c6826fb4f90f5e332ce57d334b1f796624ec36188acf27386bd9f2",
          "sha1": "dd868f930c5cc1f27713c2e77abed519b7382159",
          "md5": "f7e1b9eb02adf0c36c534862e85f464b"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "litecoinkit-fd27852-sources.jar",
          "url": "litecoinkit-fd27852-sources.jar",
          "size": 255285,
          "sha512": "586716c7c1b2137e4245204e0e9d7083f625b1df9e71a36dbe2d745513de2d9c2d425d81cbcb2ca59b9a5fcad91ecb3d211cd7f8697bd3d0d4e0f7fa8b9368eb",
          "sha256": "58536143f1284cfe599b82067cb6acfa55bcc87c4a0c81ad04c363f30933dc99",
          "sha1": "ed6990ad29b9e6c0c58663bf7759ed7a4dd24230",
          "md5": "1fb94cee9c4799f956472c3baf760150"
        }
      ]
    }
  ]
}
