{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "litecoinkit",
    "version": "91b9795",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "91b9795"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "hodler",
          "version": {
            "requires": "91b9795"
          }
        }
      ],
      "files": [
        {
          "name": "litecoinkit-91b9795.aar",
          "url": "litecoinkit-91b9795.aar",
          "size": 523606,
          "sha512": "34b316d0b91ad72e500415797c220a5102a22355ce8dc99bc1c21fe917cc8ef23bb4da0c38854f9cdedab767a3a384bc09b3ee80c42094067e755ed5bae50b3e",
          "sha256": "3a196f6ea66430d7e84d0b2fb546a6b1d5dd6e63a0e64f4c296af6b413bec660",
          "sha1": "e6239ab73108aac6571e44e38a3007ba011768d5",
          "md5": "0de1fd1de30470c418dde9ce95d81fda"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.github.piratecash",
          "module": "mwebd-android",
          "version": {
            "requires": "v0.1.19-pcash.7"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "91b9795"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "hodler",
          "version": {
            "requires": "91b9795"
          }
        }
      ],
      "files": [
        {
          "name": "litecoinkit-91b9795.aar",
          "url": "litecoinkit-91b9795.aar",
          "size": 523606,
          "sha512": "34b316d0b91ad72e500415797c220a5102a22355ce8dc99bc1c21fe917cc8ef23bb4da0c38854f9cdedab767a3a384bc09b3ee80c42094067e755ed5bae50b3e",
          "sha256": "3a196f6ea66430d7e84d0b2fb546a6b1d5dd6e63a0e64f4c296af6b413bec660",
          "sha1": "e6239ab73108aac6571e44e38a3007ba011768d5",
          "md5": "0de1fd1de30470c418dde9ce95d81fda"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "litecoinkit-91b9795-sources.jar",
          "url": "litecoinkit-91b9795-sources.jar",
          "size": 262710,
          "sha512": "c3a1f1e2ccecd86b66f43dd10714e1ef1d151219213283029bf7a9c0568aed1120a56d2050b482e24496396cc69d51896cd115c2115fa199bf58ea2347cc265f",
          "sha256": "09965dd406cbb7f0134c5530dc39e63709bb1525194307c73e2bdb18dc8ebe9e",
          "sha1": "daf84c2f4fe4af3e72f5c87d4a517ea684d308e1",
          "md5": "2cd22743602e41ad7b0b74a0aa9082ee"
        }
      ]
    }
  ]
}
