{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "bitcoincore",
    "version": "v0.1.0-pcash.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash",
          "module": "hd-wallet-kit-android",
          "version": {
            "requires": "46a441d"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bitcoincore-v0.1.0-pcash.4.aar",
          "url": "bitcoincore-v0.1.0-pcash.4.aar",
          "size": 1125111,
          "sha512": "4e8dabc0d3d08b5de13eabf9b72d63165450f51db3720c1d6a93e6862b9359d2c7b1b0816a9e4c22df8be4789a4ab6d8e91081700e4e757d3dc119bccbe08d6b",
          "sha256": "67e80cd1da34169baade7168dad3c02ef5374999506724aa52ec05daac30b0a6",
          "sha1": "9a6f682fdeeeee7b69c375340677675dbcd848ff",
          "md5": "c3666f4f5d44badc43f73c50d7f848b0"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.5.0"
          }
        },
        {
          "group": "com.github.piratecash",
          "module": "hd-wallet-kit-android",
          "version": {
            "requires": "46a441d"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bitcoincore-v0.1.0-pcash.4.aar",
          "url": "bitcoincore-v0.1.0-pcash.4.aar",
          "size": 1125111,
          "sha512": "4e8dabc0d3d08b5de13eabf9b72d63165450f51db3720c1d6a93e6862b9359d2c7b1b0816a9e4c22df8be4789a4ab6d8e91081700e4e757d3dc119bccbe08d6b",
          "sha256": "67e80cd1da34169baade7168dad3c02ef5374999506724aa52ec05daac30b0a6",
          "sha1": "9a6f682fdeeeee7b69c375340677675dbcd848ff",
          "md5": "c3666f4f5d44badc43f73c50d7f848b0"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "bitcoincore-v0.1.0-pcash.4-sources.jar",
          "url": "bitcoincore-v0.1.0-pcash.4-sources.jar",
          "size": 1203563,
          "sha512": "2354b83ce7330e170c60df3f9989ec2bd26f95a79b1f48dcf3d627a9298db307a322ac73c80451e98bdc183224784c9bb4854dd4daa19c77cd94704b56bed919",
          "sha256": "9462f9b7845294221015c0491c8ae96afe107f6dd5c6463f13920e1a1af94fdb",
          "sha1": "47783076a78f102ef408e303930588038433fb81",
          "md5": "296867bdfd62d6f3d98a571872bcb486"
        }
      ]
    }
  ]
}
