{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "bitcoincore",
    "version": "v0.1.0-pcash.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash",
          "module": "hd-wallet-kit-android",
          "version": {
            "requires": "46a441d"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bitcoincore-v0.1.0-pcash.7.aar",
          "url": "bitcoincore-v0.1.0-pcash.7.aar",
          "size": 1125715,
          "sha512": "8bec7179c8381d820c4920aa0d48b9a1e8397ec738e78b5140e06f0aec456c59c1d4b78a1f8b910fa8d8f116c593dc4715033d2016e02295019062eb05478791",
          "sha256": "1eb2071594efb9e36364f537c700880c109d1916ddccc599082b27ebd8056f12",
          "sha1": "197febde70291428afb5fd7ce3263b046211426b",
          "md5": "ad1ce99ec899dbb50f9d2495b5c32d9b"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.5.0"
          }
        },
        {
          "group": "com.github.piratecash",
          "module": "hd-wallet-kit-android",
          "version": {
            "requires": "46a441d"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bitcoincore-v0.1.0-pcash.7.aar",
          "url": "bitcoincore-v0.1.0-pcash.7.aar",
          "size": 1125715,
          "sha512": "8bec7179c8381d820c4920aa0d48b9a1e8397ec738e78b5140e06f0aec456c59c1d4b78a1f8b910fa8d8f116c593dc4715033d2016e02295019062eb05478791",
          "sha256": "1eb2071594efb9e36364f537c700880c109d1916ddccc599082b27ebd8056f12",
          "sha1": "197febde70291428afb5fd7ce3263b046211426b",
          "md5": "ad1ce99ec899dbb50f9d2495b5c32d9b"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "bitcoincore-v0.1.0-pcash.7-sources.jar",
          "url": "bitcoincore-v0.1.0-pcash.7-sources.jar",
          "size": 1204693,
          "sha512": "be4948a5a8a3be0f8eb0f70a2988a06cc946fdefa2965934ef6fb1d055584cfb7e814ada493b4197de9b4a246fad774adfaeab33af8aca5f13eb9c64ed815430",
          "sha256": "a1fb0354163493be95049a10c9913e2918c479605d5158d2ac8e28872849c2ef",
          "sha1": "d2cdcecdbd26e3dbabef23116504a284c95d5e84",
          "md5": "dcd1c41a16bc2afc26647bc52b3b456f"
        }
      ]
    }
  ]
}
