{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "piratecashkit",
    "version": "v0.1.0-pcash.27",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "v0.1.0-pcash.27"
          }
        }
      ],
      "files": [
        {
          "name": "piratecashkit-v0.1.0-pcash.27.aar",
          "url": "piratecashkit-v0.1.0-pcash.27.aar",
          "size": 287782,
          "sha512": "b85b8c5a31f7abb595ce798a817b50c94d17e52630f85b321dd03c9d485af61a38b54655478705f10fb7a9b3bec6bbc1bf499b5349ff288b0b48fe124f087b2a",
          "sha256": "2a2509a13f3bd9d87d78aaac032165fe23986649d1468f114fabcf519f4e8b75",
          "sha1": "ff1c0cf7441a4c4624de92820fcad011939bde55",
          "md5": "f3c6601a1f67791ca066f6b4ab5318e4"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "dashlib",
          "version": {
            "requires": "v0.1.0-pcash.27"
          }
        },
        {
          "group": "de.sfuhrm",
          "module": "saphir-hash-jca",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "com.github.all3fox",
          "module": "lyra2",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "v0.1.0-pcash.27"
          }
        }
      ],
      "files": [
        {
          "name": "piratecashkit-v0.1.0-pcash.27.aar",
          "url": "piratecashkit-v0.1.0-pcash.27.aar",
          "size": 287782,
          "sha512": "b85b8c5a31f7abb595ce798a817b50c94d17e52630f85b321dd03c9d485af61a38b54655478705f10fb7a9b3bec6bbc1bf499b5349ff288b0b48fe124f087b2a",
          "sha256": "2a2509a13f3bd9d87d78aaac032165fe23986649d1468f114fabcf519f4e8b75",
          "sha1": "ff1c0cf7441a4c4624de92820fcad011939bde55",
          "md5": "f3c6601a1f67791ca066f6b4ab5318e4"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "piratecashkit-v0.1.0-pcash.27-sources.jar",
          "url": "piratecashkit-v0.1.0-pcash.27-sources.jar",
          "size": 292764,
          "sha512": "98426c7a75cda59632f77a94a1c5b98a044636f4edddf6a1ded96bdd8b738f4d0780ba1ee2ae64de2d4e4ccb1753be868c51b62c58fdb331f351710d9bcd9cff",
          "sha256": "69943da76944eb47abce1c83b1fb7e7bc6e4ee533cf8214d751d6119f8d1cc41",
          "sha1": "1af7f52a319b8bf60fe65cace04bc697bf967a61",
          "md5": "1f18c17532a747307dcb5a0f82f5ff8e"
        }
      ]
    }
  ]
}
