{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "piratecashkit",
    "version": "dc3aa12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "dc3aa12"
          }
        }
      ],
      "files": [
        {
          "name": "piratecashkit-dc3aa12.aar",
          "url": "piratecashkit-dc3aa12.aar",
          "size": 290600,
          "sha512": "6fd57cd9ee49ee069cc0ef6fd5dc55fa1156fd396c047db3d8ac5546a0a4e143c2c6a9f36b9b20ad9e9b16bf3bfa6edbc0cfd20797c4161163ed455d6c343e06",
          "sha256": "b84074fd3f97e655f1841f0f65374f749654ff10d346aafa57836792b1fb9535",
          "sha1": "bca909749e3d30bf624433f76c3854ca81445fb2",
          "md5": "6c30294aac39c65e6540af857876ee2f"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "dashlib",
          "version": {
            "requires": "dc3aa12"
          }
        },
        {
          "group": "de.sfuhrm",
          "module": "saphir-hash-jca",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "com.github.all3fox",
          "module": "lyra2",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "dc3aa12"
          }
        }
      ],
      "files": [
        {
          "name": "piratecashkit-dc3aa12.aar",
          "url": "piratecashkit-dc3aa12.aar",
          "size": 290600,
          "sha512": "6fd57cd9ee49ee069cc0ef6fd5dc55fa1156fd396c047db3d8ac5546a0a4e143c2c6a9f36b9b20ad9e9b16bf3bfa6edbc0cfd20797c4161163ed455d6c343e06",
          "sha256": "b84074fd3f97e655f1841f0f65374f749654ff10d346aafa57836792b1fb9535",
          "sha1": "bca909749e3d30bf624433f76c3854ca81445fb2",
          "md5": "6c30294aac39c65e6540af857876ee2f"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "piratecashkit-dc3aa12-sources.jar",
          "url": "piratecashkit-dc3aa12-sources.jar",
          "size": 289464,
          "sha512": "45853cd96f3c2c18b7c36db0b1b81a201f7c11c61c0261c45957f817179045a4aaefa782187d63a04712a49d3453fb768b7eb95008b308b29c2796f64a85cc56",
          "sha256": "1b19b79c3c34b925267d04700adfb62b9fb15d66f4b49d0ca0bcb8d43490ea67",
          "sha1": "3ac04529a17ebd0e664472eeb0007de7566e2e07",
          "md5": "a284a4c72fdc2278b9258b48d88b910e"
        }
      ]
    }
  ]
}
