{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "piratecashkit",
    "version": "fadfbf9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "fadfbf9"
          }
        }
      ],
      "files": [
        {
          "name": "piratecashkit-fadfbf9.aar",
          "url": "piratecashkit-fadfbf9.aar",
          "size": 290596,
          "sha512": "d89324dd72560795183393dbf213cc0de511834f47654020c7cc7f8aa7ad034c714441381d439eb519cd0661b6c2f87678e4e7d5fe0805af65850ab96906b1eb",
          "sha256": "58ffee566e652799cdf1bdfbc9220c05259e32b0f2939636f3bd64b2bff5bde8",
          "sha1": "8e2d357225a91d1157dcdb1e4eddb072c0348573",
          "md5": "c5cf8bad87186a7ba7bfa7b678c65b13"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "dashlib",
          "version": {
            "requires": "fadfbf9"
          }
        },
        {
          "group": "de.sfuhrm",
          "module": "saphir-hash-jca",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "com.github.all3fox",
          "module": "lyra2",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "fadfbf9"
          }
        }
      ],
      "files": [
        {
          "name": "piratecashkit-fadfbf9.aar",
          "url": "piratecashkit-fadfbf9.aar",
          "size": 290596,
          "sha512": "d89324dd72560795183393dbf213cc0de511834f47654020c7cc7f8aa7ad034c714441381d439eb519cd0661b6c2f87678e4e7d5fe0805af65850ab96906b1eb",
          "sha256": "58ffee566e652799cdf1bdfbc9220c05259e32b0f2939636f3bd64b2bff5bde8",
          "sha1": "8e2d357225a91d1157dcdb1e4eddb072c0348573",
          "md5": "c5cf8bad87186a7ba7bfa7b678c65b13"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "piratecashkit-fadfbf9-sources.jar",
          "url": "piratecashkit-fadfbf9-sources.jar",
          "size": 289469,
          "sha512": "0c8cf7be80ed58568a26865f262412a262eb5e70b00f457c13dd16ad934099cb13327d5fa22b48cff91b02a28519905d02c01388bfe2c58909e71a7419b73dce",
          "sha256": "280e3d1e2cd1ebdcae9d60218f4834c485d4d7d2e871a3f40100d367ccf3e1f6",
          "sha1": "e9063abb964f3f79bf2d37c19bd5df5ca3f52982",
          "md5": "b7621a630cf0da29fa67287906ca9441"
        }
      ]
    }
  ]
}
