{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "bitcoincore",
    "version": "407858a",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash",
          "module": "hd-wallet-kit-android",
          "version": {
            "requires": "46a441d"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bitcoincore-407858a.aar",
          "url": "bitcoincore-407858a.aar",
          "size": 1125715,
          "sha512": "8bec7179c8381d820c4920aa0d48b9a1e8397ec738e78b5140e06f0aec456c59c1d4b78a1f8b910fa8d8f116c593dc4715033d2016e02295019062eb05478791",
          "sha256": "1eb2071594efb9e36364f537c700880c109d1916ddccc599082b27ebd8056f12",
          "sha1": "197febde70291428afb5fd7ce3263b046211426b",
          "md5": "ad1ce99ec899dbb50f9d2495b5c32d9b"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.5.0"
          }
        },
        {
          "group": "com.github.piratecash",
          "module": "hd-wallet-kit-android",
          "version": {
            "requires": "46a441d"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bitcoincore-407858a.aar",
          "url": "bitcoincore-407858a.aar",
          "size": 1125715,
          "sha512": "8bec7179c8381d820c4920aa0d48b9a1e8397ec738e78b5140e06f0aec456c59c1d4b78a1f8b910fa8d8f116c593dc4715033d2016e02295019062eb05478791",
          "sha256": "1eb2071594efb9e36364f537c700880c109d1916ddccc599082b27ebd8056f12",
          "sha1": "197febde70291428afb5fd7ce3263b046211426b",
          "md5": "ad1ce99ec899dbb50f9d2495b5c32d9b"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "bitcoincore-407858a-sources.jar",
          "url": "bitcoincore-407858a-sources.jar",
          "size": 1204693,
          "sha512": "aaa56504e829c1bb83f9b9fb951cf70e6053fd738cad00e5aad9781d5bcb4df6ac87b8e8cc7b452ed5c19077af6884c7cda2f5d5c29aa9b2cd1b8705174ce018",
          "sha256": "d04dd8281fdbfbf00a93ba6788f264916c40ec13c7d111161f817593866d10f7",
          "sha1": "dd24d59b04dbdd78f5294095c6d27ea8fbb52aa7",
          "md5": "135a206b71dd6837f379736f1198c0c2"
        }
      ]
    }
  ]
}
