{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "piratecashkit",
    "version": "545988c",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "545988c"
          }
        }
      ],
      "files": [
        {
          "name": "piratecashkit-545988c.aar",
          "url": "piratecashkit-545988c.aar",
          "size": 287782,
          "sha512": "b85b8c5a31f7abb595ce798a817b50c94d17e52630f85b321dd03c9d485af61a38b54655478705f10fb7a9b3bec6bbc1bf499b5349ff288b0b48fe124f087b2a",
          "sha256": "2a2509a13f3bd9d87d78aaac032165fe23986649d1468f114fabcf519f4e8b75",
          "sha1": "ff1c0cf7441a4c4624de92820fcad011939bde55",
          "md5": "f3c6601a1f67791ca066f6b4ab5318e4"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "dashlib",
          "version": {
            "requires": "545988c"
          }
        },
        {
          "group": "de.sfuhrm",
          "module": "saphir-hash-jca",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "com.github.all3fox",
          "module": "lyra2",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "545988c"
          }
        }
      ],
      "files": [
        {
          "name": "piratecashkit-545988c.aar",
          "url": "piratecashkit-545988c.aar",
          "size": 287782,
          "sha512": "b85b8c5a31f7abb595ce798a817b50c94d17e52630f85b321dd03c9d485af61a38b54655478705f10fb7a9b3bec6bbc1bf499b5349ff288b0b48fe124f087b2a",
          "sha256": "2a2509a13f3bd9d87d78aaac032165fe23986649d1468f114fabcf519f4e8b75",
          "sha1": "ff1c0cf7441a4c4624de92820fcad011939bde55",
          "md5": "f3c6601a1f67791ca066f6b4ab5318e4"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "piratecashkit-545988c-sources.jar",
          "url": "piratecashkit-545988c-sources.jar",
          "size": 292764,
          "sha512": "dfb1ec0075061080128453509f4ddb1c46f26f71a28b25c4af85acda226792086d007941e98f7048ed1b413895d5a30f897d05bc3584edbdb7d0ad7f7b07b79a",
          "sha256": "ea1c910d020b53338b4d289951cd8f776369c312cefad179384bd13465a1edfa",
          "sha1": "9d7080e1f07c3d58359d515d805faedf69e2ba49",
          "md5": "7e9b0e144dc44f0bfc274ef1cab2d9ce"
        }
      ]
    }
  ]
}
