{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "dashkit",
    "version": "1c68398",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "1c68398"
          }
        }
      ],
      "files": [
        {
          "name": "dashkit-1c68398.aar",
          "url": "dashkit-1c68398.aar",
          "size": 234128,
          "sha512": "84c3669e1afe9bcdef4486039ca0e4c9d2f80cf342ecb737051078e515fb59598dadf440797c83da0c63d479038962f3a91d9fb7c3fd7d77312ac6cedab2ca7b",
          "sha256": "1493d222991c97abb9e29533d349ae0465ea2e3a9742b0a72b56c3d86742c3b5",
          "sha1": "dea338b173237af0897325aca2eee3dbbd2eb8f8",
          "md5": "6576a40d84e2281b317be18d6c345e93"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.eclipsesource.minimal-json",
          "module": "minimal-json",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "dashlib",
          "version": {
            "requires": "1c68398"
          }
        },
        {
          "group": "de.sfuhrm",
          "module": "saphir-hash-jca",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "1c68398"
          }
        }
      ],
      "files": [
        {
          "name": "dashkit-1c68398.aar",
          "url": "dashkit-1c68398.aar",
          "size": 234128,
          "sha512": "84c3669e1afe9bcdef4486039ca0e4c9d2f80cf342ecb737051078e515fb59598dadf440797c83da0c63d479038962f3a91d9fb7c3fd7d77312ac6cedab2ca7b",
          "sha256": "1493d222991c97abb9e29533d349ae0465ea2e3a9742b0a72b56c3d86742c3b5",
          "sha1": "dea338b173237af0897325aca2eee3dbbd2eb8f8",
          "md5": "6576a40d84e2281b317be18d6c345e93"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "dashkit-1c68398-sources.jar",
          "url": "dashkit-1c68398-sources.jar",
          "size": 277466,
          "sha512": "3edca0d5b173d17e87fab3745ae14460511d79874db5e813b253cba860ae8366d42c380ed73f067c9f480382f7c0c8f033be5b3a9cde3df61655b9f649fdaa7b",
          "sha256": "b082285b0af1436458902b42fad2eeda09e79a688c4f4708b23f69035274f05f",
          "sha1": "1f6a7ae53c820850eaea8fbd6857b94390351781",
          "md5": "7731e3c294fb69fa7ea560c6ee6a98a0"
        }
      ]
    }
  ]
}
