{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash.bitcoin-kit-android",
    "module": "litecoinkit",
    "version": "51bb2eb",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "51bb2eb"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "hodler",
          "version": {
            "requires": "51bb2eb"
          }
        }
      ],
      "files": [
        {
          "name": "litecoinkit-51bb2eb.aar",
          "url": "litecoinkit-51bb2eb.aar",
          "size": 566607,
          "sha512": "f842b155c1940b7362e65b4296328f4a6c4d58696ed6fad205773c9fcfd2909a285e25732fba0a40aab6bc9b1ea99b3f44026b057a7d86ad8a8912c9edcff4ce",
          "sha256": "8863e675631633c1a736457076f4494950de7c8ae90d1d81c8606d668c1a753a",
          "sha1": "b4cd1b7a829d79b4d2e77d08982ac50b03c0587d",
          "md5": "b9e7bb98ea1e0623a00ae3f6c37b52c0"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.github.piratecash",
          "module": "mwebd-android",
          "version": {
            "requires": "v0.1.19-pcash.8"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "bitcoincore",
          "version": {
            "requires": "51bb2eb"
          }
        },
        {
          "group": "com.github.piratecash.bitcoin-kit-android",
          "module": "hodler",
          "version": {
            "requires": "51bb2eb"
          }
        }
      ],
      "files": [
        {
          "name": "litecoinkit-51bb2eb.aar",
          "url": "litecoinkit-51bb2eb.aar",
          "size": 566607,
          "sha512": "f842b155c1940b7362e65b4296328f4a6c4d58696ed6fad205773c9fcfd2909a285e25732fba0a40aab6bc9b1ea99b3f44026b057a7d86ad8a8912c9edcff4ce",
          "sha256": "8863e675631633c1a736457076f4494950de7c8ae90d1d81c8606d668c1a753a",
          "sha1": "b4cd1b7a829d79b4d2e77d08982ac50b03c0587d",
          "md5": "b9e7bb98ea1e0623a00ae3f6c37b52c0"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "litecoinkit-51bb2eb-sources.jar",
          "url": "litecoinkit-51bb2eb-sources.jar",
          "size": 288445,
          "sha512": "67e988bb2ced1f29b2d83b29301acb40b65efe6cd8ca71a2830a27dcf773ce373051e30008aeb8d9ad8ea37c28d34dbbbafd18a880f13afd4c125de731f5d6f1",
          "sha256": "414e7f8a15f89f81d87a4ccb5bc2f3dc2371e85f3e68559f8822a0322214131f",
          "sha1": "c3d2d025209aba25b8bec0c420773fe5454434ed",
          "md5": "7628ace304d95bcc3f16ceb62d4c7a50"
        }
      ]
    }
  ]
}
